wkr_ligand('').
wkr_proteins('').
wkr_transcription_factors('').
wkr_adaptor_proteins('').
wkr_receptors('').
wkr_enzymes('').
wkr_janus_kinases(X):-wkr_janus_kinase_3(X).
wkr_protein_tyrosine_kinases(X):-wkr_janus_kinases(X).
wkr_protein_kinases(X):-wkr_protein_tyrosine_kinases(X).
wkr_phosphotransferases_alcohol_group_acceptor_(X):-wkr_protein_kinases(X).
wkr_phosphotransferases(X):-wkr_phosphotransferases_alcohol_group_acceptor_(X).
wkr_transferases(X):-wkr_phosphotransferases(X).
wkr_enzymes(X):-wkr_transferases(X).
wkr_enzymes_and_coenzymes(X):-wkr_enzymes(X).
wkr_chemicals_and_drugs_category(X):-wkr_enzymes_and_coenzymes(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_janus_kinases(X).
wkr_peptides(X):-wkr_intracellular_signaling_peptides_and_proteins(X).
wkr_amino_acids_peptides_and_proteins(X):-wkr_peptides(X).
wkr_chemicals_and_drugs_category(X):-wkr_amino_acids_peptides_and_proteins(X).
wkr_proteins(X):-wkr_intracellular_signaling_peptides_and_proteins(X).
wkr_amino_acids_peptides_and_proteins(X):-wkr_proteins(X).
wkr_imides(X):-wkr_2__3_5_bis_trifluoromethylphenyl_hydroxymethyl_2_4_nitrophenylamino_6_phenyl_1_2_4a_7a_tetrahydropyrrolo_3_4_b_pyridine_5_7_dione(X).
wkr_organic_chemicals(X):-wkr_imides(X).
wkr_chemicals_and_drugs_category(X):-wkr_organic_chemicals(X).
wkr_piperidines(X):-wkr_2__3_5_bis_trifluoromethylphenyl_hydroxymethyl_2_4_nitrophenylamino_6_phenyl_1_2_4a_7a_tetrahydropyrrolo_3_4_b_pyridine_5_7_dione(X).
wkr_heterocyclic_compounds_1_ring(X):-wkr_piperidines(X).
wkr_heterocyclic_compounds(X):-wkr_heterocyclic_compounds_1_ring(X).
wkr_chemicals_and_drugs_category(X):-wkr_heterocyclic_compounds(X).
wkr_histocompatibility_antigens_class_i(X):-wkr_mhc_class_i_related_chain_a(X).
wkr_membrane_glycoproteins(X):-wkr_histocompatibility_antigens_class_i(X).
wkr_glycoproteins(X):-wkr_membrane_glycoproteins(X).
wkr_glycoconjugates(X):-wkr_glycoproteins(X).
wkr_carbohydrates(X):-wkr_glycoconjugates(X).
wkr_chemicals_and_drugs_category(X):-wkr_carbohydrates(X).
wkr_proteins(X):-wkr_glycoproteins(X).
wkr_membrane_proteins(X):-wkr_membrane_glycoproteins(X).
wkr_proteins(X):-wkr_membrane_proteins(X).
wkr_histocompatibility_antigens(X):-wkr_histocompatibility_antigens_class_i(X).
wkr_antigens_surface(X):-wkr_histocompatibility_antigens(X).
wkr_antigens(X):-wkr_antigens_surface(X).
wkr_biological_factors(X):-wkr_antigens(X).
wkr_chemicals_and_drugs_category(X):-wkr_biological_factors(X).
wkr_isoantigens(X):-wkr_histocompatibility_antigens(X).
wkr_antigens(X):-wkr_isoantigens(X).
wkr_histocompatibility_antigens_class_i(X):-wkr_micb_antigen(X).
wkr_sox_transcription_factors(X):-wkr_soxb2_transcription_factors(X).
wkr_dna_binding_proteins(X):-wkr_sox_transcription_factors(X).
wkr_proteins(X):-wkr_dna_binding_proteins(X).
wkr_high_mobility_group_proteins(X):-wkr_sox_transcription_factors(X).
wkr_chromosomal_proteins_non_histone(X):-wkr_high_mobility_group_proteins(X).
wkr_nuclear_proteins(X):-wkr_chromosomal_proteins_non_histone(X).
wkr_proteins(X):-wkr_nuclear_proteins(X).
wkr_nucleoproteins(X):-wkr_chromosomal_proteins_non_histone(X).
wkr_proteins(X):-wkr_nucleoproteins(X).
wkr_transcription_factors(X):-wkr_sox_transcription_factors(X).
wkr_proteins(X):-wkr_transcription_factors(X).
wkr_mice_inbred_strains(X):-wkr_mice_129_strain(X).
wkr_animals_inbred_strains(X):-wkr_mice_inbred_strains(X).
wkr_animals_laboratory(X):-wkr_animals_inbred_strains(X).
wkr_animal_population_groups(X):-wkr_animals_laboratory(X).
wkr_animals(X):-wkr_animal_population_groups(X).
wkr_eukaryota(X):-wkr_animals(X).
wkr_organisms_category(X):-wkr_eukaryota(X).
wkr_mice(X):-wkr_mice_inbred_strains(X).
wkr_murinae(X):-wkr_mice(X).
wkr_muridae(X):-wkr_murinae(X).
wkr_rodentia(X):-wkr_muridae(X).
wkr_eutheria(X):-wkr_rodentia(X).
wkr_mammals(X):-wkr_eutheria(X).
wkr_vertebrates(X):-wkr_mammals(X).
wkr_chordata(X):-wkr_vertebrates(X).
wkr_animals(X):-wkr_chordata(X).
wkr_mice_mutant_strains(X):-wkr_mice_129_strain(X).
wkr_mice(X):-wkr_mice_mutant_strains(X).
wkr_mice_knockout(X):-wkr_mice_129_strain(X).
wkr_mice_transgenic(X):-wkr_mice_knockout(X).
wkr_animals_genetically_modified(X):-wkr_mice_transgenic(X).
wkr_animal_population_groups(X):-wkr_animals_genetically_modified(X).
wkr_organisms_genetically_modified(X):-wkr_animals_genetically_modified(X).
wkr_organism_forms(X):-wkr_organisms_genetically_modified(X).
wkr_organisms_category(X):-wkr_organism_forms(X).
wkr_mice(X):-wkr_mice_transgenic(X).
wkr_mice_mutant_strains(X):-wkr_mice_knockout(X).
wkr_dna_binding_proteins(X):-wkr_stpa_protein_e_coli(X).
wkr_molecular_chaperones(X):-wkr_stpa_protein_e_coli(X).
wkr_proteins(X):-wkr_molecular_chaperones(X).
wkr_escherichia_coli_proteins(X):-wkr_stpa_protein_e_coli(X).
wkr_bacterial_proteins(X):-wkr_escherichia_coli_proteins(X).
wkr_proteins(X):-wkr_bacterial_proteins(X).
wkr_cryoglobulins(X):-wkr_macromolecular_insoluble_cold_globulin(X).
wkr_paraproteins(X):-wkr_cryoglobulins(X).
wkr_immunoglobulins(X):-wkr_paraproteins(X).
wkr_immunoproteins(X):-wkr_immunoglobulins(X).
wkr_blood_proteins(X):-wkr_immunoproteins(X).
wkr_proteins(X):-wkr_blood_proteins(X).
wkr_serum_globulins(X):-wkr_immunoglobulins(X).
wkr_blood_proteins(X):-wkr_serum_globulins(X).
wkr_globulins(X):-wkr_serum_globulins(X).
wkr_proteins(X):-wkr_globulins(X).
wkr_t_lymphocytes(X):-wkr_cd8_positive_t_lymphocytes(X).
wkr_lymphocytes(X):-wkr_t_lymphocytes(X).
wkr_leukocytes_mononuclear(X):-wkr_lymphocytes(X).
wkr_leukocytes(X):-wkr_leukocytes_mononuclear(X).
wkr_blood_cells(X):-wkr_leukocytes(X).
wkr_cells(X):-wkr_blood_cells(X).
wkr_anatomy_category(X):-wkr_cells(X).
wkr_blood(X):-wkr_blood_cells(X).
wkr_body_fluids(X):-wkr_blood(X).
wkr_fluids_and_secretions(X):-wkr_body_fluids(X).
wkr_anatomy_category(X):-wkr_fluids_and_secretions(X).
wkr_hemic_and_immune_systems(X):-wkr_blood(X).
wkr_anatomy_category(X):-wkr_hemic_and_immune_systems(X).
wkr_immune_system(X):-wkr_leukocytes(X).
wkr_hemic_and_immune_systems(X):-wkr_immune_system(X).
wkr_phosphoproteins(X):-wkr_znhit2_protein_human(X).
wkr_proteins(X):-wkr_phosphoproteins(X).
wkr_viral_proteins(X):-wkr_orf6_protein_sars_cov_2(X).
wkr_proteins(X):-wkr_viral_proteins(X).
wkr_viral_matrix_proteins(X):-wkr_sars7a_protein_sars_virus(X).
wkr_viral_envelope_proteins(X):-wkr_viral_matrix_proteins(X).
wkr_viral_structural_proteins(X):-wkr_viral_envelope_proteins(X).
wkr_viral_proteins(X):-wkr_viral_structural_proteins(X).
wkr_karyopherins(X):-wkr_importin_4_mouse(X).
wkr_nucleocytoplasmic_transport_proteins(X):-wkr_karyopherins(X).
wkr_membrane_transport_proteins(X):-wkr_nucleocytoplasmic_transport_proteins(X).
wkr_carrier_proteins(X):-wkr_membrane_transport_proteins(X).
wkr_proteins(X):-wkr_carrier_proteins(X).
wkr_membrane_proteins(X):-wkr_membrane_transport_proteins(X).
wkr_nuclear_proteins(X):-wkr_karyopherins(X).
wkr_alpha_karyopherins(X):-wkr_kpna1_protein_mouse(X).
wkr_karyopherins(X):-wkr_alpha_karyopherins(X).
wkr_alpha_karyopherins(X):-wkr_kpna6_protein_mouse(X).
wkr_alpha_karyopherins(X):-wkr_kpna7_protein_mouse(X).
wkr_karyopherins(X):-wkr_importin_9_human(X).
wkr_beta_karyopherins(X):-wkr_ipo11_protein_human(X).
wkr_karyopherins(X):-wkr_beta_karyopherins(X).
wkr_karyopherins(X):-wkr_importin_13_rat(X).
wkr_alpha_karyopherins(X):-wkr_importin_alpha4_mouse(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_nmi_protein_human(X).
wkr_protein_inhibitors_of_activated_stat(X):-wkr_pias2_protein_human(X).
wkr_adaptor_proteins_signal_transducing(X):-wkr_protein_inhibitors_of_activated_stat(X).
wkr_adaptor_proteins(X):-wkr_adaptor_proteins_signal_transducing(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_adaptor_proteins_signal_transducing(X).
wkr_carrier_proteins(X):-wkr_adaptor_proteins_signal_transducing(X).
wkr_poly_adp_ribose_binding_proteins(X):-wkr_pias4_protein_human(X).
wkr_carrier_proteins(X):-wkr_poly_adp_ribose_binding_proteins(X).
wkr_nuclear_proteins(X):-wkr_poly_adp_ribose_binding_proteins(X).
wkr_protein_inhibitors_of_activated_stat(X):-wkr_pias4_protein_human(X).
wkr_oligopeptides(X):-wkr_stat_6_inhibitor_peptide(X).
wkr_peptides(X):-wkr_oligopeptides(X).
wkr_phosphopeptides(X):-wkr_stat_6_inhibitor_peptide(X).
wkr_peptides(X):-wkr_phosphopeptides(X).
wkr_peptidyl_dipeptidase_a(X):-wkr_angiotensin_converting_enzyme_2(X).
wkr_dipeptidyl_peptidases_and_tripeptidyl_peptidases(X):-wkr_peptidyl_dipeptidase_a(X).
wkr_exopeptidases(X):-wkr_dipeptidyl_peptidases_and_tripeptidyl_peptidases(X).
wkr_peptide_hydrolases(X):-wkr_exopeptidases(X).
wkr_hydrolases(X):-wkr_peptide_hydrolases(X).
wkr_enzymes(X):-wkr_hydrolases(X).
wkr_receptors_interleukin_16(X):-wkr_cd4_antigens(X).
wkr_receptors(X):-wkr_receptors_interleukin_16(X).
wkr_receptors_interleukin(X):-wkr_receptors_interleukin_16(X).
wkr_receptors(X):-wkr_receptors_interleukin(X).
wkr_receptors_cytokine(X):-wkr_receptors_interleukin(X).
wkr_receptors(X):-wkr_receptors_cytokine(X).
wkr_receptors_immunologic(X):-wkr_receptors_cytokine(X).
wkr_receptors(X):-wkr_receptors_immunologic(X).
wkr_receptors_cell_surface(X):-wkr_receptors_immunologic(X).
wkr_receptors(X):-wkr_receptors_cell_surface(X).
wkr_membrane_proteins(X):-wkr_receptors_cell_surface(X).
wkr_receptors_hiv(X):-wkr_cd4_antigens(X).
wkr_receptors(X):-wkr_receptors_hiv(X).
wkr_receptors_virus(X):-wkr_receptors_hiv(X).
wkr_receptors(X):-wkr_receptors_virus(X).
wkr_receptors_cell_surface(X):-wkr_receptors_virus(X).
wkr_antigens_differentiation_t_lymphocyte(X):-wkr_cd4_antigens(X).
wkr_antigens_differentiation(X):-wkr_antigens_differentiation_t_lymphocyte(X).
wkr_antigens_surface(X):-wkr_antigens_differentiation(X).
wkr_biomarkers(X):-wkr_antigens_differentiation(X).
wkr_biological_factors(X):-wkr_biomarkers(X).
wkr_src_family_kinases(X):-wkr_lymphocyte_specific_protein_tyrosine_kinase_p56_lck_(X).
wkr_protein_tyrosine_kinases(X):-wkr_src_family_kinases(X).
wkr_proto_oncogene_proteins(X):-wkr_lymphocyte_specific_protein_tyrosine_kinase_p56_lck_(X).
wkr_oncogene_proteins(X):-wkr_proto_oncogene_proteins(X).
wkr_neoplasm_proteins(X):-wkr_oncogene_proteins(X).
wkr_proteins(X):-wkr_neoplasm_proteins(X).
wkr_cd8_antigens(X):-wkr_cd8_antigen_alpha_chain(X).
wkr_antigens_differentiation_t_lymphocyte(X):-wkr_cd8_antigens(X).
wkr_receptors(X):-wkr_receptors_antigen_t_cell_alpha_beta(X).
wkr_receptors_antigen_t_cell(X):-wkr_receptors_antigen_t_cell_alpha_beta(X).
wkr_receptors(X):-wkr_receptors_antigen_t_cell(X).
wkr_receptors_antigen(X):-wkr_receptors_antigen_t_cell(X).
wkr_receptors(X):-wkr_receptors_antigen(X).
wkr_receptors_immunologic(X):-wkr_receptors_antigen(X).
wkr_receptors_ccr5(X):-wkr_ccr5_protein_human(X).
wkr_receptors(X):-wkr_receptors_ccr5(X).
wkr_receptors_ccr(X):-wkr_receptors_ccr5(X).
wkr_receptors(X):-wkr_receptors_ccr(X).
wkr_receptors_chemokine(X):-wkr_receptors_ccr(X).
wkr_receptors(X):-wkr_receptors_chemokine(X).
wkr_receptors_g_protein_coupled(X):-wkr_receptors_chemokine(X).
wkr_receptors(X):-wkr_receptors_g_protein_coupled(X).
wkr_receptors_cell_surface(X):-wkr_receptors_g_protein_coupled(X).
wkr_receptors_cytokine(X):-wkr_receptors_chemokine(X).
wkr_receptors_hiv(X):-wkr_receptors_ccr5(X).
wkr_chemokines_cxc(X):-wkr_chemokine_cxcl12(X).
wkr_chemokines(X):-wkr_chemokines_cxc(X).
wkr_cytokines(X):-wkr_chemokines(X).
wkr_intercellular_signaling_peptides_and_proteins(X):-wkr_cytokines(X).
wkr_ligand(X):-wkr_intercellular_signaling_peptides_and_proteins(X).
wkr_peptides(X):-wkr_intercellular_signaling_peptides_and_proteins(X).
wkr_proteins(X):-wkr_intercellular_signaling_peptides_and_proteins(X).
wkr_biological_factors(X):-wkr_intercellular_signaling_peptides_and_proteins(X).
wkr_chemotactic_factors(X):-wkr_chemokines(X).
wkr_biological_factors(X):-wkr_chemotactic_factors(X).
wkr_inflammation_mediators(X):-wkr_chemokines(X).
wkr_biological_factors(X):-wkr_inflammation_mediators(X).
wkr_cysteine_endopeptidases(X):-wkr_psmb7_protein_zebrafish(X).
wkr_cysteine_proteases(X):-wkr_cysteine_endopeptidases(X).
wkr_peptide_hydrolases(X):-wkr_cysteine_proteases(X).
wkr_endopeptidases(X):-wkr_cysteine_endopeptidases(X).
wkr_peptide_hydrolases(X):-wkr_endopeptidases(X).
wkr_zebrafish_proteins(X):-wkr_psmb7_protein_zebrafish(X).
wkr_fish_proteins(X):-wkr_zebrafish_proteins(X).
wkr_proteins(X):-wkr_fish_proteins(X).
wkr_viral_nonstructural_proteins(X):-wkr_nsp1_protein_sars_cov_2(X).
wkr_viral_proteins(X):-wkr_viral_nonstructural_proteins(X).
wkr_methyltransferases(X):-wkr_nsp13_protein_sars_cov(X).
wkr_one_carbon_group_transferases(X):-wkr_methyltransferases(X).
wkr_transferases(X):-wkr_one_carbon_group_transferases(X).
wkr_viral_nonstructural_proteins(X):-wkr_nsp13_protein_sars_cov(X).
wkr_rna_helicases(X):-wkr_nsp13_protein_sars_cov(X).
wkr_rna_nucleotidyltransferases(X):-wkr_rna_helicases(X).
wkr_nucleotidyltransferases(X):-wkr_rna_nucleotidyltransferases(X).
wkr_phosphotransferases(X):-wkr_nucleotidyltransferases(X).
wkr_genes(X):-wkr_major_histocompatibility_complex(X).
wkr_genome_components(X):-wkr_genes(X).
wkr_genome(X):-wkr_genome_components(X).
wkr_genetic_structures(X):-wkr_genome(X).
wkr_genetic_phenomena(X):-wkr_genetic_structures(X).
wkr_phenomena_and_processes_category(X):-wkr_genetic_phenomena(X).
wkr_genetic_loci(X):-wkr_major_histocompatibility_complex(X).
wkr_genome_components(X):-wkr_genetic_loci(X).
wkr_immunogenetic_phenomena(X):-wkr_major_histocompatibility_complex(X).
wkr_immune_system_phenomena(X):-wkr_immunogenetic_phenomena(X).
wkr_phenomena_and_processes_category(X):-wkr_immune_system_phenomena(X).
wkr_rna_binding_proteins(X):-wkr_prrc2b_protein_human(X).
wkr_carrier_proteins(X):-wkr_rna_binding_proteins(X).
wkr_nucleoproteins(X):-wkr_rna_binding_proteins(X).
wkr_hla_b51_antigen(X):-wkr_hla_b51_49_antigen(X).
wkr_hla_b_antigens(X):-wkr_hla_b51_antigen(X).
wkr_histocompatibility_antigens_class_i(X):-wkr_hla_b_antigens(X).
wkr_hla_antigens(X):-wkr_hla_b_antigens(X).
wkr_histocompatibility_antigens(X):-wkr_hla_antigens(X).
wkr_dna_binding_proteins(X):-wkr_ppp1r10_protein_human(X).
wkr_rna_binding_proteins(X):-wkr_ppp1r10_protein_human(X).
wkr_hla_c_antigens(X):-wkr_hla_c05_17_antigen(X).
wkr_histocompatibility_antigens_class_i(X):-wkr_hla_c_antigens(X).
wkr_hla_antigens(X):-wkr_hla_c_antigens(X).
wkr_homeodomain_proteins(X):-wkr_cdx1_protein_human(X).
wkr_dna_binding_proteins(X):-wkr_homeodomain_proteins(X).
wkr_core_binding_factor_alpha_subunits(X):-wkr_core_binding_factor_alpha_2_subunit(X).
wkr_core_binding_factors(X):-wkr_core_binding_factor_alpha_subunits(X).
wkr_transcription_factors(X):-wkr_core_binding_factors(X).
wkr_upstream_stimulatory_factors(X):-wkr_usf1_protein_mouse(X).
wkr_basic_helix_loop_helix_transcription_factors(X):-wkr_upstream_stimulatory_factors(X).
wkr_dna_binding_proteins(X):-wkr_basic_helix_loop_helix_transcription_factors(X).
wkr_transcription_factors(X):-wkr_basic_helix_loop_helix_transcription_factors(X).
