base([
event('NR1H4',inhibit,'NR1H4'),
event('NR1H4',inhibit,'NR0B2'),
event('NR1H4',regulate,'RXR'),
event('NR1H4',regulate,'NR1H4'),
event('RXR',inhibit,'NR1H4'),
event('NR1H4',regulate,'BAAT'),
event('NR1H4',regulate,'bile acid'),
event('BAAT',regulate,'BAAT'),
event('BAAT',regulate,'RXR'),
event('BAAT',regulate,'NR1H4'),
event('RXR',bind,'RXR'),
event('RXR',regulate,'RXR'),
event('BAAT',associate,'NR1H2'),
event('CYP7A1',associate,'NR1H2'),
event('NR0B2',associate,'NR1H2'),
event('NR1H4',regulate,'CYP7A1'),
event('bile acid',regulate,'BAAT'),
event('bile acid',regulate,'CYP7A1'),
event('BAAT',associate,'bile acid'),
event('NR1H4',associate,'bile acid'),
event('NR0B2',associate,'bile acid'),
event('BAAT',associate,'CYP7A1'),
event('NR1H4',associate,'CYP7A1'),
event('NR0B2',associate,'CYP7A1'),
event('NR1H4',bind,'BAAT'),
event('NR1H4',bind,'bile acid'),
event('NR1H4',bind,'CYP7A1'),
event('NR1H4',bind,'NR1H4'),
event('NR1H4',bind,'NR0B2'),
event('NR1H4',regulate,'NR0B2'),
event('NR0B2',regulate,'NR0B2'),
event('NR0B2',inhibit,'BAAT'),
event('NR5A2',regulate,'CYP7A1'),
event('NR0B2',regulate,'CYP7A1'),
event('NR5A2',inhibit,'CYP7A1'),
event('NR5A2',inhibit,'NR1H4'),
event('NR5A2',inhibit,'NR0B2'),
event('BAAT',regulate,'bile acid'),
event('BAAT',regulate,'CYP7A1'),
event('CYP7A1',regulate,'BAAT'),
event('MDFIC',regulate,'BAAT'),
event('BAAT',regulate,'MDFIC'),
event('NR1H4',regulate,'MDFIC'),
event('BAAT',associate,'NR1H4'),
event('NR1H2',associate,'NR1H4'),
event('MDFIC',associate,'NR1H4'),
event('NR1H2',regulate,'NR1H2'),
event('NR1H2',regulate,'CYP7A1'),
event('NR1H3',regulate,'CYP7A1'),
event('NR1H2',regulate,'MDFIC'),
event('NR1H2',associate,'NR1H2'),
event('NR1H2',inhibit,'RXR'),
event('NR1H2',bind,'NR1H2'),
event('NR1H2',bind,'CYP7A1'),
event('NR1H2',inhibit,'NR1H2'),
event('NR1H2',inhibit,'CYP7A1'),
event('BAAT',inhibit,'NR1H2'),
event('oxysterols',regulate,'NR1H3'),
event('MDFIC',bind,'NR1H3'),
event('NR1H3',inhibit,'MDFIC'),
event('MDFIC',regulate,'NR1H3'),
event('MDFIC',regulate,'NR1H2'),
event('NR1H2',regulate,'NR1H3'),
event('NR1H2',inhibit,'NR1H3'),
event('NR1H3',regulate,'NR1H2'),
event('NR1H3',regulate,'NR1H3'),
event('CHROMR',regulate,'NR1H2'),
event('CHROMR',regulate,'NR1H3'),
event('oxysterols',bind,'NR1H2'),
event('NR1H2',regulate,'RXR'),
event('NR1H3',regulate,'RXR'),
event('NR1H2',bind,'RXR'),
event('NR1H3',bind,'RXR'),
event('RXR',associate,'NR1H2'),
event('RXR',associate,'NR1H3'),
event('oxysterols',regulate,'NR1H2'),
event('NR1H3',bind,'NR1H2'),
event('NR1H2',bind,'NR1H3'),
event('NR1H3',bind,'NR1H3'),
event('NR1H2',bind,'MDFIC'),
event('NR1H3',bind,'MDFIC'),
event('NR1H3',inhibit,'NR1H2'),
event('NR1H3',inhibit,'NR1H3'),
event('MDFIC',bind,'RXR'),
event('NR1H3',regulate,'MDFIC'),
event('CYP7A1',bind,'NR1H2'),
event('CYP7A1',bind,'NR1H3'),
event('MDFIC',bind,'NR1H2'),
event('NR1H3',associate,'NR1H2'),
event('NR1H2',associate,'NR1H3'),
event('NR1H3',associate,'NR1H3'),
event('NR1H2',associate,'oxysterols'),
event('oxysterols',bind,'RXR'),
event('RXR',bind,'NR1H2'),
event('MDFIC',inhibit,'NR1H2'),
event('NR1H2',regulate,'oxysterols'),
event('RXR',regulate,'MDFIC'),
event('oxysterols',inhibit,'NR1H2'),
event('RXR',inhibit,'NR1H2'),
event('RXR',regulate,'NR1H2'),
event('CYP7A1',inhibit,'CYP7A1'),
event('CYP7A1',regulate,'CYP7A1'),
event('NR1H3',inhibit,'CYP7A1'),
event('NR1H2',associate,'MDFIC'),
event('NR1H2',regulate,'bile acid'),
event('CYP7A1',regulate,'bile acid'),
event('CYP7A1',bind,'NR1H4'),
event('NR1H2',bind,'NR0B2'),
event('NR1H2',regulate,'NR1H4'),
event('oxysterols',associate,'NR1H2'),
event('MDFIC',associate,'NR1H2'),
event('MDFIC',inhibit,'CYP7A1'),
event('MDFIC',regulate,'CYP7A1'),
event('RXR',associate,'MDFIC'),
event('NR1H2',associate,'RXR'),
event('bile acid',bind,'NR1H2'),
event('CYP7A1',regulate,'NR1H2'),
event('NR5A2',regulate,'NR5A2'),
event('CYP7A1',bind,'NR5A2'),
event('NR0B2',bind,'NR5A2'),
event('NR1H2',bind,'NR5A2'),
event('NR5A2',bind,'NR5A2'),
event('RXR',bind,'NR5A2'),
event('CYP7A1',regulate,'MDFIC'),
event('NR0B2',regulate,'NR1H2'),
event('NR0B2',regulate,'NR1H3'),
event('NR0B2',regulate,'NR1H4'),
event('NR1H4',regulate,'NR1H2'),
event('NR1H4',regulate,'NR1H3'),
event('NR1H3',regulate,'oxysterols'),
event('oxysterols',bind,'NR1H3'),
event('NR0B2',regulate,'bile acid'),
event('NR1H4',bind,'NR1H2'),
event('NR1H4',bind,'NR1H3'),
event('NR1H2',bind,'bile acid'),
event('CYP7A1',bind,'bile acid'),
event('NR1H3',bind,'bile acid'),
event('CYP7A1',bind,'MDFIC'),
event('NR1H4',bind,'MDFIC'),
event('NR1H2',regulate,'BAAT'),
event('NR1H2',bind,'NR1H4'),
event('RXR',bind,'NR1H4'),
event('NR1H2',inhibit,'NR1H4'),
event('MDFIC',bind,'NR1H4'),
event('RXR',regulate,'NR1H4'),
event('NR0B2',associate,'NR0B2'),
event('NR1H2',inhibit,'NR0B2'),
event('NR0B2',inhibit,'NR0B2'),
event('NR1H2',regulate,'NR0B2'),
event('RXR',regulate,'NR1H3'),
event('bile acid',inhibit,'CYP7A1'),
event('NR1H4',inhibit,'CYP7A1'),
event('CYP7A1',regulate,'NR1H3'),
event('CYP7A1',regulate,'RXR'),
event('bile acid',bind,'NR1H3'),
event('NR1H2',inhibit,'oxysterols'),
event('NR1H3',inhibit,'oxysterols'),
event('bile acid',bind,'NR5A2'),
event('NR1H3',regulate,'bile acid'),
event('bile acid',bind,'NR1H4'),
event('NR1H4',inhibit,'NR1H2'),
event('BAAT',regulate,'NR1H2'),
event('NR1H2',bind,'oxysterols'),
event('NR1H3',associate,'MDFIC'),
event('NR1H2',inhibit,'bile acid'),
event('NR0B2',regulate,'MDFIC'),
event('NR1H4',inhibit,'MDFIC'),
event('NR0B2',inhibit,'MDFIC'),
event('NR1H2',inhibit,'MDFIC'),
event('MDFIC',regulate,'NR1H4'),
event('MDFIC',inhibit,'NR1H3'),
event('MDFIC',inhibit,'NR1H4'),
event('MDFIC',associate,'RXR'),
event('CYP7A1',regulate,'NR1H4'),
event('CYP7A1',bind,'CYP7A1'),
event('NR1H3',bind,'CYP7A1'),
event('MDFIC',bind,'CYP7A1'),
event('CYP7A1',inhibit,'bile acid'),
event('bile acid',regulate,'NR1H2'),
event('bile acid',regulate,'NR5A2'),
event('bile acid',regulate,'RXR'),
event('bile acid',regulate,'NR0B2'),
event('CYP7A1',regulate,'NR5A2'),
event('CYP7A1',regulate,'NR0B2'),
event('RXR',regulate,'CYP7A1'),
event('RXR',regulate,'NR5A2'),
event('RXR',regulate,'NR0B2'),
event('NR1H4',regulate,'NR5A2'),
event('bile acid',inhibit,'NR1H2'),
event('bile acid',inhibit,'NR5A2'),
event('bile acid',inhibit,'RXR'),
event('CYP7A1',inhibit,'NR1H2'),
event('CYP7A1',inhibit,'NR5A2'),
event('CYP7A1',inhibit,'RXR'),
event('RXR',inhibit,'CYP7A1'),
event('RXR',inhibit,'NR5A2'),
event('RXR',inhibit,'RXR'),
event('NR1H4',inhibit,'NR5A2'),
event('NR1H4',inhibit,'RXR'),
event('NR0B2',inhibit,'NR1H2'),
event('NR0B2',inhibit,'CYP7A1'),
event('NR0B2',inhibit,'NR5A2'),
event('NR0B2',inhibit,'RXR'),
event('MDFIC',inhibit,'NR5A2'),
event('MDFIC',inhibit,'RXR'),
event('CYP7A1',inhibit,'NR1H3'),
event('CYP7A1',associate,'CYP7A1'),
event('CYP7A1',associate,'NR1H3'),
event('NR1H3',inhibit,'NR1H4'),
event('NR1H3',regulate,'NR1H4'),
event('NR1H3',bind,'NR1H4'),
event('BAAT',regulate,'NR1H3'),
event('NR1H3',inhibit,'bile acid'),
event('NR0B2',inhibit,'bile acid'),
event('NR1H3',bind,'NR0B2'),
event('NR1H3',regulate,'NR0B2'),
event('NR1H3',inhibit,'RXR'),
event('oxysterols',regulate,'CYP7A1'),
event('CYP7A1',bind,'NR0B2'),
event('MDFIC',regulate,'NR0B2'),
event('NR5A2',regulate,'NR0B2'),
event('NR0B2',regulate,'NR5A2'),
event('CYP7A1',associate,'MDFIC'),
event('NR1H2',inhibit,'BAAT'),
event('BAAT',inhibit,'BAAT'),
event('BAAT',bind,'CHROMR'),
event('NR1H2',bind,'BAAT'),
event('BAAT',bind,'NR1H2'),
event('BAAT',associate,'BAAT'),
event('BAAT',bind,'BAAT'),
event('MDFIC',bind,'BAAT'),
event('CH25H',bind,'NR1H2'),
event('NR1H4',bind,'RXR'),
event('CYP7A1',bind,'RXR'),
event('oxysterols',bind,'CYP7A1'),
event('RXR',bind,'CYP7A1'),
event('bile acid',regulate,'NR1H4'),
event('CYP7A1',inhibit,'NR1H4'),
event('CYP7A1',inhibit,'MDFIC'),
event('CYP7A1',regulate,'oxysterols'),
event('bile acid',associate,'CYP7A1'),
event('oxysterols',associate,'CYP7A1'),
event('CYP7A1',inhibit,'oxysterols'),
event('oxysterols',inhibit,'NR1H3'),
event('CH25H',regulate,'CH25H'),
event('MDFIC',regulate,'CH25H'),
event('FOXA2',bind,'FOXA2'),
event('NR1H2',inhibit,'FOXA2'),
event('FOXA2',regulate,'FOXA2'),
event('oxysterols',regulate,'oxysterols'),
event('oxysterols',bind,'oxysterols'),
event('oxysterols',regulate,'CH25H'),
event('NR1H4',associate,'RXR'),
event('NR1H4',associate,'NR1H4'),
event('NR1H2',associate,'CYP7A1'),
event('BAAT',regulate,'SRY'),
event('SRY',regulate,'BAAT'),
event('NR0B2',inhibit,'NR1H4'),
event('NR0B2',associate,'NR1H4'),
event('NR1H4',associate,'NR0B2'),
event('NR1H4',associate,'MDFIC'),
event('NR0B2',associate,'MDFIC'),
event('MDFIC',inhibit,'NR0B2'),
event('NR5A2',bind,'NR0B2'),
event('CYP7A1',inhibit,'NR0B2'),
event('NR0B2',bind,'NR0B2'),
event('NR0B2',associate,'NR5A2'),
event('NR5A2',inhibit,'NR5A2'),
event('NR0B2',bind,'NR1H4'),
event('CYP7A1',associate,'NR1H4'),
event('CYP7A1',associate,'NR0B2'),
event('bile acid',inhibit,'NR0B2'),
event('NR1H2',inhibit,'NR5A2'),
event('NR5A2',regulate,'bile acid'),
event('NR5A2',bind,'NR1H2'),
event('NR5A2',bind,'NR1H3'),
event('NR1H2',regulate,'NR5A2'),
event('NR1H2',associate,'NR0B2'),
event('NR5A2',associate,'NR0B2'),
event('NR1H3',associate,'NR0B2'),
event('NR5A2',bind,'CYP7A1'),
event('NR0B2',bind,'CYP7A1'),
event('NR0B2',bind,'NR1H2'),
event('NR0B2',bind,'NR1H3'),
event('NR5A2',associate,'NR1H2'),
event('NR5A2',regulate,'NR1H2'),
event('NR5A2',regulate,'NR1H3'),
event('NR5A2',regulate,'NR1H4'),
event('NR5A2',regulate,'MDFIC'),
event('NR5A2',associate,'CYP7A1'),
event('NR1H3',associate,'CYP7A1'),
event('NR5A2',associate,'NR1H3'),
event('NR5A2',associate,'NR1H4'),
event('NR1H3',associate,'NR1H4'),
event('NR5A2',associate,'MDFIC'),
event('MDFIC',associate,'NR0B2'),
event('bile acid',associate,'NR0B2'),
event('CYP7A1',associate,'bile acid'),
event('NR1H4',inhibit,'bile acid'),
event('bile acid',inhibit,'NR1H4'),
event('NR5A2',inhibit,'NR1H2'),
event('bile acid',associate,'NR5A2'),
event('NR1H2',associate,'NR5A2'),
event('NR5A2',associate,'NR5A2'),
event('bile acid',bind,'NR0B2'),
event('MDFIC',associate,'NR5A2'),
event('MDFIC',bind,'NR0B2'),
event('NR0B2',bind,'bile acid'),
event('bile acid',bind,'CYP7A1'),
event('NR1H4',bind,'NR5A2'),
event('MDFIC',regulate,'NR5A2'),
event('CYP7A1',associate,'NR5A2'),
event('NR0B2',regulate,'BAAT'),
event('MDFIC',bind,'NR5A2'),
event('NR1H4',regulate,'FOXA2'),
event('FOXA2',bind,'NR1H4'),
event('FOXA2',regulate,'NR1H4'),
event('NR5A2',associate,'SRY'),
event('SRY',associate,'CHROMR'),
event('CHROMR',inhibit,'NR1H4'),
event('NR1H4',associate,'NR5A2'),
event('bile acid',associate,'NR1H4'),
event('CHROMR',regulate,'NR1H4'),
event('NR1H4',inhibit,'CHROMR'),
event('SRY',associate,'MDFIC'),
event('SRY',regulate,'SRY'),
event('SRY',inhibit,'SRY'),
event('SRY',associate,'SRY'),
event('SRY',inhibit,'NR1H2'),
event('SRY',regulate,'MDFIC'),
event('SRY',bind,'MDFIC'),
event('CHROMR',associate,'CHROMR'),
event('CHROMR',associate,'MDFIC'),
event('MDFIC',associate,'CYP7A1'),
event('RXR',regulate,'bile acid'),
event('CYP7A1',associate,'BAAT'),
event('RUNX1',regulate,'RXR'),
event('RUNX1',associate,'RUNX1'),
event('RUNX1',regulate,'NR0B2'),
event('BAAT',regulate,'NR5A2'),
event('NR5A2',bind,'MDFIC'),
event('NRBF2',regulate,'RXR'),
event('NR1H2',regulate,'FOXA2'),
event('NR0B2',bind,'RXR'),
event('RXR',bind,'NR0B2'),
event('NR0B2',regulate,'RXR'),
event('RXR',associate,'NR1H4'),
event('BAAT',inhibit,'RXR'),
event('RXR',associate,'RXR'),
event('bile acid',bind,'RXR'),
event('NR5A2',inhibit,'bile acid'),
event('NR1H4',associate,'NR1H2'),
event('RUNX1',regulate,'NR1H4'),
event('CDX1',associate,'bile acid'),
event('MDFIC',associate,'NR1H3'),
event('NR1H4',inhibit,'BAAT'),
event('CDX1',regulate,'CDX1'),
event('CDX1',associate,'CDX1'),
event('NR0B2',regulate,'CDX1'),
event('bile acid',regulate,'CDX1'),
event('MDFIC',regulate,'RXR'),
event('NR5A2',bind,'RXR'),
event('NR5A2',bind,'NR1H4'),
event('FOXA2',bind,'NR5A2'),
event('NR5A2',regulate,'BAAT'),
event('NR5A2',associate,'BAAT'),
event('NR5A2',inhibit,'MDFIC'),
event('NR1H3',inhibit,'BAAT'),
event('NR1H3',bind,'BAAT'),
event('RXR',bind,'MDFIC'),
event('RXR',bind,'BAAT'),
event('NR1H3',associate,'RXR'),
event('RXR',inhibit,'NR1H3'),
event('NR0B2',inhibit,'NR1H3'),
event('BAAT',associate,'MDFIC'),
event('FOXA2',associate,'MDFIC'),
event('NR0B2',regulate,'FOXA2'),
event('FOXA2',inhibit,'FOXA2'),
event('NR5A2',regulate,'FOXA2'),
event('FOXA2',regulate,'NR5A2'),
event('NR5A2',bind,'FOXA2'),
event('FOXA2',regulate,'NR1H2')
]).
