wkr_ligand('').
wkr_proteins('').
wkr_transcription_factors('').
wkr_adaptor_proteins('').
wkr_receptors('').
wkr_enzymes('').
wkr_acyltransferases(X):-wkr_bile_acid_coa_amino_acid_n_acyltransferase(X).
wkr_transferases(X):-wkr_acyltransferases(X).
wkr_enzymes(X):-wkr_transferases(X).
wkr_enzymes_and_coenzymes(X):-wkr_enzymes(X).
wkr_chemicals_and_drugs_category(X):-wkr_enzymes_and_coenzymes(X).
wkr_core_binding_factor_alpha_subunits(X):-wkr_core_binding_factor_alpha_2_subunit(X).
wkr_core_binding_factors(X):-wkr_core_binding_factor_alpha_subunits(X).
wkr_transcription_factors(X):-wkr_core_binding_factors(X).
wkr_proteins(X):-wkr_transcription_factors(X).
wkr_amino_acids_peptides_and_proteins(X):-wkr_proteins(X).
wkr_chemicals_and_drugs_category(X):-wkr_amino_acids_peptides_and_proteins(X).
wkr_steroid_hydroxylases(X):-wkr_cholesterol_25_hydroxylase(X).
wkr_cytochrome_p_450_enzyme_system(X):-wkr_steroid_hydroxylases(X).
wkr_cytochromes(X):-wkr_cytochrome_p_450_enzyme_system(X).
wkr_enzymes_and_coenzymes(X):-wkr_cytochromes(X).
wkr_hemeproteins(X):-wkr_cytochromes(X).
wkr_proteins(X):-wkr_hemeproteins(X).
wkr_mixed_function_oxygenases(X):-wkr_cytochrome_p_450_enzyme_system(X).
wkr_oxygenases(X):-wkr_mixed_function_oxygenases(X).
wkr_oxidoreductases(X):-wkr_oxygenases(X).
wkr_enzymes(X):-wkr_oxidoreductases(X).
wkr_hypoalphalipoproteinemias(X):-wkr_lecithin_cholesterol_acyltransferase_deficiency(X).
wkr_hypolipoproteinemias(X):-wkr_hypoalphalipoproteinemias(X).
wkr_lipid_metabolism_inborn_errors(X):-wkr_hypolipoproteinemias(X).
wkr_metabolism_inborn_errors(X):-wkr_lipid_metabolism_inborn_errors(X).
wkr_genetic_diseases_inborn(X):-wkr_metabolism_inborn_errors(X).
wkr_congenital_hereditary_and_neonatal_diseases_and_abnormalities(X):-wkr_genetic_diseases_inborn(X).
wkr_diseases_category(X):-wkr_congenital_hereditary_and_neonatal_diseases_and_abnormalities(X).
wkr_metabolic_diseases(X):-wkr_metabolism_inborn_errors(X).
wkr_nutritional_and_metabolic_diseases(X):-wkr_metabolic_diseases(X).
wkr_diseases_category(X):-wkr_nutritional_and_metabolic_diseases(X).
wkr_lipid_metabolism_disorders(X):-wkr_lipid_metabolism_inborn_errors(X).
wkr_metabolic_diseases(X):-wkr_lipid_metabolism_disorders(X).
wkr_dyslipidemias(X):-wkr_hypolipoproteinemias(X).
wkr_lipid_metabolism_disorders(X):-wkr_dyslipidemias(X).
wkr_sterol_esterase(X):-wkr_nceh1_protein_human(X).
wkr_carboxylic_ester_hydrolases(X):-wkr_sterol_esterase(X).
wkr_esterases(X):-wkr_carboxylic_ester_hydrolases(X).
wkr_hydrolases(X):-wkr_esterases(X).
wkr_enzymes(X):-wkr_hydrolases(X).
wkr_niemann_pick_diseases(X):-wkr_niemann_pick_disease_type_c(X).
wkr_sphingolipidoses(X):-wkr_niemann_pick_diseases(X).
wkr_lysosomal_storage_diseases_nervous_system(X):-wkr_sphingolipidoses(X).
wkr_brain_diseases_metabolic_inborn(X):-wkr_lysosomal_storage_diseases_nervous_system(X).
wkr_brain_diseases_metabolic(X):-wkr_brain_diseases_metabolic_inborn(X).
wkr_brain_diseases(X):-wkr_brain_diseases_metabolic(X).
wkr_central_nervous_system_diseases(X):-wkr_brain_diseases(X).
wkr_nervous_system_diseases(X):-wkr_central_nervous_system_diseases(X).
wkr_diseases_category(X):-wkr_nervous_system_diseases(X).
wkr_metabolic_diseases(X):-wkr_brain_diseases_metabolic(X).
wkr_metabolism_inborn_errors(X):-wkr_brain_diseases_metabolic_inborn(X).
wkr_lysosomal_storage_diseases(X):-wkr_lysosomal_storage_diseases_nervous_system(X).
wkr_metabolism_inborn_errors(X):-wkr_lysosomal_storage_diseases(X).
wkr_lipidoses(X):-wkr_sphingolipidoses(X).
wkr_lipid_metabolism_inborn_errors(X):-wkr_lipidoses(X).
wkr_lipid_metabolism_disorders(X):-wkr_lipidoses(X).
wkr_histiocytosis_non_langerhans_cell(X):-wkr_niemann_pick_diseases(X).
wkr_histiocytosis(X):-wkr_histiocytosis_non_langerhans_cell(X).
wkr_lymphatic_diseases(X):-wkr_histiocytosis(X).
wkr_hemic_and_lymphatic_diseases(X):-wkr_lymphatic_diseases(X).
wkr_diseases_category(X):-wkr_hemic_and_lymphatic_diseases(X).
wkr_membrane_transport_proteins(X):-wkr_npc1l1_protein_mouse(X).
wkr_carrier_proteins(X):-wkr_membrane_transport_proteins(X).
wkr_proteins(X):-wkr_carrier_proteins(X).
wkr_membrane_proteins(X):-wkr_membrane_transport_proteins(X).
wkr_proteins(X):-wkr_membrane_proteins(X).
wkr_glycoproteins(X):-wkr_npc2_protein_rat(X).
wkr_glycoconjugates(X):-wkr_glycoproteins(X).
wkr_carbohydrates(X):-wkr_glycoconjugates(X).
wkr_chemicals_and_drugs_category(X):-wkr_carbohydrates(X).
wkr_proteins(X):-wkr_glycoproteins(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_npc2_protein_rat(X).
wkr_peptides(X):-wkr_intracellular_signaling_peptides_and_proteins(X).
wkr_amino_acids_peptides_and_proteins(X):-wkr_peptides(X).
wkr_proteins(X):-wkr_intracellular_signaling_peptides_and_proteins(X).
wkr_cell_membrane_structures(X):-wkr_membrane_microdomains(X).
wkr_cell_membrane(X):-wkr_cell_membrane_structures(X).
wkr_cellular_structures(X):-wkr_cell_membrane(X).
wkr_cells(X):-wkr_cellular_structures(X).
wkr_anatomy_category(X):-wkr_cells(X).
wkr_liver_x_receptors(X):-wkr_nr1h2_protein_rat(X).
wkr_dna_binding_proteins(X):-wkr_liver_x_receptors(X).
wkr_proteins(X):-wkr_dna_binding_proteins(X).
wkr_receptors_cytoplasmic_and_nuclear(X):-wkr_liver_x_receptors(X).
wkr_receptors(X):-wkr_receptors_cytoplasmic_and_nuclear(X).
wkr_proteins(X):-wkr_receptors_cytoplasmic_and_nuclear(X).
wkr_liver_x_receptors(X):-wkr_nr1h3_protein_rat(X).
wkr_cholesterol_7_alpha_hydroxylase(X):-wkr_cyp7a1_protein_human(X).
wkr_cytochrome_p450_family_7(X):-wkr_cholesterol_7_alpha_hydroxylase(X).
wkr_cytochrome_p_450_enzyme_system(X):-wkr_cytochrome_p450_family_7(X).
wkr_steroid_hydroxylases(X):-wkr_cholesterol_7_alpha_hydroxylase(X).
wkr_receptors_cytoplasmic_and_nuclear(X):-wkr_nr5a2_protein_mouse(X).
wkr_gonadotropin_releasing_hormone(X):-wkr_lhrh_n_ac_trp_1__4_cl_phe_2_trp_3_arg_6_ala_10_(X).
wkr_pituitary_hormone_releasing_hormones(X):-wkr_gonadotropin_releasing_hormone(X).
wkr_hypothalamic_hormones(X):-wkr_pituitary_hormone_releasing_hormones(X).
wkr_peptide_hormones(X):-wkr_hypothalamic_hormones(X).
wkr_hormones(X):-wkr_peptide_hormones(X).
wkr_hormones_hormone_substitutes_and_hormone_antagonists(X):-wkr_hormones(X).
wkr_chemicals_and_drugs_category(X):-wkr_hormones_hormone_substitutes_and_hormone_antagonists(X).
wkr_physiological_effects_of_drugs(X):-wkr_hormones_hormone_substitutes_and_hormone_antagonists(X).
wkr_pharmacologic_actions(X):-wkr_physiological_effects_of_drugs(X).
wkr_chemical_actions_and_uses(X):-wkr_pharmacologic_actions(X).
wkr_chemicals_and_drugs_category(X):-wkr_chemical_actions_and_uses(X).
wkr_peptides(X):-wkr_peptide_hormones(X).
wkr_neuropeptides(X):-wkr_hypothalamic_hormones(X).
wkr_peptides(X):-wkr_neuropeptides(X).
wkr_nerve_tissue_proteins(X):-wkr_neuropeptides(X).
wkr_proteins(X):-wkr_nerve_tissue_proteins(X).
wkr_oligopeptides(X):-wkr_gonadotropin_releasing_hormone(X).
wkr_peptides(X):-wkr_oligopeptides(X).
wkr_analogs_and_derivatives(X):-wkr_lhrh_n_ac_trp_1__4_cl_phe_2_trp_3_arg_6_ala_10_(X).
wkr_chemistry(X):-wkr_analogs_and_derivatives(X).
wkr_subheadings_category(X):-wkr_chemistry(X).
wkr_liver_x_receptors(X):-wkr_nr1h3_protein_mouse(X).
wkr_sulfonamides(X):-wkr_t_0314407(X).
wkr_amides(X):-wkr_sulfonamides(X).
wkr_organic_chemicals(X):-wkr_amides(X).
wkr_chemicals_and_drugs_category(X):-wkr_organic_chemicals(X).
wkr_sulfones(X):-wkr_sulfonamides(X).
wkr_sulfur_compounds(X):-wkr_sulfones(X).
wkr_inorganic_chemicals(X):-wkr_sulfur_compounds(X).
wkr_chemicals_and_drugs_category(X):-wkr_inorganic_chemicals(X).
wkr_organic_chemicals(X):-wkr_sulfur_compounds(X).
wkr_transcription_factors(X):-wkr_nrbf2_protein_rat(X).
wkr_receptors_immunologic(X):-wkr_spalpha_protein_mouse(X).
wkr_receptors(X):-wkr_receptors_immunologic(X).
wkr_receptors_cell_surface(X):-wkr_receptors_immunologic(X).
wkr_receptors(X):-wkr_receptors_cell_surface(X).
wkr_membrane_proteins(X):-wkr_receptors_cell_surface(X).
wkr_receptors_cytoplasmic_and_nuclear(X):-wkr_farnesoid_x_activated_receptor(X).
wkr_receptors_cytoplasmic_and_nuclear(X):-wkr_nuclear_receptor_subfamily_0_group_b_member_2(X).
wkr_homeodomain_proteins(X):-wkr_cdx1_protein_human(X).
wkr_dna_binding_proteins(X):-wkr_homeodomain_proteins(X).
wkr_myogenic_regulatory_factors(X):-wkr_mdfi_protein_mouse(X).
wkr_muscle_proteins(X):-wkr_myogenic_regulatory_factors(X).
wkr_contractile_proteins(X):-wkr_muscle_proteins(X).
wkr_proteins(X):-wkr_contractile_proteins(X).
wkr_basic_helix_loop_helix_transcription_factors(X):-wkr_myogenic_regulatory_factors(X).
wkr_dna_binding_proteins(X):-wkr_basic_helix_loop_helix_transcription_factors(X).
wkr_transcription_factors(X):-wkr_basic_helix_loop_helix_transcription_factors(X).
wkr_sox_transcription_factors(X):-wkr_soxb2_transcription_factors(X).
wkr_dna_binding_proteins(X):-wkr_sox_transcription_factors(X).
wkr_high_mobility_group_proteins(X):-wkr_sox_transcription_factors(X).
wkr_chromosomal_proteins_non_histone(X):-wkr_high_mobility_group_proteins(X).
wkr_nuclear_proteins(X):-wkr_chromosomal_proteins_non_histone(X).
wkr_proteins(X):-wkr_nuclear_proteins(X).
wkr_nucleoproteins(X):-wkr_chromosomal_proteins_non_histone(X).
wkr_proteins(X):-wkr_nucleoproteins(X).
wkr_transcription_factors(X):-wkr_sox_transcription_factors(X).
wkr_hepatocyte_nuclear_factors(X):-wkr_hepatocyte_nuclear_factor_3_beta(X).
wkr_dna_binding_proteins(X):-wkr_hepatocyte_nuclear_factors(X).
wkr_nuclear_proteins(X):-wkr_hepatocyte_nuclear_factors(X).
wkr_transcription_factors(X):-wkr_hepatocyte_nuclear_factors(X).
wkr_forkhead_transcription_factors(X):-wkr_hepatocyte_nuclear_factor_3_beta(X).
wkr_winged_helix_transcription_factors(X):-wkr_forkhead_transcription_factors(X).
wkr_dna_binding_proteins(X):-wkr_winged_helix_transcription_factors(X).
wkr_transcription_factors(X):-wkr_winged_helix_transcription_factors(X).
