transcription_factor('STAT5A').
transcription_factor('STAT3').
transcription_factor('Stat6').
transcription_factor('STAT1').
transcription_factor('Stat3').
transcription_factor('STAT3').
transcription_factor('Stat6').
transcription_factor('Stat1').
transcription_factor('STAT5B').
transcription_factor('Stat5a').
transcription_factor('STAT6').
transcription_factor('Stat5b').
transcription_factor('Stat3').
transcription_factor('STAT2').
transcription_factor('Stat92E').
transcription_factor('STAT4').
transcription_factor('Stat2').
transcription_factor('Stat4').
receptor('STAT5A').
receptor('STAT3').
receptor('Stat6').
receptor('STAT1').
receptor('Stat3').
receptor('STAT3').
receptor('Stat6').
receptor('Stat1').
receptor('STAT5B').
receptor('Stat5a').
receptor('STAT6').
receptor('Stat5b').
receptor('Stat3').
receptor('STAT2').
receptor('Stat92E').
receptor('STAT4').
receptor('Stat2').
receptor('Stat4').
ligand('retropepsin').
ligand('cathepsin').
ligand('TMPRRS2').
ligand('dexamethasone').
ligand('GC376').
ligand('Neuropilin-1').
ligand('remdesivir').
ligand('lopinavir').
ligand('Ritonavir').
ligand('chloroquine').
ligand('Interferon').
ligand('Tocilizumab').
ligand('avifavir').
ligand('favipiravir').
ligand('ivermectin').
ligand('clo2').
ligand('chlorine').
ligand('PD098059').
ligand('ammonium').
ligand('leitragin').
ligand('glycoprotein').
protein('ORF6').
ligand('ORF6').
receptor('ORF6').
receptor('CD4').
protein('CD8').
receptor('CD8').
protein('CD4').
protein('MHC').
ligand('MHC').
protein('STAT').
transcription_factor('STAT').
receptor('STAT').
enzyme('PSMB7').
protein('PSMB7').
receptor('CCR5').
protein('CCR5').
receptor('CXCR4').
protein('CXCR4').
protein('SARS-CoV-2').
receptor('ACE2').
protein('ACE2').
protein('SARS-CoV').
protein('JAK3').
enzyme('JAK3').
protein('PIAS').
transcription_factor('RUNX1').
protein('RUNX1').
protein('NMI').
protein('ORF8').
protein('IPO5').
transcription_factor('SRY').
protein('SRY').
protein('IPO4').
protein('PPP1R10').
protein('ZNHIT2').
transcription_factor('USF1').
protein('USF1').
protein('CDX1').
protein('COVID-19').
protein('Ipo7').
ligand('Ipo7').
receptor('Ipo7').
protein('Ipo9').
ligand('Ipo9').
receptor('Ipo9').
protein('Ipo13').
ligand('Ipo13').
receptor('Ipo13').
protein('IPO8').
ligand('IPO8').
receptor('IPO8').
protein('IPO13').
ligand('IPO13').
receptor('IPO13').
protein('IPO9').
ligand('IPO9').
receptor('IPO9').
protein('ipo13').
ligand('ipo13').
receptor('ipo13').
protein('IPO7').
ligand('IPO7').
receptor('IPO7').
protein('IPO7').
ligand('IPO11').
receptor('IPO11').
protein('IPO11').
ligand('IPO5').
receptor('IPO5').
protein('IPO5').
ligand('Ipo11').
receptor('Ipo11').
protein('Ipo11').
