%//[SARS-CoV, RUNX1, GATA2, ERVFRD-1, GATA3, GATA5, GATA1, importin, MAGOH, MAGOHB, PYM1, CASC3, ExoN, SRY, ACE2, SARS-CoV-2, coronavirus, spike, RdRp, remdesivir, NendoU, PLpro, STAT1, Mpro, GATA4, USF1, METTL23, CNEP1R1, CTDNEP1, ERV3-1, transcriptase, GATA6, TRPS1, ZGLP1, GATAD2B, GATAD2A, GATAD1, CDX1]
transcription_factor('RUNX1').
protein('RUNX1').
transcription_factor('GATA2').
protein('GATA2').
transcription_factor('GATA3').
protein('GATA3').
transcription_factor('GATA5').
protein('GATA5').
transcription_factor('GATA1').
protein('GATA1').
protein('MAGOH').
transcription_factor('MAGOHB').
protein('MAGOHB').
transcription_factor('PYM1').
protein('PYM1').
protein('CASC3').
protein('ExoN').
transcription_factor('SRY').
protein('SRY').
protein('NendoU').
enzyme('NendoU').
protein('PLpro').
enzyme('PLpro').
protein('Mpro').
enzyme('Mpro').
transcription_factor('GATA4').
protein('GATA4').
transcription_factor('USF1').
protein('USF1').
transcription_factor('METTL23').
protein('METTL23').
transcription_factor('CNEP1R1').
protein('CNEP1R1').
enzyme('CTDNEP1').
transcription_factor('GATA6').
protein('GATA6').
transcription_factor('ZGLP1').
protein('ZGLP1').
transcription_factor('GATAD2B').
protein('GATAD2B').
transcription_factor('GATAD2A').
protein('GATAD2A').
protein('GATAD1').
protein('CDX1').

%las siguientes lineas son para evitar errores en el proceso no deben ser modificadas
enzyme('').
protein('').
transcription_factor('').
receptor('').
ligand('').
