wkr_ligand('').
wkr_proteins('').
wkr_transcription_factors('').
wkr_adaptor_proteins('').
wkr_receptors('').
wkr_enzymes('').
wkr_sox_transcription_factors(X):-wkr_soxb2_transcription_factors(X).
wkr_dna_binding_proteins(X):-wkr_sox_transcription_factors(X).
wkr_proteins(X):-wkr_dna_binding_proteins(X).
wkr_amino_acids_peptides_and_proteins(X):-wkr_proteins(X).
wkr_chemicals_and_drugs_category(X):-wkr_amino_acids_peptides_and_proteins(X).
wkr_high_mobility_group_proteins(X):-wkr_sox_transcription_factors(X).
wkr_chromosomal_proteins_non_histone(X):-wkr_high_mobility_group_proteins(X).
wkr_nuclear_proteins(X):-wkr_chromosomal_proteins_non_histone(X).
wkr_proteins(X):-wkr_nuclear_proteins(X).
wkr_nucleoproteins(X):-wkr_chromosomal_proteins_non_histone(X).
wkr_proteins(X):-wkr_nucleoproteins(X).
wkr_transcription_factors(X):-wkr_sox_transcription_factors(X).
wkr_proteins(X):-wkr_transcription_factors(X).
wkr_phosphoprotein_phosphatases(X):-wkr_dullard_protein_mouse(X).
wkr_phosphoric_monoester_hydrolases(X):-wkr_phosphoprotein_phosphatases(X).
wkr_esterases(X):-wkr_phosphoric_monoester_hydrolases(X).
wkr_hydrolases(X):-wkr_esterases(X).
wkr_enzymes(X):-wkr_hydrolases(X).
wkr_enzymes_and_coenzymes(X):-wkr_enzymes(X).
wkr_chemicals_and_drugs_category(X):-wkr_enzymes_and_coenzymes(X).
wkr_pharmacological_actions_category(X):-wkr_neurokinin_1_receptor_antagonists(X).
wkr_influenza_a_virus(X):-wkr_influenza_a_virus_h10n8_subtype(X).
wkr_influenzavirus_a(X):-wkr_influenza_a_virus(X).
wkr_orthomyxoviridae(X):-wkr_influenzavirus_a(X).
wkr_rna_viruses(X):-wkr_orthomyxoviridae(X).
wkr_viruses(X):-wkr_rna_viruses(X).
wkr_organisms_category(X):-wkr_viruses(X).
wkr_cerebellar_cortex(X):-wkr_cerebellar_vermis(X).
wkr_cerebellum(X):-wkr_cerebellar_cortex(X).
wkr_metencephalon(X):-wkr_cerebellum(X).
wkr_rhombencephalon(X):-wkr_metencephalon(X).
wkr_brain_stem(X):-wkr_rhombencephalon(X).
wkr_brain(X):-wkr_brain_stem(X).
wkr_central_nervous_system(X):-wkr_brain(X).
wkr_nervous_system(X):-wkr_central_nervous_system(X).
wkr_anatomy_category(X):-wkr_nervous_system(X).
wkr_viral_envelope_proteins(X):-wkr_ervk_6_protein_human_endogenous_retrovirus(X).
wkr_viral_structural_proteins(X):-wkr_viral_envelope_proteins(X).
wkr_viral_proteins(X):-wkr_viral_structural_proteins(X).
wkr_proteins(X):-wkr_viral_proteins(X).
wkr_pharmacological_actions_category(X):-wkr_adrenergic_beta_2_receptor_antagonists(X).
wkr_cornified_envelope_proline_rich_proteins(X):-wkr_lce2d_protein_human(X).
wkr_cytoskeletal_proteins(X):-wkr_cornified_envelope_proline_rich_proteins(X).
wkr_proteins(X):-wkr_cytoskeletal_proteins(X).
wkr_membrane_proteins(X):-wkr_cornified_envelope_proline_rich_proteins(X).
wkr_proteins(X):-wkr_membrane_proteins(X).
wkr_cornified_envelope_proline_rich_proteins(X):-wkr_lce2b_protein_human(X).
wkr_cornified_envelope_proline_rich_proteins(X):-wkr_lce1c_protein_human(X).
wkr_cornified_envelope_proline_rich_proteins(X):-wkr_lce1b_protein_human(X).
wkr_cornified_envelope_proline_rich_proteins(X):-wkr_lce3c_protein_human(X).
wkr_cornified_envelope_proline_rich_proteins(X):-wkr_lce3b_protein_human(X).
wkr_cornified_envelope_proline_rich_proteins(X):-wkr_lce3d_protein_human(X).
wkr_cornified_envelope_proline_rich_proteins(X):-wkr_lce4a_protein_human(X).
wkr_cornified_envelope_proline_rich_proteins(X):-wkr_lce5a_protein_human(X).
wkr_cornified_envelope_proline_rich_proteins(X):-wkr_lelp1_protein_human(X).
wkr_membrane_proteins(X):-wkr_lem2_protein_mouse(X).
wkr_nuclear_proteins(X):-wkr_lem2_protein_mouse(X).
wkr_dna_binding_proteins(X):-wkr_mbp_lor3_arf_protein_human(X).
wkr_recombinant_fusion_proteins(X):-wkr_mbp_lor3_arf_protein_human(X).
wkr_recombinant_proteins(X):-wkr_recombinant_fusion_proteins(X).
wkr_proteins(X):-wkr_recombinant_proteins(X).
wkr_nuclear_proteins(X):-wkr_nemp1_protein_human(X).
wkr_ran_gtp_binding_protein(X):-wkr_nemp1_protein_human(X).
wkr_monomeric_gtp_binding_proteins(X):-wkr_ran_gtp_binding_protein(X).
wkr_gtp_binding_proteins(X):-wkr_monomeric_gtp_binding_proteins(X).
wkr_gtp_phosphohydrolases(X):-wkr_gtp_binding_proteins(X).
wkr_acid_anhydride_hydrolases(X):-wkr_gtp_phosphohydrolases(X).
wkr_hydrolases(X):-wkr_acid_anhydride_hydrolases(X).
wkr_carrier_proteins(X):-wkr_gtp_binding_proteins(X).
wkr_proteins(X):-wkr_carrier_proteins(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_monomeric_gtp_binding_proteins(X).
wkr_peptides(X):-wkr_intracellular_signaling_peptides_and_proteins(X).
wkr_amino_acids_peptides_and_proteins(X):-wkr_peptides(X).
wkr_proteins(X):-wkr_intracellular_signaling_peptides_and_proteins(X).
wkr_nucleocytoplasmic_transport_proteins(X):-wkr_ran_gtp_binding_protein(X).
wkr_membrane_transport_proteins(X):-wkr_nucleocytoplasmic_transport_proteins(X).
wkr_carrier_proteins(X):-wkr_membrane_transport_proteins(X).
wkr_membrane_proteins(X):-wkr_membrane_transport_proteins(X).
wkr_nuclear_proteins(X):-wkr_ran_gtp_binding_protein(X).
wkr_cytoskeletal_proteins(X):-wkr_syne1_protein_human(X).
wkr_nerve_tissue_proteins(X):-wkr_syne1_protein_human(X).
wkr_proteins(X):-wkr_nerve_tissue_proteins(X).
wkr_microfilament_proteins(X):-wkr_syne2_protein_human(X).
wkr_biopolymers(X):-wkr_microfilament_proteins(X).
wkr_polymers(X):-wkr_biopolymers(X).
wkr_macromolecular_substances(X):-wkr_polymers(X).
wkr_chemicals_and_drugs_category(X):-wkr_macromolecular_substances(X).
wkr_biomedical_and_dental_materials(X):-wkr_polymers(X).
wkr_chemicals_and_drugs_category(X):-wkr_biomedical_and_dental_materials(X).
wkr_specialty_uses_of_chemicals(X):-wkr_biomedical_and_dental_materials(X).
wkr_chemical_actions_and_uses(X):-wkr_specialty_uses_of_chemicals(X).
wkr_chemicals_and_drugs_category(X):-wkr_chemical_actions_and_uses(X).
wkr_manufactured_materials(X):-wkr_biomedical_and_dental_materials(X).
wkr_technology_industry_and_agriculture(X):-wkr_manufactured_materials(X).
wkr_technology_and_food_and_beverages_category(X):-wkr_technology_industry_and_agriculture(X).
wkr_cytoskeletal_proteins(X):-wkr_microfilament_proteins(X).
wkr_nerve_tissue_proteins(X):-wkr_syne2_protein_human(X).
wkr_membrane_proteins(X):-wkr_syne3_protein_zebrafish(X).
wkr_zebrafish_proteins(X):-wkr_syne3_protein_zebrafish(X).
wkr_fish_proteins(X):-wkr_zebrafish_proteins(X).
wkr_proteins(X):-wkr_fish_proteins(X).
wkr_gene_products_env(X):-wkr_env_gene_products_human_immunodeficiency_virus(X).
wkr_polyproteins(X):-wkr_gene_products_env(X).
wkr_proteins(X):-wkr_polyproteins(X).
wkr_retroviridae_proteins(X):-wkr_gene_products_env(X).
wkr_viral_proteins(X):-wkr_retroviridae_proteins(X).
wkr_viral_envelope_proteins(X):-wkr_gene_products_env(X).
wkr_human_immunodeficiency_virus_proteins(X):-wkr_env_gene_products_human_immunodeficiency_virus(X).
wkr_retroviridae_proteins(X):-wkr_human_immunodeficiency_virus_proteins(X).
wkr_lysosome_associated_membrane_glycoproteins(X):-wkr_lysosomal_associated_membrane_protein_3(X).
wkr_membrane_glycoproteins(X):-wkr_lysosome_associated_membrane_glycoproteins(X).
wkr_glycoproteins(X):-wkr_membrane_glycoproteins(X).
wkr_glycoconjugates(X):-wkr_glycoproteins(X).
wkr_carbohydrates(X):-wkr_glycoconjugates(X).
wkr_chemicals_and_drugs_category(X):-wkr_carbohydrates(X).
wkr_proteins(X):-wkr_glycoproteins(X).
wkr_membrane_proteins(X):-wkr_membrane_glycoproteins(X).
wkr_membrane_potentials(X):-wkr_action_potentials(X).
wkr_biophysical_phenomena(X):-wkr_membrane_potentials(X).
wkr_physical_phenomena(X):-wkr_biophysical_phenomena(X).
wkr_phenomena_and_processes_category(X):-wkr_physical_phenomena(X).
wkr_cell_physiological_phenomena(X):-wkr_membrane_potentials(X).
wkr_phenomena_and_processes_category(X):-wkr_cell_physiological_phenomena(X).
wkr_electrophysiological_phenomena(X):-wkr_membrane_potentials(X).
wkr_physiological_phenomena(X):-wkr_electrophysiological_phenomena(X).
wkr_phenomena_and_processes_category(X):-wkr_physiological_phenomena(X).
wkr_nervous_system_physiological_phenomena(X):-wkr_membrane_potentials(X).
wkr_musculoskeletal_and_neural_physiological_phenomena(X):-wkr_nervous_system_physiological_phenomena(X).
wkr_phenomena_and_processes_category(X):-wkr_musculoskeletal_and_neural_physiological_phenomena(X).
wkr_cysteine_endopeptidases(X):-wkr_3c_like_proteinase_coronavirus(X).
wkr_cysteine_proteases(X):-wkr_cysteine_endopeptidases(X).
wkr_peptide_hydrolases(X):-wkr_cysteine_proteases(X).
wkr_hydrolases(X):-wkr_peptide_hydrolases(X).
wkr_endopeptidases(X):-wkr_cysteine_endopeptidases(X).
wkr_peptide_hydrolases(X):-wkr_endopeptidases(X).
wkr_viral_nonstructural_proteins(X):-wkr_3c_like_proteinase_coronavirus(X).
wkr_viral_proteins(X):-wkr_viral_nonstructural_proteins(X).
wkr_ribonucleoproteins(X):-wkr_casc3_protein_rat(X).
wkr_rna_binding_proteins(X):-wkr_ribonucleoproteins(X).
wkr_carrier_proteins(X):-wkr_rna_binding_proteins(X).
wkr_nucleoproteins(X):-wkr_rna_binding_proteins(X).
wkr_zebrafish_proteins(X):-wkr_magoh_protein_zebrafish(X).
wkr_endoribonucleases(X):-wkr_nidoviral_uridylate_specific_endoribonuclease(X).
wkr_endonucleases(X):-wkr_endoribonucleases(X).
wkr_esterases(X):-wkr_endonucleases(X).
wkr_ribonucleases(X):-wkr_endoribonucleases(X).
wkr_esterases(X):-wkr_ribonucleases(X).
wkr_viral_nonstructural_proteins(X):-wkr_nidoviral_uridylate_specific_endoribonuclease(X).
wkr_homeodomain_proteins(X):-wkr_cdx1_protein_human(X).
wkr_dna_binding_proteins(X):-wkr_homeodomain_proteins(X).
wkr_zebrafish_proteins(X):-wkr_gata1a_protein_zebrafish(X).
wkr_gata1_transcription_factor(X):-wkr_gata1a_protein_zebrafish(X).
wkr_erythroid_specific_dna_binding_factors(X):-wkr_gata1_transcription_factor(X).
wkr_dna_binding_proteins(X):-wkr_erythroid_specific_dna_binding_factors(X).
wkr_transcription_factors(X):-wkr_erythroid_specific_dna_binding_factors(X).
wkr_gata_transcription_factors(X):-wkr_gata1_transcription_factor(X).
wkr_dna_binding_proteins(X):-wkr_gata_transcription_factors(X).
wkr_transcription_factors(X):-wkr_gata_transcription_factors(X).
wkr_erythroid_specific_dna_binding_factors(X):-wkr_gata2_transcription_factor(X).
wkr_gata_transcription_factors(X):-wkr_gata2_transcription_factor(X).
wkr_gata3_transcription_factor(X):-wkr_gata3_protein_human(X).
wkr_erythroid_specific_dna_binding_factors(X):-wkr_gata3_transcription_factor(X).
wkr_gata_transcription_factors(X):-wkr_gata3_transcription_factor(X).
wkr_gata4_transcription_factor(X):-wkr_gata4_protein_mouse(X).
wkr_gata_transcription_factors(X):-wkr_gata4_transcription_factor(X).
wkr_gata_transcription_factors(X):-wkr_gata5_transcription_factor(X).
wkr_gata6_transcription_factor(X):-wkr_gata6_protein_mouse(X).
wkr_gata_transcription_factors(X):-wkr_gata6_transcription_factor(X).
wkr_eye_proteins(X):-wkr_gatad1_protein_human(X).
wkr_proteins(X):-wkr_eye_proteins(X).
wkr_gata_transcription_factors(X):-wkr_gatad2a_protein_human(X).
wkr_gata_transcription_factors(X):-wkr_gatad2b_protein_human(X).
wkr_fingers(X):-wkr_trichorhinophalangeal_syndrome_type_i(X).
wkr_hand(X):-wkr_fingers(X).
wkr_upper_extremity(X):-wkr_hand(X).
wkr_extremities(X):-wkr_upper_extremity(X).
wkr_body_regions(X):-wkr_extremities(X).
wkr_anatomy_category(X):-wkr_body_regions(X).
wkr_abnormalities(X):-wkr_trichorhinophalangeal_syndrome_type_i(X).
wkr_embryology(X):-wkr_abnormalities(X).
wkr_anatomy_and_histology(X):-wkr_embryology(X).
wkr_subheadings_category(X):-wkr_anatomy_and_histology(X).
wkr_etiology(X):-wkr_embryology(X).
wkr_subheadings_category(X):-wkr_etiology(X).
wkr_hair_diseases(X):-wkr_trichorhinophalangeal_syndrome_type_i(X).
wkr_skin_diseases(X):-wkr_hair_diseases(X).
wkr_skin_and_connective_tissue_diseases(X):-wkr_skin_diseases(X).
wkr_diseases_category(X):-wkr_skin_and_connective_tissue_diseases(X).
wkr_nose(X):-wkr_trichorhinophalangeal_syndrome_type_i(X).
wkr_face(X):-wkr_nose(X).
wkr_head(X):-wkr_face(X).
wkr_body_regions(X):-wkr_head(X).
wkr_respiratory_system(X):-wkr_nose(X).
wkr_anatomy_category(X):-wkr_respiratory_system(X).
wkr_sense_organs(X):-wkr_nose(X).
wkr_anatomy_category(X):-wkr_sense_organs(X).
wkr_langer_giedion_syndrome(X):-wkr_trichorhinophalangeal_syndrome_type_i(X).
wkr_osteochondrodysplasias(X):-wkr_langer_giedion_syndrome(X).
wkr_bone_diseases_developmental(X):-wkr_osteochondrodysplasias(X).
wkr_bone_diseases(X):-wkr_bone_diseases_developmental(X).
wkr_musculoskeletal_diseases(X):-wkr_bone_diseases(X).
wkr_diseases_category(X):-wkr_musculoskeletal_diseases(X).
wkr_genetic_diseases_inborn(X):-wkr_osteochondrodysplasias(X).
wkr_congenital_hereditary_and_neonatal_diseases_and_abnormalities(X):-wkr_genetic_diseases_inborn(X).
wkr_diseases_category(X):-wkr_congenital_hereditary_and_neonatal_diseases_and_abnormalities(X).
wkr_core_binding_factor_alpha_subunits(X):-wkr_core_binding_factor_alpha_2_subunit(X).
wkr_core_binding_factors(X):-wkr_core_binding_factor_alpha_subunits(X).
wkr_transcription_factors(X):-wkr_core_binding_factors(X).
wkr_upstream_stimulatory_factors(X):-wkr_usf1_protein_mouse(X).
wkr_basic_helix_loop_helix_transcription_factors(X):-wkr_upstream_stimulatory_factors(X).
wkr_dna_binding_proteins(X):-wkr_basic_helix_loop_helix_transcription_factors(X).
wkr_transcription_factors(X):-wkr_basic_helix_loop_helix_transcription_factors(X).
