% The identities for the objects present in the knowledge base, as pubtator predicts.

protein('CXCR4').
protein('IPO5').
protein('CCR5').
protein('CD4').
protein('STAT3').
disease('COVID-19').
protein('ACE2').
protein('CD8A').
protein('IFNG').
protein('IPO9').
protein('CD8B').
protein('S').
protein('IFNA1').
protein('HLA-A').
protein('IPO7').
ligand('MICA').
protein('STAT1').
protein('JAK1').
protein('ORF6').
protein('IFNB1').
protein('IFNAR1').
protein('HLA-C').
protein('IPO13').
protein('STAT5B').
protein('IFNGR1').
protein('STAT2').
protein('IFNA8').
protein('JAK3').
protein('STAT6').
protein('ORF8').
protein('STAT5A').
protein('HLA-B').
protein('IFNL1').
protein('MICB').
protein('IFN1@').
