% gene and gene products from PubTator
protein('CXCR4').
protein('IPO5').
protein('CCR5').
protein('CD4').
protein('STAT3').
protein('ACE2').
protein('CXCL10').
protein('IL1B').
protein('TNF').
protein('OAS1').
protein('CD8A').
protein('IFNG').
protein('IL6').
protein('IPO9').
protein('CD8B').
protein('IL10').
protein('LZTFL1').
protein('FGB').
protein('TLR7').
protein('S').
protein('CRP').
protein('FURIN').
protein('BSG').
protein('N').
protein('IFNA1').
protein('SLC6A20').
protein('HLA-A').
protein('IPO7').
protein('IRF3').
protein('STAT1').
protein('JAK1').
protein('ORF6').
protein('E').
protein('IFNB1').
protein('IFNAR1').
protein('HLA-C').
protein('IPO13').
protein('STAT5B').
protein('IFNGR1').
protein('STAT2').
protein('TLR3').
protein('IFNA8').
protein('JAK3').
protein('TYK2').
protein('STAT6').
protein('ORF8').
protein('STAT5A').
protein('HLA-B').
protein('M').
protein('ORF3A').
protein('NRP1').
protein('IFNL1').
protein('MICB').
protein('IFN1@').
