ligando('').
transcription_factors('').
sinonimos('JAK',['JAK']).
sinonimos('JAK3',['JAK3','Janus kinase 3','L-JAK','JAKL','LJAK','JAK3_HUMAN','JAK-3','Tyrosine-protein kinase JAK3','Janus kinase 3','Leukocyte janus kinase']).
tejidos('JAK3',['Blood','Blood','Blood']).
sinonimos('MICA',['MICA','MHC class I polypeptide-related sequence A','PERB11.1','MHC class I polypeptide-related sequence A']).
tejidos('MICA',['Bone','Bone','Bone']).
sinonimos('MICB',['MICB','MHC class I polypeptide-related sequence B','PERB11.2','MHC class I polypeptide-related sequence B']).
tejidos('MICB',['Pancreas','Pancreas']).
sinonimos('MICC',['MICC','MHC class I polypeptide-related sequence C (pseudogene)','MHC class I polypeptide-related sequence C','PERB11.3']).
sinonimos('ORF6',['ORF6']).
sinonimos('ORF8',['ORF8']).
sinonimos('IMPα',['IMPα']).
sinonimos('IMPβ1',['IMPβ1']).
sinonimos('IPO4',['IPO4','importin 4','Imp4','FLJ23338','Importin-4','Importin-4b','Ran-binding protein 4']).
tejidos('IPO4',['Neuroblastoma','Neuroblastoma','Neuroblastoma','Neuroblastoma','Neuroblastoma']).
sinonimos('IPO5',['IPO5','importin 5','KPNB3','RANBP5','karyopherin (importin) beta 3','RAN binding protein 5','IMB3','MGC2068','PSE1','Importin-5','Importin subunit beta-3','Karyopherin beta-3','Ran-binding protein 5']).
tejidos('IPO5',['Bone marrow','Bone marrow','Bone marrow','Bone marrow','Bone marrow','Bone marrow','Bone marrow']).
sinonimos('IPO5P1',['IPO5P1','importin 5 pseudogene 1']).
sinonimos('NMI',['NMI','N-myc and STAT interactor','N-myc (and STAT) interactor','N-myc-interactor','N-myc and STAT interactor']).
tejidos('NMI',['Cervix carcinoma','Cervix carcinoma','Cervix carcinoma','Cervix carcinoma']).
sinonimos('PIAS1',['PIAS1','protein inhibitor of activated STAT 1','DDXBP1','DEAD/H (Asp-Glu-Ala-Asp/His) box binding protein 1','GBP','GU/RH-II','ZMIZ3','E3 SUMO-protein ligase PIAS1','DEAD/H box-binding protein 1','E3 SUMO-protein transferase PIAS1','Gu-binding protein','Protein inhibitor of activated STAT protein 1','RNA helicase II-binding protein']).
tejidos('PIAS1',['B-cell','B-cell','B-cell','B-cell','B-cell','B-cell','B-cell']).
sinonimos('PIAS2',['PIAS2','protein inhibitor of activated STAT 2','PIASX-BETA','miz','PIASX-ALPHA','ZMIZ4','ARIP3','E3 SUMO-protein ligase PIAS2','Androgen receptor-interacting protein 3','DAB2-interacting protein','E3 SUMO-protein transferase PIAS2','Msx-interacting zinc finger protein','PIAS-NY protein','Protein inhibitor of activated STAT x','Protein inhibitor of activated STAT2']).
tejidos('PIAS2',['B-cell','B-cell','B-cell','B-cell']).
sinonimos('PIAS3',['PIAS3','protein inhibitor of activated STAT 3','FLJ14651','ZMIZ5','E3 SUMO-protein ligase PIAS3','E3 SUMO-protein transferase PIAS3','Protein inhibitor of activated STAT protein 3']).
tejidos('PIAS3',['Blood','Blood','Blood']).
sinonimos('PIAS4',['PIAS4','protein inhibitor of activated STAT 4','Piasg','PIASY','FLJ12419','ZMIZ6','E3 SUMO-protein ligase PIAS4','PIASy','Protein inhibitor of activated STAT protein 4','Protein inhibitor of activated STAT protein gamma']).
tejidos('PIAS4',['B-cell','B-cell','B-cell','B-cell']).
sinonimos('STAT',['STAT']).
sinonimos('ACE2',['ACE2','angiotensin converting enzyme 2','angiotensin I converting enzyme (peptidyl-dipeptidase A) 2','angiotensin I converting enzyme 2','ACEH','Angiotensin-converting enzyme 2','Angiotensin-converting enzyme homolog','Angiotensin-converting enzyme-related carboxypeptidase','Metalloprotease MPROT15','Processed angiotensin-converting enzyme 2']).
tejidos('ACE2',['Heart','Heart','Heart','Heart','Heart','Heart','Heart']).
sinonimos('CD4',['CD4','CD4 molecule','CD4 antigen (p55)','T-cell surface glycoprotein CD4','T4','Leu-3','T-cell surface antigen T4/Leu-3']).
tejidos('CD4',['Brain','Brain','Brain','Brain','Brain']).
sinonimos('CD4+',['CD4+']).
sinonimos('CD8A',['CD8A','CD8 subunit alpha','CD8','CD8 antigen, alpha polypeptide (p32)','T-cell surface glycoprotein CD8 alpha chain','CD8a molecule','p32','CD8alpha','T-lymphocyte differentiation antigen T8/Leu-2']).
tejidos('CD8A',['Pericardium']).
sinonimos('CD8B',['CD8B','CD8 subunit beta','CD8B1','CD8 antigen, beta polypeptide 1 (p37)','CD8b molecule','Ly-3','LYT3','P37','CD8beta','T-cell surface glycoprotein CD8 beta chain']).
tejidos('CD8B',['T-cell','T-cell']).
sinonimos('CD8+',['CD8+']).
sinonimos('CCR5',['CCR5','C-C motif chemokine receptor 5','CMKBR5','chemokine (C-C motif) receptor 5','chemokine (C-C motif) receptor 5 (gene/pseudogene)','C-C motif chemokine receptor 5 (gene/pseudogene)','CKR-5','CC-CKR-5','CKR5','CD195','IDDM22','C-C chemokine receptor type 5','CHEMR13','HIV-1 fusion coreceptor']).
tejidos('CCR5',['Macrophage']).
sinonimos('CXCR4',['CXCR4','C-X-C motif chemokine receptor 4','chemokine (C-X-C motif), receptor 4 (fusin)','chemokine (C-X-C motif) receptor 4','LESTR','NPY3R','HM89','NPYY3R','D2S201E','fusin','HSY3RR','NPYR','CD184','C-X-C chemokine receptor type 4','FB22','Fusin','LCR1','Leukocyte-derived seven transmembrane domain receptor','Lipopolysaccharide-associated protein 3','NPYRL','Stromal cell-derived factor 1 receptor']).
tejidos('CXCR4',['Lung','Lung','Lung','Lung','Lung','Lung','Lung','Lung','Lung','Lung']).
sinonimos('PSMB7',['PSMB7','proteasome 20S subunit beta 7','proteasome (prosome, macropain) subunit, beta type, 7','proteasome subunit beta 7','Z','Proteasome subunit beta type-7','Macropain chain Z','Multicatalytic endopeptidase complex chain Z','Proteasome subunit Z']).
tejidos('PSMB7',['Thymus','Thymus','Thymus','Thymus','Thymus','Thymus','Thymus','Thymus']).
sinonimos('SARS-CoV-2',['SARS-CoV-2']).
sinonimos('C17orf49',['C17orf49','chromosome 17 open reading frame 49','MGC49942','BAP18','HEPIS','Chromatin complexes subunit BAP18','BPTF-associated protein of 18 kDa']).
tejidos('C17orf49',['Hippocampus','Hippocampus','Hippocampus']).
sinonimos('SARS-CoV',['SARS-CoV']).
sinonimos('HLA-A',['HLA-A','major histocompatibility complex, class I, A','HLA class I histocompatibility antigen, A alpha chain','Human leukocyte antigen A']).
tejidos('HLA-A',['Blood','Blood','Blood','Blood']).
sinonimos('PRRC2B',['PRRC2B','proline rich coiled-coil 2B','KIAA0515','BAT2L','BAT2L1','KIAA0515','HLA-B associated transcript 2-like','HLA-B associated transcript 2-like 1','proline-rich coiled-coil 2B','MGC10526','LQFBS-1','Protein PRRC2B','HLA-B-associated transcript 2-like 1','Proline-rich coiled-coil protein 2B']).
tejidos('PRRC2B',['Eye','Eye','Eye','Eye','Eye','Eye','Eye']).
sinonimos('HLA-B',['HLA-B']).
sinonimos('PPP1R10',['PPP1R10','protein phosphatase 1 regulatory subunit 10','protein phosphatase 1, regulatory (inhibitor) subunit 10','protein phosphatase 1, regulatory subunit 10','PNUTS','FB19','CAT53','p99','Serine/threonine-protein phosphatase 1 regulatory subunit 10','MHC class I region proline-rich protein CAT53','PP1-binding protein of 114 kDa','Phosphatase 1 nuclear targeting subunit','Protein FB19']).
tejidos('PPP1R10',['Brain','Brain','Brain','Brain','Brain']).
sinonimos('HLA-C',['HLA-C']).
sinonimos('',['']).
wkr_2__3_5_bis_trifluoromethylphenyl_hydroxymethyl_2_4_nitrophenylamino_6_phenyl_1_2_4a_7a_tetrahydropyrrolo_3_4_b_pyridine_5_7_dione('JAK').
wkr_janus_kinase_3('JAK3').
wkr_mhc_class_i_related_chain_a('MICA').
wkr_micb_antigen('MICB').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_mice_129_strain('MICE').
wkr_stpa_protein_e_coli('MICF').
wkr_macromolecular_insoluble_cold_globulin('MICG').
wkr_cd8_positive_t_lymphocytes('MHC').
wkr_orf6_protein_sars_cov_2('ORF6').
wkr_sars7a_protein_sars_virus('ORF8').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_importin_4_mouse('IPO4').
wkr_kpna1_protein_mouse('IPO5').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_kpna6_protein_mouse('IPO7').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_kpna7_protein_mouse('IPO8').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_ipo9_protein_human('IPO9').
wkr_ipo11_protein_human('IPO11').
wkr_importin_13_rat('IPO13').
wkr_importin_alpha4_mouse('importin').
wkr_nmi_protein_human('NMI').
wkr_pias2_protein_human('PIAS1').
wkr_pias2_protein_human('PIAS2').
wkr_pias2_protein_human('PIAS3').
wkr_pias4_protein_human('PIAS4').
wkr_stat_6_inhibitor_peptide('STAT').
wkr_alunacedase_alfa('ACE2').
wkr_cd4_antigens('CD4').
wkr_lymphocyte_specific_protein_tyrosine_kinase_p56_lck_('CD4+').
wkr_cd8_antigen_alpha_chain('CD8A').
wkr_hla_c05_17_antigen('CD8B').
wkr_receptors_antigen_t_cell_alpha_beta('CD8+').
wkr_ccr5_protein_human('CCR5').
wkr_chemokine_cxcl12('CXCR4').
wkr_psmb7_protein_human('PSMB7').
wkr_coh04s1_covid_19_vaccine('SARS-CoV-2').
wkr_c17orf49_protein_human('C17orf49').
wkr_nsp13_protein_sars_cov('SARS-CoV').
wkr_major_histocompatibility_complex('HLA-A').
wkr_prrc2b_protein_mouse('PRRC2B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_ppp1r10_protein_human('PPP1R10').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
wkr_hla_c05_17_antigen('MICC').
wkr_hla_c05_17_antigen('MICD').
wkr_hla_c05_17_antigen('IMPα').
wkr_hla_c05_17_antigen('IMPβ1').
wkr_hla_c05_17_antigen('IPO5P1').
wkr_hla_c05_17_antigen('IPO7P1').
wkr_hla_c05_17_antigen('IPO7P2').
wkr_hla_c05_17_antigen('IPO8P1').
wkr_hla_c05_17_antigen('CD8B').
wkr_hla_b51_49_antigen('HLA-B').
wkr_hla_c05_17_antigen('HLA-C').
wkr_hla_c05_17_antigen('').
