%//[ORF6, STAT, CD8, CD4, MHC, HLA-C, HLA-A, HLA-B, PSMB7, CCR5, CXCR4, SARS-CoV-2, ACE2, SARS-CoV, JAK3, importin, RUNX1, NMI, PIAS, ORF8, IPO5, SRY, IPO4, PPP1R10, ZNHIT2, USF1, CDX1]
ligand('retropepsin').
ligand('cathepsin').
ligand('TMPRRS2').
ligand('dexamethasone').
ligand('GC376').
ligand('Neuropilin-1').
ligand('remdesivir').
ligand('lopinavir').
ligand('Ritonavir').
ligand('chloroquine').
ligand('Interferon').
ligand('Tocilizumab').
ligand('avifavir').
ligand('favipiravir').
ligand('ivermectin').
ligand('clo2').
ligand('chlorine').
ligand('PD098059').
ligand('ammonium').
ligand('leitragin').
ligand('glycoprotein').
protein('ORF6').
ligand('ORF6').
receptor('ORF6').
receptor('CD4').
protein('CD8').
receptor('CD8').
protein('CD4').
protein('MHC').
ligand('MHC').
protein('STAT').
transcription_factor('STAT').
receptor('STAT').
enzyme('PSMB7').
protein('PSMB7').
receptor('CCR5').
protein('CCR5').
receptor('CXCR4').
protein('CXCR4').
protein('SARS-CoV-2').
receptor('ACE2').
protein('ACE2').
protein('SARS-CoV').
protein('JAK3').
enzyme('JAK3').
protein('importin').
ligand('importin').
receptor('importin').
protein('PIAS').
transcription_factor('RUNX1').
protein('RUNX1').
protein('NMI').
protein('ORF8').
protein('IPO5').
transcription_factor('SRY').
protein('SRY').
protein('IPO4').
protein('PPP1R10').
protein('ZNHIT2').
transcription_factor('USF1').
protein('USF1').
protein('CDX1').

%las siguientes lineas son para evitar errores en el proceso no deben ser modificadas
enzyme('').
protein('').
transcription_factor('').
receptor('').
ligand('').
