disease('COVID-19').
transcription_factor('STAT1').
protein('STAT1').
transcription_factor('STAT').
protein('STAT').
transcription_factor('STAT3').
protein('STAT3').
transcription_factor('STAT4').
protein('STAT4').
transcription_factor('STAT6').
protein('STAT6').
protein('STAT5A').
transcription_factor('STAT5A').
protein('STAT5B').
transcription_factor('STAT5B').
transcription_factor('STAT2').
protein('STAT2').
ligand('S').
receptor('CXCR4').
protein('CXCR4').
protein('PIAS1').
receptor('CCR5').
protein('CCR5').
protein('ACE2').
enzyme('ACE2').
receptor('ACE2').
receptor('CD4').
protein('CD4').
ligand('CD4').
protein('IPO9').
protein('CD8B').
protein('PPP1R10').
protein('IPO7').
protein('MICA').
ligand('MICA').
protein('ORF6').
protein('IPO13').
protein('IPO5').
protein('IPO4').
protein('IPO8').
protein('HLA-C').
ligand('HLA-C').
protein('PIAS3').
protein('PIAS2').
protein('PIAS4').
protein('NMI').
protein('ORF8').
protein('JAK3').
ligand('JAK3').
enzyme('JAK3').
protein('HLA-B').
ligand('HLA-B').
protein('MICB').
ligand('MICB').
enzyme('PSMB7').
protein('IPO11').
protein('PRRC2B').
protein('MICD').
ligand('MICD').
protein('INTERFERON').
protein('IFNG').
protein('IFNG1').
protein('IFNG-AS1').
protein('IFNR').
protein('IFNK').
protein('IFNT2').
protein('IFNW1').
protein('IFNE').
protein('IFNT').
protein('IFN2').
protein('IFNA1').
protein('IFNA16').
protein('IFNA17').
protein('IFNA21').
protein('IFNA15').
protein('IFNA14').
protein('IFNA2').
protein('IFNB1').
protein('IFNGR1').
protein('IFNAR1').
protein('IFNAR2').
protein('IFNA8').
protein('IFNA4').
protein('IFNA').
protein('IFNA3').
protein('IFNAA').
protein('IFNAB').
protein('IFNL1').
protein('IFNL2').
protein('IFNL3').
protein('IFNL4').
protein('IFN1@').
protein('IFNA6').
protein('IFN-ALPHA-14').
protein('IFNA21').
protein('IFNLR1').

% genes and genes products from Pubtator selected from genes.pl with the help of gemini deep researcher.

%las siguientes lineas son para evitar errores en el proceso no deben ser modificadas
enzyme('').
protein('').
transcription_factor('').
receptor('').
ligand('').
disease('').

