% Diseases from PubTator

disease('NEOPLASMS').
disease('CARCINOGENESIS').
disease('PANCREATITIS').
disease('INFLAMMATORY BOWEL DISEASES').
disease('CROHN DISEASE').
disease('COLITIS ULCERATIVE').
disease('INFLAMMATION').
disease('ENCEPHALOMYELITIS AUTOIMMUNE EXPERIMENTAL').
disease('MULTIPLE SCLEROSIS').
disease('MYOCLONIC EPILEPSIES PROGRESSIVE').
disease('DIABETES MELLITUS TYPE 1').
disease('AUTOIMMUNE DISEASES').
disease('COLITIS').
disease('WEIGHT LOSS').
disease('DIARRHEA').
disease('OSTEOARTHRITIS').
disease('NECROSIS').
disease('SHOCK HEMORRHAGIC').
disease('HEMORRHAGE').
disease('WOUNDS AND INJURIES').
disease('COVID-19').
disease('CHRONIC DISEASE').
disease('RESPIRATORY SYSTEM ABNORMALITIES').
disease('RESPIRATORY DISTRESS SYNDROME').
disease('RENAL INSUFFICIENCY').
disease('DRUG-RELATED SIDE EFFECTS AND ADVERSE REACTIONS').
disease('CRANIOSYNOSTOSES').
disease('DEATH').
disease('LUNG INJURY').
disease('INFECTIONS').
disease('CYTOKINE RELEASE SYNDROME').
disease('PNEUMONIA').
disease('ARTHRITIS RHEUMATOID').
disease('LUPUS ERYTHEMATOSUS SYSTEMIC').
disease('DERMATITIS ATOPIC').
disease('REPERFUSION INJURY').
disease('ISCHEMIA').
disease('BRAIN ISCHEMIA').
disease('LUNG DISEASES').
disease('ANEMIA').
disease('THROMBOCYTOPENIA').
disease('DRUG HYPERSENSITIVITY SYNDROME').
disease('DOWN SYNDROME').
disease('DRUG HYPERSENSITIVITY').
disease('LIVER FAILURE').
disease('LEUKEMIA MYELOID ACUTE').
disease('HEMATOLOGIC NEOPLASMS').
disease('RESPIRATORY INSUFFICIENCY').
disease('CORONAVIRUS INFECTIONS').
disease('NEUROLOGIC MANIFESTATIONS').
disease('614878').
disease('LIVER CIRRHOSIS BILIARY').
disease('BLOOD COAGULATION DISORDERS').
disease('CHEMICAL AND DRUG INDUCED LIVER INJURY').
disease('INTERFERON GAMMA RECEPTOR 1 DEFICIENCY').
disease('OBESITY').
disease('ORGANIZING PNEUMONIA').
disease('MULTIPLE ORGAN FAILURE').
disease('THROMBOCYTHEMIA ESSENTIAL').
disease('POLYCYTHEMIA VERA').
disease('PRIMARY MYELOFIBROSIS').
disease('LUNG NEOPLASMS').
disease('ADENOCARCINOMA OF LUNG').
disease('JOB SYNDROME').
disease('MUSCULOSKELETAL DISEASES').
disease('CRITICAL ILLNESS').
disease('THROMBOSIS').
disease('CHORIOAMNIONITIS').
disease('PREMATURE BIRTH').
disease('RING CHROMOSOME 20 SYNDROME').
disease('NEURODEGENERATIVE DISEASES').
disease('NEUROINFLAMMATORY DISEASES').
disease('NERVE DEGENERATION').
disease('T CELL IMMUNODEFICIENCY PRIMARY').
disease('MYCOSIS FUNGOIDES').
disease('LYMPHOMA T-CELL CUTANEOUS').
disease('HEPATITIS B').
disease('FETAL DISEASES').
disease('IMMUNOLOGIC DEFICIENCY SYNDROMES').
disease('GROWTH DISORDERS').
disease('EDEMA').
disease('NEOPLASMS GLANDULAR AND EPITHELIAL').
disease('SKIN DISEASES').
disease('IMMUNE SYSTEM DISEASES').
disease('INFARCTION MIDDLE CEREBRAL ARTERY').
disease('BRAIN DISEASES').
disease('CARCINOMA HEPATOCELLULAR').
disease('MULTIPLE MYELOMA').
disease('FANCONI ANEMIA').
disease('COLORECTAL NEOPLASMS').
disease('RECTAL NEOPLASMS').
disease('PRECANCEROUS CONDITIONS').
disease('PARASITIC DISEASES').
disease('VIRUS DISEASES').
disease('CHOLANGIOCARCINOMA').
disease('DUANE RETRACTION SYNDROME').
disease('IGA VASCULITIS').
disease('CARTILAGE DISEASES').
disease('HYPERPLASIA').
disease('BREAST NEOPLASMS').
disease('PSORIASIS').
disease('ARTHRITIS PSORIATIC').
disease('OSTEOPOROSIS').
disease('MULTIPLE TRAUMA').
disease('ASTHMA').
disease('FOOD HYPERSENSITIVITY').
disease('LYMPHOMA NON-HODGKIN').
disease('SEVERE ACUTE RESPIRATORY SYNDROME').
disease('MPOX (MONKEYPOX)').
disease('HEPATITIS C CHRONIC').
disease('HEPATITIS C').
disease('COMMUNICABLE DISEASES').
disease('PANCREATIC NEOPLASMS').
disease('GASTROINTESTINAL NEOPLASMS').
disease('UTERINE CERVICAL NEOPLASMS').
disease('ADRENAL INSUFFICIENCY').
disease('ADDISON DISEASE').
disease('BEHCET SYNDROME').
disease('SYSTEMIC INFLAMMATORY RESPONSE SYNDROME').
disease('UVEITIS').
disease('ORAL ULCER').
disease('HERPES SIMPLEX').
disease('LYMPHOMA FOLLICULAR').
disease('LYMPHOMA').
disease('PEMPHIGOID BULLOUS').
disease('DERMATITIS HERPETIFORMIS').
disease('SPONDYLITIS ANKYLOSING').
disease('PEMPHIGUS').
disease('PERIODONTITIS').
disease('GLIOMA').
disease('STROKE').
disease('OSSIFICATION HETEROTOPIC').
disease('NEOPLASM METASTASIS').
disease('MELANOMA').
disease('UROLOGIC NEOPLASMS').
disease('EXANTHEMA').
disease('PARKINSON DISEASE').
disease('SIGNS AND SYMPTOMS RESPIRATORY').
disease('CARCINOMA NON-SMALL-CELL LUNG').
disease('ARTHRITIS').
disease('ASTROCYTOMA').
disease('FIBROSARCOMA').
disease('FATTY LIVER ALCOHOLIC').
disease('LIVER DISEASES').
disease('RESPIRATORY TRACT INFECTIONS').
disease('NEVUS').
disease('DYSPLASTIC NEVUS SYNDROME').
disease('LYMPHATIC METASTASIS').
disease('MELANOMA CUTANEOUS MALIGNANT').
disease('NEVUS PIGMENTED').
disease('CELL TRANSFORMATION NEOPLASTIC').
disease('PAPILLOMA').
disease('STOMACH NEOPLASMS').
disease('TUMOR VIRUS INFECTIONS').
disease('INFLUENZA HUMAN').
disease('MYOSITIS').
disease('MYOTONIC DYSTROPHY').
disease('POLYMYOSITIS').
disease('DERMATOMYOSITIS').
disease('ENTEROVIRUS INFECTIONS').
disease('PERIODONTAL DISEASES').
disease('HAND FOOT AND MOUTH DISEASE').
disease('MENINGITIS ASEPTIC').
disease('CENTRAL NERVOUS SYSTEM DISEASES').
disease('HEPATITIS B CHRONIC').
disease('LIVER CIRRHOSIS').
disease('MEASLES').
disease('GLIOBLASTOMA').
disease('PRIMARY IMMUNODEFICIENCY DISEASES').
disease('VIREMIA').
disease('CARDIOVASCULAR DISEASES').
disease('ENDOCRINE SYSTEM DISEASES').
disease('HEART DISEASES').
disease('COLITIS-ASSOCIATED NEOPLASMS').
disease('COLONIC NEOPLASMS').
disease('ATHEROSCLEROSIS').
disease('ACUTE CORONARY SYNDROME').
disease('LUPUS NEPHRITIS').
disease('TOOTH EROSION').
disease('MYOCARDITIS').
disease('GLYCOSURIA RENAL').
disease('FIBROSIS').
disease('SUPERINFECTION').
disease('GRAFT VS HOST DISEASE').
disease('DRY EYE SYNDROMES').
disease('VITILIGO').
disease('ROSACEA').
disease('VASCULITIS').
disease('SARCOMA').
disease('RETINAL DYSPLASIA').
disease('ARTHRITIS INFECTIOUS').
disease('CARDIOMYOPATHIES').
disease('MULTIPLE SCLEROSIS RELAPSING-REMITTING').
disease('DEMYELINATING DISEASES').
disease('CEREBRAL INFARCTION').
disease('INFARCTION').
disease('MAMMARY NEOPLASMS ANIMAL').
disease('CYSTIC FIBROSIS').
disease('HYPOXIA').
disease('HYPOXIA BRAIN').
disease('EMBRYO LOSS').
disease('LEUKEMIA LYMPHOCYTIC CHRONIC B-CELL').
disease('FATTY LIVER').
disease('INSULIN RESISTANCE').
disease('NEPHROTIC SYNDROME').
disease('NEPHROSIS').
disease('GLOMERULONEPHRITIS MEMBRANOUS').
disease('TUBERCULOSIS').
disease('ANEMIA APLASTIC').
disease('HIV INFECTIONS').
disease('CYTOMEGALOVIRUS INFECTIONS').
disease('AUTISM SPECTRUM DISORDER').
disease('DEVELOPMENTAL DISABILITIES').
disease('MENTAL DISORDERS').
disease('LEUKEMIA PROLYMPHOCYTIC T-CELL').
disease('DYSKINESIA FAMILIAL WITH FACIAL MYOKYMIA').
disease('LYMPHOMA LARGE B-CELL DIFFUSE').
disease('MOUTH DISEASES').
disease('LEUKOCYTOSIS').
disease('LEUKEMIA').
disease('GENETIC DISEASES INBORN').
disease('AUTOIMMUNE LYMPHOPROLIFERATIVE SYNDROME').
disease('LYMPHOPROLIFERATIVE DISORDERS').
disease('RENAL CELL CARCINOMA 1').
disease('IDIOPATHIC PULMONARY FIBROSIS').
disease('PULMONARY FIBROSIS').
disease('FEVER').
disease('HEMORRHAGIC FEVER WITH RENAL SYNDROME').
disease('SHOCK').
disease('SEVERE DENGUE').
disease('MYCOSES').
disease('SEPSIS').
disease('ENDOTOXEMIA').
disease('CANDIDIASIS').
disease('KIDNEY DISEASES').
disease('MALARIA').
disease('PARASITEMIA').
disease('PROSTATITIS').
disease('MALARIA CEREBRAL').
disease('PULMONARY ARTERIAL HYPERTENSION').
disease('SCLERODERMA SYSTEMIC').
disease('HYPERTENSION PULMONARY').
disease('VASCULAR REMODELING').
disease('RESPIRATORY TRACT DISEASES').
disease('PULMONARY DISEASE CHRONIC OBSTRUCTIVE').
disease('CARCINOMA RENAL CELL').
disease('EPSTEIN-BARR VIRUS INFECTIONS').
disease('SHOCK SEPTIC').
disease('SOFT TISSUE INJURIES').
disease('BACTERIAL INFECTIONS').
disease('EMBOLISM FAT').
disease('KAPOSI VARICELLIFORM ERUPTION').
disease('ALZHEIMER DISEASE').
disease('ECZEMA').
disease('CRYPTOCOCCOSIS').
disease('MENINGITIS CRYPTOCOCCAL').
disease('PRECURSOR CELL LYMPHOBLASTIC LEUKEMIA-LYMPHOMA').
disease('PAIN').
disease('SCHISTOSOMIASIS').
disease('OSTEOSARCOMA').
disease('GIANT CELL ARTERITIS').
disease('VASCULAR SYSTEM INJURIES').
disease('MYOCARDIAL INFARCTION').
disease('PERIPHERAL ARTERIAL DISEASE').
disease('ECTODERMAL DYSPLASIA').
disease('ENCEPHALOMYELITIS VENEZUELAN EQUINE').
disease('CHAGAS DISEASE').
disease('COINFECTION').
disease('TRYPANOSOMIASIS AFRICAN').
disease('TRYPANOSOMIASIS').
disease('LYME DISEASE').
disease('THYMOMA').
disease('ATAXIA TELANGIECTASIA').
disease('PERITONITIS').
disease('POLYRADICULONEUROPATHY CHRONIC INFLAMMATORY DEMYELINATING').
disease('ENCEPHALITIS').
disease('HYPERGLYCEMIA').
disease('LYMPHOPENIA').
disease('OVARIAN NEOPLASMS').
disease('DENGUE').
disease('CAPILLARY LEAK SYNDROME').
disease('PARALYSIS').
disease('CHROMOSOME 16 TRISOMY').
disease('INTELLECTUAL DISABILITY').
disease('PNEUMOCYSTIS INFECTIONS').
disease('BONE MARROW FAILURE DISORDERS').
disease('PNEUMONIA PNEUMOCYSTIS').
disease('FOODBORNE DISEASES').
disease('HEPATITIS VIRAL HUMAN').
disease('LIVER FAILURE ACUTE').
disease('LEUKEMIA MYELOID').
disease('LEUKEMIA MYELOGENOUS CHRONIC BCR-ABL POSITIVE').
disease('LEUKEMIA MYELOID CHRONIC-PHASE').
disease('BLAST CRISIS').
disease('PRURITUS').
disease('DERMATITIS ALLERGIC CONTACT').
disease('DIABETIC FOOT').
disease('DIABETES COMPLICATIONS').
disease('MACROPHAGE ACTIVATION SYNDROME').
disease('RHEUMATIC DISEASES').
disease('STILL\'S DISEASE ADULT-ONSET').
disease('CONNECTIVE TISSUE DISEASES').
disease('PHOTOSENSITIVITY DISORDERS').
disease('ALOPECIA AREATA').
disease('ALOPECIA').
disease('CORNEAL DISEASES').
disease('PRURIGO').
disease('DERMATITIS ATOPIC 1').
disease('ANXIETY').
disease('DEPRESSIVE DISORDER').
disease('FOLLICULITIS').
disease('ATROPHY').
disease('TELANGIECTASIS').
disease('SPONDYLARTHROPATHIES').
disease('ARTHRITIS REACTIVE').
disease('ACQUIRED IMMUNODEFICIENCY SYNDROME').
disease('146850').
disease('CARCINOMA').
disease('SARCOIDOSIS').
disease('GRANULOMA').
disease('DISEASE').
disease('IDIOPATHIC NONCIRRHOTIC PORTAL HYPERTENSION').
disease('GLOMERULONEPHRITIS').
disease('VASCULAR DISEASES').
disease('LIVER DISEASES ALCOHOLIC').
disease('HODGKIN DISEASE').
disease('URINARY BLADDER NEOPLASMS').
disease('LEUKEMIA LARGE GRANULAR LYMPHOCYTIC').
disease('HEMATOLOGIC DISEASES').
disease('NEUTROPENIA').
disease('LYMPHOMA T-CELL').
disease('BONE MARROW DISEASES').
disease('HEREDITARY AUTOINFLAMMATORY DISEASES').
disease('PURPURA THROMBOCYTOPENIC IDIOPATHIC').
disease('LEUKEMIA B-CELL').
disease('GATA2 DEFICIENCY').
disease('LEUKEMIA PROMYELOCYTIC ACUTE').
disease('RED-CELL APLASIA PURE').
disease('AUTOIMMUNE DISEASES OF THE NERVOUS SYSTEM').
disease('HYPERGAMMAGLOBULINEMIA').
disease('CD59 DEFICIENCY').
disease('HYPERSENSITIVITY IMMEDIATE').
disease('STATUS ASTHMATICUS').
disease('SJOGREN\'S SYNDROME').
disease('DIABETES MELLITUS').
disease('PERSISTENT INFECTION').
disease('SMOKE INHALATION INJURY').
disease('SARCOMA SYNOVIAL').
disease('HEAD AND NECK NEOPLASMS').
disease('SQUAMOUS CELL CARCINOMA OF HEAD AND NECK').
disease('NEOPLASMS ADIPOSE TISSUE').
disease('PERSONALITY DISORDERS').
disease('CYSTS').
disease('POLYCYSTIC KIDNEY AUTOSOMAL DOMINANT').
disease('KIDNEY NEOPLASMS').
disease('CARDIOMEGALY').
disease('HYPERTROPHY').
disease('HEART FAILURE').
disease('CARDIOMYOPATHY DILATED').
disease('MALFORMATIONS OF CORTICAL DEVELOPMENT GROUP I').
disease('CEREBRAL HEMORRHAGE').
disease('HEMATOMA').
disease('ENCEPHALITIS HERPES SIMPLEX').
disease('DIABETES MELLITUS TYPE 2').
disease('AA AMYLOIDOSIS').
disease('AMYOTROPHIC LATERAL SCLEROSIS').
disease('LEUKEMIA-LYMPHOMA ADULT T-CELL').
disease('ULCER').
disease('ARTHRITIS EXPERIMENTAL').
disease('HEREDODEGENERATIVE DISORDERS NERVOUS SYSTEM').
disease('PROSTATIC NEOPLASMS').
disease('SCHIZOPHRENIA').
disease('MEMORY DISORDERS').
disease('HEPATITIS CHRONIC').
disease('WILMS TUMOR').
disease('COGNITION DISORDERS').
disease('HUNTINGTON DISEASE').
disease('ABNORMALITIES DRUG-INDUCED').
disease('INFERTILITY').
disease('LEUKOENCEPHALOPATHIES').
disease('FOOT-AND-MOUTH DISEASE').
disease('SPLENOMEGALY').
disease('NEMATODE INFECTIONS').
disease('SIMIAN ACQUIRED IMMUNODEFICIENCY SYNDROME').
disease('AIDS-ASSOCIATED NEPHROPATHY').
disease('PLEURISY').
disease('GLIOSIS').
disease('RETROGRADE DEGENERATION').
disease('NERVOUS SYSTEM DISEASES').
disease('GLUCOSEPHOSPHATE DEHYDROGENASE DEFICIENCY').
disease('HTLV-I INFECTIONS').
disease('BRONCHIOLITIS OBLITERANS SYNDROME').
disease('TYPHOID FEVER').
disease('DIABETIC RETINOPATHY').
disease('SUBSTANCE-RELATED DISORDERS').
disease('DERMATITIS').
disease('X-LINKED COMBINED IMMUNODEFICIENCY DISEASES').
disease('SEVERE COMBINED IMMUNODEFICIENCY').
disease('HERPES ZOSTER').
disease('MYCOBACTERIUM INFECTIONS').
disease('MYCOBACTERIUM INFECTIONS NONTUBERCULOUS').
disease('DELTARETROVIRUS INFECTIONS').
disease('ACUTE-ON-CHRONIC LIVER FAILURE').
disease('ATTENTION DEFICIT AND DISRUPTIVE BEHAVIOR DISORDERS').
disease('ACUTE KIDNEY INJURY').
disease('NEUROCOGNITIVE DISORDERS').
disease('NEURALGIA').
disease('MAST CELL ACTIVATION DISORDERS').
disease('HEREDITARY PANCREATITIS').
disease('BRAIN INJURIES').
disease('BRAIN INFARCTION').
disease('GLUT1 DEFICIENCY SYNDROME').
disease('PRECURSOR T-CELL LYMPHOBLASTIC LEUKEMIA-LYMPHOMA').
disease('CEREBROVASCULAR DISORDERS').
disease('GENITAL NEOPLASMS FEMALE').
disease('ENDOMETRIAL NEOPLASMS').
disease('LICHEN PLANUS').
disease('MYOPATHIES STRUCTURAL CONGENITAL').
disease('PERIPHERAL NERVOUS SYSTEM DISEASES').
disease('HYPERTENSION').
disease('JOINT DISEASES').
disease('AVIAN LEUKOSIS').
disease('CALICIVIRIDAE INFECTIONS').
disease('CANDIDIASIS CHRONIC MUCOCUTANEOUS').
disease('CANDIDIASIS ORAL').
disease('MEDULLOBLASTOMA').
disease('ZIKA VIRUS INFECTION').
disease('GUILLAIN-BARRE SYNDROME').
disease('HIPPOCAMPAL SCLEROSIS').
disease('FOCAL CORTICAL DYSPLASIA').
disease('BRAIN EDEMA').
disease('TRIPLE NEGATIVE BREAST NEOPLASMS').
disease('ENTERITIS').
disease('LIVER NEOPLASMS').
disease('METABOLIC SIDE EFFECTS OF DRUGS AND SUBSTANCES').
disease('AGGRESSIVE PERIODONTITIS').
disease('MENINGOENCEPHALITIS').
disease('MENINGISM').
disease('BRAIN INJURIES TRAUMATIC').
disease('BONE DISEASES').
disease('MYOCARDIAL ISCHEMIA').
disease('RNA VIRUS INFECTIONS').
disease('INTESTINAL DISEASES').
disease('CARCINOMA SQUAMOUS CELL').
disease('LYMPHOCYTOSIS').
disease('X-LINKED SIDEROBLASTIC ANEMIA').
disease('CHRONOBIOLOGY DISORDERS').
disease('NEUTROPHIL IMMUNODEFICIENCY SYNDROME').
disease('CARCINOMA MERKEL CELL').
disease('PAPILLOMAVIRUS INFECTIONS').
disease('CECAL DISEASES').
disease('CANCER PAIN').
disease('LEUKOPLAKIA').
disease('LEUKOPLAKIA ORAL').
disease('DIARRHEA 5 WITH TUFTING ENTEROPATHY CONGENITAL').
disease('NEUROBLASTOMA').
disease('PLACENTA DISEASES').
disease('FETAL DEATH').
disease('MYSOPHOBIA').
disease('MICROCEPHALY').
disease('BRAIN NEOPLASMS').
disease('HEADACHE').
disease('DISEASE RESISTANCE').
disease('TUBERCULOSIS PULMONARY').
disease('ENHANCED S-CONE SYNDROME').
disease('CALCINOSIS CUTIS').
disease('HYPERSENSITIVITY DELAYED').
disease('NEUROMYELITIS OPTICA').
disease('GLUCOSE INTOLERANCE').
disease('PLATELET SIGNAL PROCESSING DEFECT').
disease('HEMORRHAGIC FEVER CRIMEAN').
disease('VESICULAR STOMATITIS').
disease('LEUKOPENIA').
disease('SEVERE FEVER WITH THROMBOCYTOPENIA SYNDROME').
disease('ENCEPHALITIS VIRAL').
disease('SARCOMA KAPOSI').
disease('LYMPHOMA PRIMARY EFFUSION').
disease('MUCOCUTANEOUS LYMPH NODE SYNDROME').
disease('METABOLIC DISEASES').
disease('METABOLIC SYNDROME').
disease('ACUTE LUNG INJURY').
disease('POST-ACUTE COVID-19 SYNDROME').
disease('REINFECTION').
disease('PLASMA CELL GRANULOMA PULMONARY').
disease('MELANOMA EXPERIMENTAL').
disease('RESPIRATION DISORDERS').
disease('CENTRAL NERVOUS SYSTEM VIRAL DISEASES').
disease('METABOLISM INBORN ERRORS').
disease('PRE-ECLAMPSIA').
disease('OVERWEIGHT').
disease('270100').
disease('ABORTION HABITUAL').
disease('MITOCHONDRIAL DISEASES').
disease('DEPRESSIVE DISORDER MAJOR').
disease('CHRONIC PAIN').
disease('SCIATIC NEUROPATHY').
disease('PREECLAMPTIC TOXEMIA').
disease('MALNUTRITION').
disease('ROTAVIRUS INFECTIONS').
disease('SIGNS AND SYMPTOMS DIGESTIVE').
disease('OTOTOXICITY').
disease('OVARIAN DISEASES').
disease('HYPOMAGNESEMIA 5 RENAL WITH OCULAR INVOLVEMENT').
disease('PULMONARY ATELECTASIS').
disease('PITUITARY NEOPLASMS').
disease('ANTHROPOPHOBIA').
disease('EOSINOPHILIA').
disease('DYSBIOSIS').
disease('RESPIRATORY HYPERSENSITIVITY').
disease('PEDIATRIC MULTISYSTEM INFLAMMATORY DISEASE COVID-19 RELATED').
disease('ADULT MULTISYSTEM INFLAMMATORY DISEASE COVID-19 RELATED').
disease('ADENOCARCINOMA').
disease('LEUKEMIA T-CELL').
disease('PROLACTIN DEFICIENCY ISOLATED').
disease('NEUROMUSCULAR DISEASES').
disease('FATIGUE').
disease('MYALGIA').
disease('HEMOCHROMATOSIS').
disease('MUSCULAR DISORDERS ATROPHIC').
disease('CONVERSION DISORDER').
disease('CARCINOMA PANCREATIC DUCTAL').
disease('RHINITIS ALLERGIC').
disease('ANDROGEN-INSENSITIVITY SYNDROME').
disease('AGAMMAGLOBULINEMIA').
disease('SALIVARY GLAND DISEASES').
disease('PROSTATIC NEOPLASMS CASTRATION-RESISTANT').
disease('TUBERCULOSIS MULTIDRUG-RESISTANT').
disease('RADIATION INJURIES').
disease('BIRTH WEIGHT').
disease('DNA VIRUS INFECTIONS').
disease('DIABETIC CARDIOMYOPATHIES').
disease('CORONARY ARTERY DISEASE').
disease('HEART VALVE DISEASES').
disease('VENTRICULAR DYSFUNCTION LEFT').
disease('ALBUMINURIA').
disease('POST-INFECTIOUS DISORDERS').
disease('PROTEINURIA').
disease('AORTIC ANEURYSM ABDOMINAL').
disease('613700').
disease('VISION DISORDERS').
disease('SYSTEMIC VASCULITIS').
disease('KIDNEY FAILURE CHRONIC').
disease('UVEITIS ANTERIOR').
disease('GASTROINTESTINAL DISEASES').
disease('GOUT').
disease('ARTHRITIS JUVENILE').
disease('THYROTROPIN BIOLOGICALLY INACTIVE').
disease('SPINAL DISEASES').
disease('HEARING LOSS').
disease('ABDOMINAL PAIN').
disease('SACROILIITIS').
disease('AXIAL SPONDYLOARTHRITIS').
disease('STEVENS-JOHNSON SYNDROME').
disease('LYMPHADENITIS').
disease('MYOSITIS INCLUSION BODY').
disease('ARTHRITIS SACROILIAC').
disease('VOMITING').
disease('LIGHT FIXATION SEIZURE SYNDROME').
disease('EYE DISEASES').
disease('ERYTHEMA NODOSUM').
disease('INTRACRANIAL ANEURYSM').
disease('BIPOLAR DISORDER').
disease('SMALL CELL LUNG CARCINOMA').
disease('HEREDITARY BREAST AND OVARIAN CANCER SYNDROME').
disease('ACNE VULGARIS').
disease('SPONDYLARTHRITIS').
disease('BALANITIS').
disease('EYE INFECTIONS FUNGAL').
disease('MACULAR EDEMA').
disease('SEIZURES').
disease('IMMUNE RECONSTITUTION INFLAMMATORY SYNDROME').
disease('TUBERCULOSIS MENINGEAL').
disease('LEWY BODY DISEASE').
disease('GRAVES DISEASE').
disease('PLAQUE ATHEROSCLEROTIC').
disease('LUNG DISEASES INTERSTITIAL').
disease('TURNER SYNDROME').
disease('KLINEFELTER SYNDROME').
disease('BRONCHIOLITIS').
disease('COUGH').
disease('RESPIRATORY SOUNDS').
disease('PREGNANCY IN DIABETICS').
disease('THYROIDITIS AUTOIMMUNE').
disease('HYPERTHYROIDISM').
disease('HYPOTHYROIDISM').
disease('EAR DISEASES').
disease('FRACTURES SPONTANEOUS').
disease('LEUKEMIA HAIRY CELL').
disease('PRECURSOR B-CELL LYMPHOBLASTIC LEUKEMIA-LYMPHOMA').
disease('ANGINA STABLE').
disease('DISEASE PROGRESSION').
disease('HEPATITIS E').
disease('NEOPLASMS SQUAMOUS CELL').
disease('NEUTROPHILIA HEREDITARY').
disease('TROPHOBLASTIC NEOPLASMS').
disease('VENTRICULAR REMODELING').
disease('LUPUS ERYTHEMATOSUS CUTANEOUS').
disease('INFLUENZA IN BIRDS').
disease('KERATODERMA PALMOPLANTAR').
disease('MESOTHELIOMA').
disease('DIARRHEA CHRONIC WITH VILLOUS ATROPHY').
disease('COMMON VARIABLE IMMUNODEFICIENCY').
disease('AUTOIMMUNE ENTEROPATHY').
disease('CELIAC DISEASE').
disease('PYRUVATE CARBOXYLASE DEFICIENCY DISEASE').
disease('ALCOHOLISM').
disease('MUSCLE NEOPLASMS').
disease('HEMORRHAGIC FEVER EBOLA').
disease('CHILLS').
disease('THYROID DISEASES').
disease('AORTIC ANEURYSM THORACIC').
disease('PROGRESSIVE TRANSFORMATION OF GERMINAL CENTERS').
disease('CLEFT LIP').
disease('CLEFT PALATE').
disease('OTOFACIOCERVICAL SYNDROME').
disease('WOLF-HIRSCHHORN SYNDROME').
disease('MESOTHELIOMA MALIGNANT').
disease('LYMPHOMA B-CELL MARGINAL ZONE').
disease('LYMPHOMA B-CELL').
disease('CITRULLINEMIA').
disease('SPINAL CORD DISEASES').
disease('LYMPHOHISTIOCYTOSIS HEMOPHAGOCYTIC').
disease('CORONARY DISEASE').
disease('YELLOW FEVER').
disease('LEUKEMIA BIPHENOTYPIC ACUTE').
disease('LIVEDOID VASCULOPATHY').
disease('615934').
disease('ARTHROPATHY PROGRESSIVE PSEUDORHEUMATOID OF CHILDHOOD').
disease('LATE ONSET DISORDERS').
disease('PRIMARY GRAFT DYSFUNCTION').
disease('RENAL INSUFFICIENCY CHRONIC').
disease('HYPERLIPIDEMIAS').
disease('PARAPARESIS TROPICAL SPASTIC').
disease('BASAL GANGLIA DISEASES').
disease('PAIN INSENSITIVITY CONGENITAL').
disease('HYPERALGESIA').
disease('MACULAR DEGENERATION').
disease('NASOPHARYNGEAL CARCINOMA').
disease('CARCINOMA OVARIAN EPITHELIAL').
disease('PEMPHIGUS BENIGN FAMILIAL').
disease('NEOPLASM RESIDUAL').
disease('DYGGVE-MELCHIOR-CLAUSEN SYNDROME').
disease('ESOPHAGEAL NEOPLASMS').
disease('TESTICULAR NEOPLASMS').
disease('LEUKOCYTE ADHESION DEFICIENCY TYPE 1').
disease('SMALLPOX').
disease('MUMPS').
disease('HEPATITIS AUTOIMMUNE').
disease('LEAD POISONING NERVOUS SYSTEM').
disease('HYPERGLYCEMIC HYPEROSMOLAR NONKETOTIC COMA').
disease('MOUTH NEOPLASMS').
disease('CORNEAL ENDOTHELIAL CELL LOSS').
disease('PORCINE REPRODUCTIVE AND RESPIRATORY SYNDROME').
disease('MASTITIS').
disease('DIABETIC ANGIOPATHIES').
disease('STREPTOCOCCAL INFECTIONS').
disease('CALCINOSIS').
disease('BLOOD PLATELET DISORDERS').
disease('BONE RESORPTION').
disease('CENTRAL NERVOUS SYSTEM INFECTIONS').
disease('LEUKEMIA MONOCYTIC ACUTE').
disease('LEISHMANIASIS VISCERAL').
disease('HEMATURIA BENIGN FAMILIAL').
disease('LEISHMANIASIS').
disease('WARTS').
disease('ALOPECIA UNIVERSALIS').
disease('RIFT VALLEY FEVER').
disease('ACUTE DISEASE').
disease('LYMPHOCYTIC CHORIOMENINGITIS').
disease('CHOLANGITIS').
disease('BLUETONGUE').
disease('MAREK DISEASE').
disease('WEIGHT GAIN').
disease('CONGENITAL ABNORMALITIES').
disease('RUBELLA').
disease('RETINAL DISEASES').
disease('SVEINSSON CHORIORETINAL ATROPHY').
disease('GLAUCOMA').
disease('RETINITIS').
disease('BLINDNESS').
disease('TOXOPLASMOSIS').
disease('SKIN MANIFESTATIONS').
disease('NARCOLEPSY').
disease('ENCEPHALOMYELITIS').
disease('MASSIVE HEPATIC NECROSIS').
disease('SARCOIDOSIS PULMONARY').
disease('NEPHRITIS INTERSTITIAL').
disease('PLEURAL EFFUSION MALIGNANT').
disease('CHOROIDAL EFFUSIONS').
disease('PROTOZOAN INFECTIONS').
disease('HEPATOMEGALY').
disease('ENCEPHALITIS JAPANESE').
disease('615607').
disease('COLD HYPERSENSITIVITY').
disease('DYSENTERY').
disease('DEMYELINATING AUTOIMMUNE DISEASES CNS').
disease('ADENOMATOUS POLYPOSIS COLI').
disease('CONGENITAL DISORDER OF GLYCOSYLATION TYPE 1C').
disease('PROLIDASE DEFICIENCY').
disease('HERPES LABIALIS').
disease('IMMUNO-HEMOLYTIC ANEMIA').
disease('WEST NILE FEVER').
disease('DIGITAL ULCERS').
disease('ARTERIAL OCCLUSIVE DISEASES').
disease('IMMUNOGLOBULIN G4-RELATED DISEASE').
disease('NASOPHARYNGITIS').
disease('BRONCHITIS').
disease('DYSTONIC DISORDERS').
disease('STUTTERING').
disease('FLAVIVIRUS INFECTIONS').
disease('AICARDI-GOUTIERES SYNDROME').
disease('NEONATAL HERPES').
disease('RHEUMATIC FEVER').
disease('OPPORTUNISTIC INFECTIONS').
disease('LICHENOID ERUPTIONS').
disease('PITYRIASIS LICHENOIDES').
disease('COMMON COLD').
disease('THYROIDITIS SUBACUTE').
disease('THYROID ADENOMA HYPERFUNCTIONING').
disease('THALASSEMIA').
disease('BETA-THALASSEMIA').
disease('APHASIA BROCA').
disease('DENDRITIC CELL SARCOMA FOLLICULAR').
disease('NAUSEA').
disease('CHICKENPOX').
disease('CONDYLOMATA ACUMINATA').
disease('NON-ALCOHOLIC FATTY LIVER DISEASE').
disease('ESOPHAGEAL SQUAMOUS CELL CARCINOMA').
disease('FETAL GROWTH RETARDATION').
disease('CONFUSION').
disease('ACUTE TUBULOINTERSTITIAL NEPHRITIS').
disease('MUSCLE WEAKNESS').
disease('NEURALGIA POSTHERPETIC').
disease('IMMUNE DYSREGULATION POLYENDOCRINOPATHY ENTEROPATHY X-LINKED SYNDROME').
disease('MANDIBULAR NERVE INJURIES').
disease('ENCEPHALITIS VARICELLA ZOSTER').
disease('HERPESVIRIDAE INFECTIONS').
disease('THYROID CANCER PAPILLARY').
disease('HIDRADENITIS SUPPURATIVA').
disease('OSTEOLYSIS').
disease('TOOTH RESORPTION').
disease('SARCOMA EWING').
disease('BONE NEOPLASMS').
disease('MUCOSITIS').
disease('SIGNS AND SYMPTOMS').
disease('NEUROTOXICITY SYNDROMES').
disease('LEUKEMIA MEGAKARYOBLASTIC ACUTE').
disease('PHILADELPHIA CHROMOSOME').
disease('MENINGIOMA').
disease('SYNOVITIS').
disease('SERTOLI CELL-ONLY SYNDROME').
disease('CLEAR-CELL METASTATIC RENAL CELL CARCINOMA').
disease('NEOPLASM INVASIVENESS').
disease('RESPIRATORY SYNCYTIAL VIRUS INFECTIONS').
disease('HAIR-AN SYNDROME').
disease('GLUCOSE METABOLISM DISORDERS').
disease('LOWN-GANONG-LEVINE SYNDROME').
disease('IRON OVERLOAD').
disease('MYELOPROLIFERATIVE DISORDERS').
disease('TUBERCULOSIS PLEURAL').
disease('PLEURAL EFFUSION').
disease('VARICELLA ZOSTER VIRUS INFECTION').
disease('SPINOCEREBELLAR ATAXIA 17').
disease('ABSCESS').
disease('PNEUMONIA STAPHYLOCOCCAL').
disease('614162').
disease('INVASIVE PNEUMOCOCCAL DISEASE RECURRENT ISOLATED 2').
disease('INVASIVE FUNGAL INFECTIONS').
disease('PSEUDORABIES').
disease('NON-MUSCLE INVASIVE BLADDER NEOPLASMS').
disease('POLYCYTHEMIA').
disease('LYMPHOMA EXTRANODAL NK-T-CELL').
disease('AGNOSIA').
disease('TESTICULAR GERM CELL TUMOR').
disease('HEART ARREST').
disease('SPINAL CORD INJURIES').
disease('MYOCARDIAL STUNNING').
disease('NEGATIVE RHEUMATOID FACTOR POLYARTHRITIS').
disease('ALAGILLE SYNDROME').
disease('CHEMICAL AND DRUG INDUCED LIVER INJURY CHRONIC').
disease('THYROID NEOPLASMS').
disease('ADENOMA').
disease('THYROIDITIS').
disease('NEOINTIMA').
disease('HEMOLYSIS').
disease('OVALOCYTOSIS HEREDITARY HEMOLYTIC WITH DEFECTIVE ERYTHROPOIESIS').
disease('ANEMIA SICKLE CELL').
disease('CEREBRAL PALSY').
disease('HERPES GENITALIS').
disease('SICK SINUS SYNDROME').
disease('EMPHYSEMA').
disease('ABORTION SPONTANEOUS').
disease('ANEURYSM').
disease('AORTIC ANEURYSM FAMILIAL ABDOMINAL 1').
disease('GAIT DISORDERS NEUROLOGIC').
disease('SYNDROME').
disease('AORTIC VALVE STENOSIS').
disease('109730').
disease('PROSOPAGNOSIA').
disease('OSSIFICATION OF POSTERIOR LONGITUDINAL LIGAMENT').
disease('TERTIARY LYMPHOID STRUCTURES').
disease('INVASIVE PULMONARY ASPERGILLOSIS').
disease('IRRITABLE BOWEL SYNDROME').
disease('AIRWAY OBSTRUCTION').
disease('CICATRIX').
disease('CHLAMYDIA INFECTIONS').
disease('LETHARGY').
disease('EPILEPSY').
disease('EYE INFECTIONS').
disease('MOTOR DISORDERS').
disease('NIEMANN-PICK DISEASE TYPE C').
disease('DERMATITIS CONTACT').
disease('NEURITIS AUTOIMMUNE EXPERIMENTAL').
disease('VITAMIN D DEFICIENCY').
disease('GENITAL DISEASES').
disease('PARAMYXOVIRIDAE INFECTIONS').
disease('EOSINOPHILIC ESOPHAGITIS').
disease('BILIARY ATRESIA').
disease('PULMONARY ATRESIA').
disease('CHOLESTASIS').
disease('INTRACRANIAL ARTERIOVENOUS MALFORMATIONS').
disease('VASCULAR MALFORMATIONS').
disease('PIGMENTATION DISORDERS').
disease('HYPOPIGMENTATION').
disease('METAPLASIA').
disease('WELLS SYNDROME').
disease('LEPROSY TUBERCULOID').
disease('RETINAL DEGENERATION').
disease('MYOCARDIAL REPERFUSION INJURY').
disease('ISCHEMIC STROKE').
disease('CONJUNCTIVITIS ALLERGIC').
disease('CARCINOMA EHRLICH TUMOR').
disease('CHRONIC PERIODONTITIS').
disease('ANODONTIA').
disease('UTERINE CERVICAL DYSPLASIA').
disease('OSTEOARTHRITIS KNEE').
disease('RHINITIS').
disease('PREGNANCY COMPLICATIONS').
disease('SALMONELLA INFECTIONS').
disease('ASTHMA-CHRONIC OBSTRUCTIVE PULMONARY DISEASE OVERLAP SYNDROME').
disease('SYNUCLEINOPATHIES').
disease('MUSCULAR DISEASES').
disease('LEPROSY').
disease('ECHINOCOCCOSIS').
disease('ALLERGIC FUNGAL SINUSITIS').
disease('MULTI-CENTRIC CASTLEMAN\'S DISEASE').
disease('DEMENTIA').
disease('CONSTRICTION PATHOLOGIC').
disease('CELL-ASSOCIATED NEUROTOXICITY').
disease('LYMPHOMA MANTLE-CELL').
disease('MULTIPLE SCLEROSIS CHRONIC PROGRESSIVE').
disease('PLATELET DISORDER FAMILIAL WITH ASSOCIATED MYELOID MALIGNANCY').
disease('LEUKEMIA ERYTHROBLASTIC ACUTE').
disease('TASTE DISORDERS').
disease('SCLERODERMA LOCALIZED').
disease('NEUTROPHIL ACTIN DYSFUNCTION').
disease('COMMUNITY-ACQUIRED INFECTIONS').
disease('211750').
disease('WALDENSTROM MACROGLOBULINEMIA').
disease('STOMACH DISEASES').
disease('FUSARIOSIS').
disease('UTERINE CERVICITIS').
disease('HEPATITIS D').
disease('FIBROMATOSIS AGGRESSIVE').
disease('CATARACT').
disease('INTRAOCULAR LYMPHOMA').
disease('LYMPHATIC DISEASES').
disease('NEPHRITIS').
disease('HEPATITIS D CHRONIC').
disease('SCRUB TYPHUS').
disease('BILIARY FISTULA').
disease('RETINOBLASTOMA').
disease('NEURAL TUBE DEFECTS').
disease('LEUKEMIA MYELOMONOCYTIC JUVENILE').
disease('606579').
disease('ENDOMETRIOSIS').
disease('DYSMENORRHEA').
disease('PERICARDITIS').
disease('FETAL MEMBRANES PREMATURE RUPTURE').
disease('CHORIOCARCINOMA').
disease('COLD INJURY').
disease('APLASTIC ANEMIA IDIOPATHIC').
disease('ICHTHYOSIS BULLOSA OF SIEMENS').
disease('PHOSPHOGLYCERATE KINASE 1 DEFICIENCY').
disease('CARCINOMA BASAL CELL').
disease('WINTER SHORTLAND TEMPLE SYNDROME').
disease('CORNEAL INJURIES').
disease('KERATITIS HERPETIC').
disease('DIABETIC NEPHROPATHIES').
disease('CORONARY ANEURYSM').
disease('HEREDITARY ANGIOEDEMA TYPES I AND II').
disease('LEUKEMIA LYMPHOID').
disease('ADENOMA ISLET CELL').
disease('PSYCHOTIC DISORDERS').
disease('COCHLEAR DISEASES').
disease('HEARING DISORDERS').
disease('CHOLANGITIS SCLEROSING').
disease('ACUTE ERYTHROLEUKEMIA').
disease('IGE RESPONSIVENESS ATOPIC').
disease('BRAIN STEM NEOPLASMS').
disease('LICHEN PLANUS ORAL').
disease('COLONIC DISEASES').
disease('LYMPHOMA T-CELL PERIPHERAL').
disease('LEUKOCYTE DISORDERS').
disease('IDIOPATHIC INFLAMMATORY MYOPATHY FAMILIAL').
disease('WALKER-WARBURG SYNDROME').
disease('MUSCULAR ATROPHY').
disease('COCCIDIOIDOMYCOSIS').
disease('SARCOMA MYELOID').
disease('ACROCEPHALOSYNDACTYLIA').
disease('DYSLIPIDEMIAS').
disease('CARDIOTOXICITY').
disease('BIRDSHOT CHORIORETINOPATHY').
disease('UVEAL MELANOMA').
disease('MYELODYSPLASTIC SYNDROMES').
disease('KERATOCONUS').
disease('SPASMS INFANTILE').
disease('IMMUNE DYSFUNCTION WITH T-CELL INACTIVATION DUE TO CALCIUM ENTRY DEFECT 1').
disease('BRONCHIAL HYPERREACTIVITY').
disease('TENDINOPATHY').
disease('RUPTURE').
disease('IMMUNOGLOBULIN A DEFICIENCY 1').
disease('IGA DEFICIENCY').
disease('INTERVERTEBRAL DISC DEGENERATION').
disease('SKIN NEOPLASMS').
disease('HERNIAS DIAPHRAGMATIC CONGENITAL').
disease('LUNG AGENESIS').
disease('BURKITT LYMPHOMA').
disease('ANGINA PECTORIS').
disease('ANGINA UNSTABLE').
disease('HEAT STRESS DISORDERS').
disease('POSTTHROMBOTIC SYNDROME').
disease('PURPURA').
disease('HYPERINSULINISM').
disease('REM SLEEP BEHAVIOR DISORDER').
disease('TN SYNDROME').
disease('HYPEROXIA').
disease('CORNEAL NEOVASCULARIZATION').
disease('MYOTONIC DISORDERS').
disease('CHLAMYDIAL PNEUMONIA').
disease('PDGFRA-ASSOCIATED CHRONIC EOSINOPHILIC LEUKEMIA').
disease('POLYPS').
disease('CAPILLARY MALFORMATION-ARTERIOVENOUS MALFORMATION').
disease('GASTRITIS ATROPHIC').
disease('IMMUNODEFICIENCY SYNDROME VARIABLE').
disease('MYCOBACTERIUM AVIUM-INTRACELLULARE INFECTION').
disease('MASTOCYTOSIS SYSTEMIC').
disease('GALLBLADDER NEOPLASMS').
disease('CHOLELITHIASIS').
disease('NASAL POLYPS').
disease('GRAVES OPHTHALMOPATHY').
disease('CARCINOMA ADENOID CYSTIC').
disease('LEISHMANIASIS CUTANEOUS').
disease('EPENDYMOMA').
disease('AGRANULOCYTOSIS').
disease('NASOPHARYNGEAL NEOPLASMS').
disease('NEUROENDOCRINE TUMORS').
disease('CARCINOMA NEUROENDOCRINE').
disease('GASTRITIS').
disease('HELICOBACTER INFECTIONS').
disease('SHPRINTZEN GOLBERG CRANIOSYNOSTOSIS').
disease('PLAGIOCEPHALY AND X-LINKED MENTAL RETARDATION').
disease('COXSACKIEVIRUS INFECTIONS').
disease('HEREDITARY MYOPATHY WITH EARLY RESPIRATORY FAILURE').
disease('SIMPSON-GOLABI-BEHMEL SYNDROME').
disease('PRIMARY OVARIAN INSUFFICIENCY').
disease('HASHIMOTO DISEASE').
disease('MYASTHENIA GRAVIS').
disease('CHOROIDAL NEOVASCULARIZATION').
disease('WHITE COAT HYPERTENSION').
disease('HUNTINGTON DISEASE-LIKE 3').
disease('COGNITIVE DYSFUNCTION').
disease('ARBOVIRUS INFECTIONS').
disease('EPILEPSY POST-TRAUMATIC').
disease('MIXED CONNECTIVE TISSUE DISEASE').
disease('CORONARY OCCLUSION').
disease('CORTICOSTEROID-BINDING GLOBULIN DEFICIENCY').
disease('CYSTITIS INTERSTITIAL').
disease('CLASSICAL SWINE FEVER').
disease('ADRENOCORTICAL CARCINOMA').
disease('CARCINOMA ENDOMETRIOID').
disease('PULMONARY EMBOLISM').
disease('MENIERE DISEASE').
disease('COLITIS COLLAGENOUS').
disease('PERICARDIAL EFFUSION').
disease('TRICUSPID VALVE INSUFFICIENCY').
disease('LYME NEUROBORRELIOSIS').
disease('INSULIN-LIKE GROWTH FACTOR I RESISTANCE TO').
disease('HAMARTOMA').
disease('OSTEITIS').
disease('SUBACUTE SCLEROSING PANENCEPHALITIS').
disease('EUTHYROID SICK SYNDROMES').
disease('TOOTH LOSS').
disease('ANOREXIA').
disease('KOTZOT-RICHTER SYNDROME').
disease('HISTIOCYTIC NECROTIZING LYMPHADENITIS').
disease('FIBROUS DYSPLASIA POLYOSTOTIC').
disease('LYMPHOPROLIFERATIVE SYNDROME X-LINKED 2').
disease('THORACIC OUTLET SYNDROME').
disease('INFLAMMATORY BREAST NEOPLASMS').
disease('REOVIRIDAE INFECTIONS').
disease('MONOCLONAL GAMMOPATHY OF UNDETERMINED SIGNIFICANCE').
disease('ATRIAL FIBRILLATION').
disease('RHINITIS ALLERGIC SEASONAL').
disease('PROGRESSIVE SUPRANUCLEAR PALSY ATYPICAL').
disease('CAMURATI-ENGELMANN SYNDROME').
disease('CHILBLAINS').
disease('MELIOIDOSIS').
disease('KERATITIS').
disease('DEVELOPMENTAL DEFECTS OF ENAMEL').
disease('RETROVIRIDAE INFECTIONS').
disease('GRANULOMATOUS DISEASE CHRONIC').
disease('DUODENAL ULCER').
disease('GAUCHER DISEASE PERINATAL LETHAL').
disease('TUBERCULOSIS EXTRAPULMONARY').
disease('GLOMERULONEPHRITIS IGA').
disease('LATENT TUBERCULOSIS').
disease('LATENT INFECTION').
disease('DIABETIC NEUROPATHIES').
disease('EPISODIC ATAXIA').
disease('HYPOTENSION').
disease('TEMPOROMANDIBULAR JOINT DISORDERS').
disease('INTESTINAL NEOPLASMS').
disease('MALARIA VIVAX').
disease('HYPERTHERMIA').
disease('SHOCK CARDIOGENIC').
disease('WHIPPLE DISEASE').
disease('ANAPHYLAXIS').
disease('SEXUAL DYSFUNCTION PHYSIOLOGICAL').
disease('INTERNAL HERNIA').
disease('GLUCOCORTICOID RECEPTOR DEFICIENCY').
disease('ESSENTIAL HYPERTENSION').
disease('PREMENSTRUAL SYNDROME').
disease('VENTRICULAR FIBRILLATION').
disease('HYPERTENSION RESISTANT TO CONVENTIONAL THERAPY').
disease('GLAUCOMA OPEN-ANGLE').
disease('CARDIOMYOPATHY RIGHT VENTRICULAR DILATED').
disease('YANG DEFICIENCY').
disease('YIN DEFICIENCY').
disease('MENINGITIS BACTERIAL').
disease('CILIARY DISCOORDINATION DUE TO RANDOM CILIARY ORIENTATION').
disease('DRUG RESISTANT EPILEPSY').
disease('FEVER OF UNKNOWN ORIGIN').
disease('PEDIATRIC OBESITY').
disease('BRONCHOPULMONARY DYSPLASIA').
disease('BURNS').
disease('616452').
disease('FOWLPOX').
disease('TAKAYASU ARTERITIS').
disease('ZINC DEFICIENCY NEONATAL DUE TO LOW BREAST MILK ZINC').
disease('HEREDITARY LEIOMYOMATOSIS AND RENAL CELL CANCER').
disease('STOMATOGNATHIC DISEASES').
disease('WASTING SYNDROME').
disease('SKIN ULCER').
disease('INTRAOPERATIVE COMPLICATIONS').
disease('POSTOPERATIVE COGNITIVE COMPLICATIONS').
disease('SPINAL DYSRAPHISM').
disease('MUSCULAR DYSTROPHY DUCHENNE').
disease('MUSCULAR DYSTROPHIES').
disease('VENOUS INSUFFICIENCY').
disease('VARICOSE VEINS').
disease('GENITAL DISEASES FEMALE').
disease('HYPOTHYROIDISM CONGENITAL NONGOITROUS 2').
disease('BRAIN INJURY CHRONIC').
disease('ALPHAVIRUS INFECTIONS').
disease('PRESSURE ULCER').
disease('URETERAL OBSTRUCTION').
disease('LYMPHOMA LARGE-CELL ANAPLASTIC').
disease('CHILBLAIN LUPUS 1').
disease('DRUG ERUPTIONS').
disease('DISSEMINATED INTRAVASCULAR COAGULATION').
disease('NARCOLEPSY 1').
disease('SLEEP WAKE DISORDERS').
disease('ONCOGENE ADDICTION').
disease('GASTRO-ENTEROPANCREATIC NEUROENDOCRINE TUMOR').
disease('PLACENTAL INSUFFICIENCY').
disease('APRAXIA IDEOMOTOR').
disease('CONGENITAL ADRENAL HYPERPLASIA DUE TO 21 HYDROXYLASE DEFICIENCY').
disease('COMBINED CELLULAR AND HUMORAL IMMUNE DEFECTS WITH GRANULOMAS').
disease('PHAGOCYTE BACTERICIDAL DYSFUNCTION').
disease('URTICARIA').
disease('HEART FAILURE DIASTOLIC').
disease('FAMILIAL MEDITERRANEAN FEVER').
disease('PNEUMONIA BACTERIAL').
disease('DENTAL LEAKAGE').
disease('HENIPAVIRUS INFECTIONS').
disease('SEZARY SYNDROME').
disease('AMYLOIDOSIS').
disease('USHER SYNDROME TYPE IE').
disease('HYPEREOSINOPHILIC SYNDROME').
disease('TOXOPLASMOSIS OCULAR').
disease('PNEUMONIA MYCOPLASMA').
disease('DENTIGEROUS CYST').
disease('RADICULAR CYST').
disease('DILATATION PATHOLOGIC').
disease('RADIATION PNEUMONITIS').
disease('HYPOPARATHYROIDISM').
disease('HYPERALDOSTERONISM').
disease('TRAUMA NERVOUS SYSTEM').
disease('FOLATE MALABSORPTION HEREDITARY').
disease('KIDNEY TUBULAR NECROSIS ACUTE').
disease('ABCD SYNDROME').
disease('HYALINE MEMBRANE DISEASE').
disease('TAKOTSUBO CARDIOMYOPATHY').
disease('OCULAR HYPERTENSION').
disease('HYPERCAPNIA').
disease('PEDIATRIC ACUTE-ONSET NEUROPSYCHIATRIC SYNDROME').
disease('FELINE INFECTIOUS PERITONITIS').
disease('BONE DISEASES METABOLIC').
disease('BARRETT ESOPHAGUS').
disease('607948').
disease('AUTOIMMUNE POLYENDOCRINOPATHY SYNDROME TYPE 1').
disease('UROGENITAL DISEASES').
disease('PHARYNGITIS').
disease('GLAUCOMA ANGLE-CLOSURE').
disease('DOG DISEASES').
disease('MULTIPLE PTERYGIUM SYNDROME AUTOSOMAL DOMINANT').
disease('ASPERGILLOSIS').
disease('GRANULOMATOUS MASTITIS').
disease('GEOGRAPHIC ATROPHY').
disease('603933').
disease('AORTIC ROOT ANEURYSM').
disease('BLAU SYNDROME').
disease('ERYTHEMA AB IGNE').
disease('HEAVY CHAIN DISEASE').
disease('EMPYEMA PLEURAL').
disease('OSTEOMYELITIS').
disease('BCG INFECTION GENERALIZED FAMILIAL').
disease('CACHEXIA').
disease('BRONCHIAL DISEASES').
disease('ARTHROGRYPOSIS').
disease('PSYCHOLOGICAL TRAUMA').
disease('ANTHRAX').
disease('EPILEPSY IDIOPATHIC GENERALIZED').
disease('CARCINOMA SMALL CELL').
disease('KELOID').
disease('ASCITES').
disease('CHAGAS CARDIOMYOPATHY').
disease('615978').
disease('TALAROMYCOSIS').
disease('INFECTIOUS MONONUCLEOSIS').
disease('XANTHOMATOSIS CEREBROTENDINOUS').
disease('THROMBOANGIITIS OBLITERANS').
disease('INFLAMMATORY BOWEL DISEASE 2').
disease('LEPROSY MULTIBACILLARY').
disease('CYCLIC NEUTROPENIA').
disease('GRANULOMATOSIS WITH POLYANGIITIS').
disease('LABOR PAIN').
disease('POLYENDOCRINOPATHIES AUTOIMMUNE').
disease('TUBERCULOSIS LYMPH NODE').
disease('MALARIA FALCIPARUM').
disease('OROPHARYNGEAL NEOPLASMS').
disease('MUCUS INSPISSATION OF RESPIRATORY TRACT').
disease('ENTEROCOLITIS NECROTIZING').
disease('614389').
disease('ECHINOCOCCOSIS HEPATIC').
disease('SWEET SYNDROME').
disease('HYPERSENSITIVITY').
disease('616087').
disease('PULMONARY HEART DISEASE').
disease('DESMOPLASTIC SMALL ROUND CELL TUMOR').
disease('SMOOTH MUSCLE TUMOR').
disease('LIPID METABOLISM DISORDERS').
disease('VON WILLEBRAND DISEASE TYPE 2').
disease('ANTI-NEUTROPHIL CYTOPLASMIC ANTIBODY-ASSOCIATED VASCULITIS').
disease('ANUS NEOPLASMS').
disease('LEIOMYOSARCOMA').
disease('HYPOPHYSITIS').
disease('ALOPECIA NEUROLOGIC DEFECTS AND ENDOCRINOPATHY SYNDROME').
disease('SEXUALLY TRANSMITTED DISEASES').
disease('PARAKERATOSIS').
disease('ENCEPHALITIS TICK-BORNE').
disease('TRICHURIASIS').
disease('HOOKWORM INFECTIONS').
disease('VASCULAR CALCIFICATION').
disease('DEMENTIA MULTI-INFARCT').
disease('THYROID CANCER MEDULLARY').
disease('CORONARY RESTENOSIS').
disease('STUVE-WIEDEMANN SYNDROME').
disease('THYMIC EPITHELIAL TUMOR').
disease('LACTATION DISORDERS').
disease('OCULOCUTANEOUS ALBINISM TYPE 2').
disease('ESCHERICHIA COLI INFECTIONS').
disease('HYPERKINESIS').
disease('DEMENTIA VASCULAR').
disease('PNEUMONIA VENTILATOR-ASSOCIATED').
disease('VENTILATOR-INDUCED LUNG INJURY').
disease('LEIGH DISEASE').
disease('MICROPHTHALMIA SYNDROMIC 10').
disease('LEARNING DISABILITIES').
disease('FAMILIAL PRIMARY PULMONARY HYPERTENSION').
disease('CHROMOBLASTOMYCOSIS').
disease('LATENT AUTOIMMUNE DIABETES IN ADULTS').
disease('VULVAR NEOPLASMS').
disease('MEGACOLON').
disease('PARATUBERCULOSIS').
disease('HYPOTRICHOSIS').
disease('LARON SYNDROME').
disease('TISSUE ADHESIONS').
disease('PULMONARY EOSINOPHILIA').
disease('VASCULAR RING').
disease('LUMBAR STENOSIS FAMILIAL').
disease('PROPPING ZERRES SYNDROME').
disease('PYODERMA GANGRENOSUM').
disease('HEREDITARY SENSORY AND MOTOR NEUROPATHY').
disease('614822').
disease('HEMOGLOBINURIA PAROXYSMAL').
disease('BACTEREMIA').
disease('612348').
disease('LISTERIOSIS').
disease('PARACOCCIDIOIDOMYCOSIS').
disease('PARKINSON DISEASE 12').
disease('STENOTROPHOMONAS MALTOPHILIA BACTEREMIA').
disease('LEPROSY LEPROMATOUS').
disease('CHRONIC URTICARIA').
disease('DANDRUFF').
disease('KIDNEY CALCULI').
disease('CAROTID ARTERY DISEASES').
disease('ECTRODACTYLY').
disease('607965').
disease('INTERVERTEBRAL DISC DISPLACEMENT').
disease('ACIDEMIA ISOVALERIC').
disease('CONGENITAL HYPOTHYROIDISM').
disease('PSEUDOMONAS INFECTIONS').
disease('NEOPLASMS GERM CELL AND EMBRYONAL').
disease('POLYCYSTIC OVARY SYNDROME').
disease('CIRRHOSIS FAMILIAL').
disease('NETHERTON SYNDROME').
disease('GSD IV NEUROMUSCULAR FORM FATAL PERINATAL').
disease('INTESTINAL PSEUDO-OBSTRUCTION').
disease('SPLENIC NEOPLASMS').
disease('CHORDOMA').
disease('LOEYS-DIETZ SYNDROME').
disease('AORTIC DISSECTION').
disease('ENDOCARDITIS BACTERIAL').
disease('300831').
disease('CARDIOVASCULAR ABNORMALITIES').
disease('MUSCULOSKELETAL ABNORMALITIES').
disease('CARDIO-RENAL SYNDROME').
disease('PANIC DISORDER').
disease('COMPULSIVE PERSONALITY DISORDER').
disease('ABORTION MISSED').
disease('STAPHYLOCOCCAL INFECTIONS').
disease('EPISODIC ATAXIA TYPE 1').
disease('PSEUDOLYMPHOMA').
disease('TAUOPATHIES').
disease('CELL TRANSFORMATION VIRAL').
disease('MYELOPROLIFERATIVE SYNDROME TRANSIENT').
disease('CRANIOPHARYNGIOMA').
disease('RECURRENT RESPIRATORY PAPILLOMATOSIS').
disease('MOYAMOYA DISEASE').
disease('HYPOGLYCEMIA').
disease('PERINATAL DEATH').
disease('MYASTHENIA GRAVIS AUTOIMMUNE EXPERIMENTAL').
disease('PLAGUE').
disease('ANTIBODY DEFICIENCY DUE TO DEFECT IN CD19').
disease('MALFORMATIONS OF CORTICAL DEVELOPMENT GROUP II').
disease('MALLORY-WEISS SYNDROME').
disease('BILIARY TRACT NEOPLASMS').
disease('CHROMOSOME 1 RING').
disease('ENTEROPATHY-ASSOCIATED T-CELL LYMPHOMA').
disease('NEUTROPENIA SEVERE CHRONIC').
disease('DIGESTIVE SYSTEM NEOPLASMS').
disease('DEGLOVING INJURIES').
disease('MENOPAUSE PREMATURE').
disease('LIVER ABSCESS AMEBIC').
disease('CHRONIC RECURRENT MULTIFOCAL OSTEOMYELITIS').
disease('GLUCOSE-GALACTOSE MALABSORPTION').
disease('ACUTE AORTIC SYNDROME').
disease('EALES DISEASE').
disease('KLEBSIELLA INFECTIONS').
disease('NON-FILARIAL LYMPHEDEMA').
disease('LYMPHEDEMA').
disease('FIBROCARTILAGINOUS EMBOLISM').
disease('LOCKED-IN SYNDROME').
disease('GRAFT OCCLUSION VASCULAR').
disease('NEONATAL HEMOCHROMATOSIS').
disease('CLEFT PALATE ISOLATED AND MENTAL RETARDATION').
disease('SUBARACHNOID HEMORRHAGE').
disease('CARPAL TUNNEL SYNDROME').
disease('HEART DEFECTS CONGENITAL').
disease('HEREDITARY SENSORY AND AUTONOMIC NEUROPATHIES').
disease('TUMOR LYSIS SYNDROME').
disease('WHIM SYNDROME').
disease('FIBROCYSTIC BREAST DISEASE').
disease('CHLAMYDOPHILA INFECTIONS').
disease('ROTATOR CUFF INJURIES').
disease('CONE DYSTROPHY X-LINKED 1').
disease('ROOT RESORPTION').
disease('FLUOROSIS DENTAL').
disease('ADENOMA OXYPHILIC').
disease('COLLAGEN DISEASES').
disease('RETROPERITONEAL NEOPLASMS').
disease('LI-FRAUMENI SYNDROME').
disease('CHURG-STRAUSS SYNDROME').
disease('DERMATITIS ATOPIC 3').
disease('SOMATOSENSORY DISORDERS').
disease('FRIEDREICH ATAXIA').
disease('GAIT ATAXIA').
disease('LARYNGEAL NEOPLASMS').
disease('CONGENITAL CENTRAL HYPOVENTILATION SYNDROME').
disease('TRANSCOBALAMIN I DEFICIENCY').
disease('PALLISTER W SYNDROME').
disease('CAMPOMELIC DYSPLASIA').
disease('NEUROMA ACOUSTIC').
disease('DENTAL PLAQUE').
disease('COCAINE-RELATED DISORDERS').
disease('HEAD INJURIES CLOSED').
disease('HEPATIC ENCEPHALOPATHY').
disease('227645').
disease('MUCOR INFECTION').
disease('PNEUMONIA LIPID').
disease('OPTIC NEURITIS').
disease('SPECIFIC LANGUAGE DISORDER').
disease('GROWTH FACTORS COMBINED DEFECT OF').
disease('616834').
disease('SEGAWA SYNDROME AUTOSOMAL RECESSIVE').
disease('CARCINOMA EMBRYONAL').
disease('617027').
disease('HYPERTELORISM WITH ESOPHAGEAL ABNORMALITY AND HYPOSPADIAS').
disease('MUSCULAR DYSTROPHY FACIOSCAPULOHUMERAL').
disease('ODONTOGENIC CYSTS').
disease('CONJUNCTIVAL DISEASES').
disease('OSTEOCHONDRITIS').
disease('ARTERITIS').
disease('PTERYGIUM').
disease('CRYPTOSPORIDIOSIS').
disease('HYPER-IGM IMMUNODEFICIENCY SYNDROME TYPE 1').
disease('ACUTE GENERALIZED EXANTHEMATOUS PUSTULOSIS').
disease('ANTI-N-METHYL-D-ASPARTATE RECEPTOR ENCEPHALITIS').
disease('GRAM-POSITIVE BACTERIAL INFECTIONS').
disease('CHOLERA').
disease('ALVEOLITIS EXTRINSIC ALLERGIC').
disease('PNEUMOCONIOSIS').
disease('DIGEORGE SYNDROME').
disease('EMPYEMA').
disease('PERIPROSTHETIC FRACTURES').
disease('HEART FAILURE SYSTOLIC').
disease('HYPERTENSION RENAL').
disease('CONGENITAL AMEGAKARYOCYTIC THROMBOCYTOPENIA').
disease('JEJUNAL DISEASES').
disease('ANXIETY DISORDERS').
disease('TRIGEMINAL NEURALGIA').
disease('FEMORAL NEOPLASMS').
disease('PRION DISEASES').
disease('ATTENTION DEFICIT DISORDER WITH HYPERACTIVITY').
disease('FOOT DEFORMITIES').
disease('MIXED DEMENTIAS').
disease('NOCICEPTIVE PAIN').
disease('BOVINE VIRUS DIARRHEA-MUCOSAL DISEASE').
disease('POLYOMAVIRUS INFECTIONS').
disease('INSULIN-LIKE GROWTH FACTOR I DEFICIENCY').
disease('SUDDEN INFANT DEATH').
disease('COLOR VISION DEFECTS').
disease('FIBROMYALGIA').
disease('LYMPHANGIOLEIOMYOMATOSIS').
disease('EYE BURNS').
disease('ANTERIOR POLAR CATARACT 2').
disease('PELVIC ORGAN PROLAPSE').
disease('HEMOPHILIA A').
disease('ADENOCARCINOMA IN SITU').
disease('HLA CLASS 1 DEFICIENCY').
disease('STORM SYNDROME').
disease('KERATITIS DENDRITIC').
disease('OPTIC NERVE INJURIES').
disease('FACIAL NERVE DISEASES').
disease('VENOM HYPERSENSITIVITY').
disease('FELINE ACQUIRED IMMUNODEFICIENCY SYNDROME').
disease('OTITIS MEDIA WITH EFFUSION').
disease('HEMOLYTIC-UREMIC SYNDROME').
disease('HYPOXIA-ISCHEMIA BRAIN').
disease('HYPERPHAGIA').
disease('ATR-X SYNDROME').
disease('SPACE MOTION SICKNESS').
disease('FELTY SYNDROME').
disease('EXTRANODAL EXTENSION').
disease('GIANT CELL TUMOR OF BONE').
disease('RHEUMATIC HEART DISEASE').
disease('LARON SYNDROME TYPE 2').
disease('HOLOPROSENCEPHALY').
disease('FEMINIZATION').
disease('LEUKEMIA PROLYMPHOCYTIC').
disease('HEREDITARY CENTRAL NERVOUS SYSTEM DEMYELINATING DISEASES').
disease('NEOPLASMS UNKNOWN PRIMARY').
disease('HAMMAN-RICH SYNDROME').
disease('CHORIOCARCINOMA NON-GESTATIONAL').
disease('HEMORRHOIDS').
disease('MUCOLIPIDOSES').
disease('HANTAVIRUS PULMONARY SYNDROME').
disease('RHEUMATOID VASCULITIS').
disease('MEGALENCEPHALIC LEUKOENCEPHALOPATHY WITH SUBCORTICAL CYSTS').
disease('SOLITARY FIBROUS TUMORS').
disease('VULVAR LICHEN SCLEROSUS').
disease('PROLAPSE').
disease('NEUROFIBROMATOSIS 1').
disease('DENYS-DRASH SYNDROME').
disease('MUNGAN SYNDROME').
disease('DYSGAMMAGLOBULINEMIA').
disease('RESPIRATORY TRACT NEOPLASMS').
disease('STRUMA OVARII').
disease('CARCINOMA PAPILLARY').
disease('FOLIC ACID DEFICIENCY').
disease('PROSTATIC INTRAEPITHELIAL NEOPLASIA').
disease('VENTRICULAR DYSFUNCTION').
disease('3-HYDROXY-3-METHYLGLUTARYL-COA LYASE DEFICIENCY').
disease('BARAITSER BRETT PIESOWICZ SYNDROME').
disease('CATARACT AGE-RELATED CORTICAL 1').
disease('ORTHOSTATIC INTOLERANCE').
disease('ADENOMA PLEOMORPHIC').
disease('DYSKINESIA DRUG-INDUCED').
disease('CD8 DEFICIENCY FAMILIAL').
disease('CLASSICAL LISSENCEPHALIES AND SUBCORTICAL BAND HETEROTOPIAS').
disease('LATEX HYPERSENSITIVITY').
disease('MENKES KINKY HAIR SYNDROME').
disease('TUBERCULOSIS OCULAR').
disease('POSTERIOR LEUKOENCEPHALOPATHY SYNDROME').
disease('HERNIA INGUINAL').
disease('PEELING SKIN SYNDROME').
