% gene and gene products from PubTator
protein('STAT3').
protein('STAT5A').
protein('CCND1').
protein('MYC').
protein('BCL2L1').
protein('MCL1').
protein('VEGFA').
protein('IFNG').
protein('JAK1').
protein('JAK2').
protein('TYK2').
protein('STAT1').
protein('STAT2').
protein('STAT6').
protein('EGF').
protein('TNF').
protein('IL6').
protein('CD2').
protein('CD28').
protein('CD4').
protein('STAT4').
protein('MOG').
protein('CD8A').
protein('ITGAE').
protein('CD207').
protein('CLEC9A').
protein('CCR5').
protein('IL10').
protein('MKI67').
protein('LGR5').
protein('IL2').
protein('IL17A').
protein('IL4').
protein('TGFB1').
protein('TBX21').
protein('GATA3').
protein('FOXP3').
protein('IL2RA').
protein('NFKB1').
protein('IL1B').
protein('NT5E').
protein('THY1').
protein('CD34').
protein('PTPRC').
protein('CASP3').
protein('PTGS2').
protein('MMP1').
protein('SRY').
protein('SOX9').
protein('ACAN').
protein('COL2A1').
protein('CHUK').
protein('NFKBIA').
protein('RELA').
protein('CXCR4').
protein('ACKR3').
protein('CXCL12').
protein('ADRA1A').
protein('ADRA1B').
protein('SERPINA1').
protein('ACE2').
protein('CRP').
protein('IFNA2').
protein('TLR3').
protein('STAT5B').
protein('SOCS1').
protein('CXCL8').
protein('TGFBR1').
protein('SMAD2').
protein('HDAC1').
protein('IFNA1').
protein('GZMB').
protein('MIP').
protein('CXCL10').
protein('CCL2').
protein('GPT').
protein('FGB').
protein('VWF').
protein('IFNB1').
protein('IFNAR1').
protein('IL6ST').
protein('S').
protein('IRAK1').
protein('MAP3K8').
protein('IRF3').
protein('IFNL1').
protein('NFE2L2').
protein('DPP4').
protein('AGTR1').
protein('ADAM17').
protein('YAP1').
protein('CXCL1').
protein('FGF10').
protein('SOX2').
protein('SIRT1').
protein('FN1').
protein('CCR2').
protein('CCR1').
protein('C5AR1').
protein('F2R').
protein('F2').
protein('IFNAR2').
protein('IRF9').
protein('LTF').
protein('TLR4').
protein('GFAP').
protein('SAMHD1').
protein('HNF1A').
protein('HNF1B').
protein('THPO').
protein('MPL').
protein('JAK3').
protein('JUN').
protein('CSF2').
protein('TNFRSF1B').
protein('TNFRSF1A').
protein('IL12B').
protein('TRBV20OR9-2').
protein('IL5').
protein('EP300').
protein('CREBBP').
protein('HCFC1').
protein('PLAU').
protein('PLAUR').
protein('IL13').
protein('INS').
protein('CEBPB').
protein('CEBPD').
protein('CEBPA').
protein('PPARG').
protein('IFNGR2').
protein('IL7').
protein('IL15').
protein('BCL2').
protein('MYB').
protein('GGH').
protein('IFNA8').
protein('IL4R').
protein('IL15RA').
protein('SOCS4').
protein('IL1RN').
protein('STAT92E').
protein('FCER2').
protein('IRF7').
protein('STAT1A').
protein('CISH').
protein('SOCS2').
protein('EPO').
protein('PRL').
protein('TLR7').
protein('TLR9').
protein('BCL6').
protein('CXCL11').
protein('CCL5').
protein('ESR1').
protein('LIF').
protein('FOSB').
protein('CD69').
protein('KLRK1').
protein('HLA-E').
protein('KLRC1').
protein('HLA-C').
protein('MICB').
protein('MAP2K1').
protein('MAPK1').
protein('UBASH3B').
protein('TNFRSF25').
protein('HLA-DQB1').
protein('HDAC9').
protein('ULBP2').
protein('MYOM2').
protein('KIR3DL3').
protein('KIR2DL4').
protein('FCGR3A').
protein('ICAM1').
protein('KIR2DL3').
protein('ERBB2').
protein('RUNX3').
protein('HLA-B').
protein('ERAP1').
protein('ERAP2').
protein('IL23R').
protein('IL6R').
protein('IL1R1').
protein('IL7R').
protein('IL23A').
protein('IRF1').
protein('MAPK14').
protein('AKT1').
protein('TMPRSS2').
protein('XBP1').
protein('ESCO2').
protein('GZMA').
protein('NKG7').
protein('CCL4').
protein('SLC7A11').
protein('CD14').
protein('IDH1').
protein('APP').
protein('SPI1').
protein('LAMP1').
protein('CTLA4').
protein('ACE').
protein('CXCL9').
protein('SNCA').
protein('NOS2').
protein('HRAS').
protein('CDH1').
protein('SCD1').
protein('CD163').
protein('IDO1').
protein('CXCR3').
protein('CCR9').
protein('TRIM63').
protein('SOCS6').
protein('ICAM5').
protein('KRAS').
protein('KITLG').
protein('IFNR').
protein('PIK3R2').
protein('A4GALT').
protein('SYK').
protein('ZAP70').
protein('F3').
protein('FGF9').
protein('IL27RA').
protein('EPOR').
protein('MX1').
protein('EIF2AK2').
protein('IL18').
protein('FBXW11').
protein('SKP1').
protein('CUL1').
protein('RBX1').
protein('CBLL2').
protein('IL12A').
protein('TLR8').
protein('SRC').
protein('RHOF').
protein('PTPN11').
protein('SOCS3').
protein('IFNGR1').
protein('DUOX2').
protein('SMOC1').
protein('S1PR1').
protein('IFIH1').
protein('DHX58').
protein('MMP9').
protein('CD274').
protein('ADAM10').
protein('UL50').
protein('CSNK1A1').
protein('PRKD2').
protein('MIR935').
protein('CD96').
protein('NCR2').
protein('CCR7').
protein('DDX58').
protein('GSK3B').
protein('CREB1').
protein('MAPK3').
protein('ITGAM').
protein('CD19').
protein('IGHM').
protein('BCR').
protein('CD80').
protein('CHRNA7').
protein('NR3C1').
protein('IL27').
protein('NFIL3').
protein('HAVCR2').
protein('IL9').
protein('IL9R').
protein('APOE').
protein('VCAM1').
protein('EGR2').
protein('LAG3').
protein('NFATC1').
protein('CDKN1A').
protein('ICOS').
protein('H2').
protein('BSG').
protein('CD33').
protein('IL21').
protein('MMP2').
protein('MMP3').
protein('MMP13').
protein('PIK3CD').
protein('PTK2B').
protein('CD86').
protein('ITGAX').
protein('ARG1').
protein('CTSL').
protein('IL17F').
protein('PROCR').
protein('IRF4').
protein('IL1').
protein('NUP98').
protein('HAVCR1').
protein('MTOR').
protein('CD44').
protein('RAG2').
protein('SERPINB1-PS1').
protein('SPP1').
protein('ARID5A').
protein('TNFRSF4').
protein('RBP4').
protein('ZC3H12A').
protein('KLRB1').
protein('CCR6').
protein('CD38').
protein('CXCR5').
protein('IL21R').
protein('CD40LG').
protein('CD40').
protein('ITGAL').
protein('CALR').
protein('CD47').
protein('SLC2A1').
protein('PDIA3').
protein('PDCD1').
protein('COPS5').
protein('NRP1').
protein('FASLG').
protein('GATA2').
protein('RUNX1').
protein('DSG3').
protein('TNFRSF18').
protein('IL2RB').
protein('CCR4').
protein('AQP3').
protein('CIRBP').
protein('SELL').
protein('FAS').
protein('VIM').
protein('PECAM1').
protein('CHAT').
protein('FUT2').
protein('P2RX7').
protein('WAP').
protein('CSN2').
protein('KITL').
protein('CSF1').
protein('CSF3').
protein('IL3').
protein('GH').
protein('IGF1').
protein('IGFBP3').
protein('GAS1').
protein('EPHA8').
protein('LCK').
protein('KIT').
protein('TXK').
protein('GLYCAM1').
protein('GAS2').
protein('TNFSF11').
protein('TNFRSF11A').
protein('TNFRSF11B').
protein('PIK3R1').
protein('PRKCE').
protein('ZHX2').
protein('TBP').
protein('CCN3').
protein('FLT3LG').
protein('CDKN2B').
protein('TNFRSF8').
protein('CCL17').
protein('CCL22').
protein('TPH1').
protein('PPARD').
protein('VSIR').
protein('MAF').
protein('BATF3').
protein('NFATC2').
protein('PRDM1').
protein('HMGB1').
protein('ITGB1').
protein('DNER').
protein('IL22').
protein('ACTA2').
protein('SAA1').
protein('IPO7').
protein('ACO1').
protein('SP1').
protein('IFNA').
protein('MAVS').
protein('TICAM1').
protein('LY6C1').
protein('IL10RA').
protein('IFNLR1').
protein('IL10RB').
protein('IL12RB2').
protein('RACK1').
protein('EDN1').
protein('RIPK3').
protein('MBP').
protein('CD27').
protein('CASP1').
protein('IL1A').
protein('NLRP3').
protein('EOMES').
protein('HSPA8').
protein('MAPKAPK2').
protein('ENPP2').
protein('IL12RB1').
protein('MUC5AC').
protein('IFNA15').
protein('IL2RG').
protein('CCL20').
protein('NCAM1').
protein('RORC').
protein('IFI35').
protein('OSM').
protein('ID2').
protein('IRF5').
protein('RUNX2').
protein('TP53').
protein('ABL1').
protein('ATG7').
protein('CDKN1B').
protein('MAPK8').
protein('MAP1LC3A').
protein('MAP1LC3B').
protein('TRAV6-3').
protein('NELFCD').
protein('CD83').
protein('CD3E').
protein('KRT20').
protein('CSN1S1').
protein('PRLR').
protein('BCL3').
protein('IRF2').
protein('MX2').
protein('IGHV1-9').
protein('IGHG1').
protein('RNASEL').
protein('IFNL3').
protein('MYD88').
protein('TICAM2').
protein('IFI47').
protein('IFNA3').
protein('BIRC3').
protein('CASP8').
protein('TNFRSF10B').
protein('PPR1').
protein('TLR2').
protein('LAMP2').
protein('USP18').
protein('CCL7').
protein('SREBF2').
protein('BID').
protein('TNFSF10').
protein('HLA-DRB1').
protein('SLC10A1').
protein('IFN-ALPHA-14').
protein('CDK4').
protein('ATM').
protein('FGF2').
protein('PDGFRB').
protein('PIK3CB').
protein('HLA-A').
protein('HLA-DRB4').
protein('TRAJ60').
protein('TRB').
protein('BW6').
protein('B2M').
protein('HLA-G').
protein('CD46').
protein('BRD2').
protein('H2-K1').
protein('MRAP').
protein('GAG').
protein('HLA-DQA1').
protein('TOR1A').
protein('CD68').
protein('IGF1R').
protein('KDR').
protein('RB1').
protein('PTK6').
protein('HIF1A').
protein('GH1').
protein('LYN').
protein('ETV6').
protein('EREG').
protein('GHR').
protein('IGF2').
protein('MSC').
protein('PPP2R2B').
protein('PTPA').
protein('BACH2').
protein('SERPINE1').
protein('MEF2A').
protein('B3GAT1').
protein('PTK2').
protein('RPS6KA1').
protein('SETD1B').
protein('DDX3X').
protein('TET2').
protein('RARA').
protein('GNRHR').
protein('CD247').
protein('MS4A1').
protein('IL18R1').
protein('REL').
protein('RIPK2').
protein('NOD1').
protein('LOC105243590').
protein('CCL3').
protein('JUNB').
protein('FOSL1').
protein('PTPN6').
protein('IL37').
protein('CREM').
protein('KPNA2').
protein('SYT1').
protein('CLDN1').
protein('CDH2').
protein('SNAI1').
protein('XPO1').
protein('RAN').
protein('MAP3K11').
protein('CHEK1').
protein('TNPO1').
protein('PKHD1').
protein('KPNA1').
protein('TNPO3').
protein('CDK5').
protein('SMAD4').
protein('NAPSA').
protein('KPNA3').
protein('KPNB1').
protein('KIF11').
protein('PSE1').
protein('CTNNB1').
protein('GRB10').
protein('PHGDH').
protein('EGFR').
protein('PIK3CA').
protein('NS2').
protein('IVNS1ABP').
protein('PBRM1').
protein('NXF1').
protein('RGPD2').
protein('NUP62').
protein('RANBP1').
protein('UBE2E3').
protein('IPO11').
protein('KEAP1').
protein('COL18A1').
protein('NCL').
protein('FOXO3').
protein('SETBP1').
protein('STK38').
protein('BECN1').
protein('HSF1').
protein('MALAT1').
protein('E2F1').
protein('APC').
protein('KPNA4').
protein('PTEN').
protein('RHOA').
protein('XPO5').
protein('MIR17HG').
protein('MIR19A').
protein('BRAF').
protein('NOTCH1').
protein('HNRNPA1').
protein('FUS').
protein('RBMS3').
protein('MIR221').
protein('MIR222').
protein('LYZ').
protein('GZMK').
protein('ITIH4').
protein('ENV').
protein('LMNA').
protein('MDM2').
protein('SPHK1').
protein('ERVK-20').
protein('ESR2').
protein('CXCR6').
protein('LRPAP1').
protein('LRP1').
protein('NR1H3').
protein('ABCA1').
protein('CDK1').
protein('RAF1').
protein('HSP90AA1').
protein('PROS1').
protein('G3BP1').
protein('HSP90AB1').
protein('YBX1').
protein('HNRNPA2B1').
protein('PDK1').
protein('USP33').
protein('SUCLG1').
protein('ADRB2').
protein('ARID1A').
protein('STUB1').
protein('BANF1').
protein('TRIM28').
protein('DDIT3').
protein('CCL1').
protein('CCL11').
protein('CCL21').
protein('CCL25').
protein('CCL28').
protein('CCR3').
protein('CCR8').
protein('CCR10').
protein('CD209').
protein('TAT').
protein('MCAM').
protein('CCL14').
protein('APOBEC3A').
protein('SLAMF1').
protein('CCL27').
protein('XCL1').
protein('IFITM1').
protein('IFITM2').
protein('TRAJ33').
protein('ZBTB16').
protein('LAIR1').
protein('NRSN1').
protein('LBR').
protein('NEF').
protein('CD74').
protein('ITGA4').
protein('H1-0').
protein('HSPA4').
protein('GLB1').
protein('MIR373').
protein('COX2').
protein('TIMP1').
protein('CDC73').
protein('AJUBA').
protein('IFIT2').
protein('CXCL13').
protein('ITGB2').
protein('ISG20').
protein('CX3CR1').
protein('VTN').
protein('HK2').
protein('KLRC2').
protein('PRRT2').
protein('FCGR2A').
protein('TH').
protein('MAFB').
protein('NAMPT').
protein('NBAS').
protein('IKZF1').
protein('FOS').
protein('POU2F2').
protein('LEF1').
protein('QRSL1').
protein('LEP').
protein('CYBA').
protein('NOX1').
protein('ISYNA1').
protein('MAP2K7').
protein('PRKCD').
protein('PRKCA').
protein('GNRH1').
protein('BAX').
protein('PIK3CG').
protein('IRF8').
protein('EZR').
protein('RDX').
protein('MSN').
protein('PLP1').
protein('PIAS1').
protein('CIITA').
protein('HLA-DRA').
protein('HLA-DPA1').
protein('GAST').
protein('BACE1').
protein('G6PC2').
protein('NFKBIB').
protein('PARP1').
protein('PSMB9').
protein('TAP1').
protein('PIAS3').
protein('PRDX6').
protein('SNX8').
protein('IKBKB').
protein('EZH2').
protein('DYNC1H1').
protein('FOSL2').
protein('ATF2').
protein('IFIT3').
protein('IFIT1').
protein('PARP9').
protein('DTX3L').
protein('TENM1').
protein('HMOX1').
protein('CSTB').
protein('IFN1@').
protein('ZC3HAV1').
protein('IFI27').
protein('ERG').
protein('FLI1').
protein('DPF2').
protein('TBK1').
protein('IKBKE').
protein('STING1').
protein('YY1').
protein('MIR223').
protein('MIR21').
protein('MIR155').
protein('DRD1').
protein('IBA1').
protein('MPO').
protein('TRAF6').
protein('SP7').
protein('IFI44').
protein('OPTN').
protein('MIR146').
protein('LEPR').
protein('INSR').
protein('CCKAR').
protein('POMC').
protein('PRKAA1').
protein('NPY').
protein('AGRP').
protein('AHR').
protein('CXCR2').
protein('CXCL2').
protein('PIM1').
protein('CD1C').
protein('RET').
protein('TMEM173').
protein('ART1').
protein('IFNA5').
protein('IFNA6').
protein('CLEC7A').
protein('IRF-1').
protein('DLK1').
protein('DLL1').
protein('RELB').
protein('ANXA5').
protein('S100A4').
protein('PCNA').
protein('EEA1').
protein('RAB7B').
protein('EIF2AK3').
protein('H3P16').
protein('PYCARD').
protein('PRKRA').
protein('SMAD6').
protein('SMAD7').
protein('SMAD1').
protein('MAP3K7').
protein('SNW1').
protein('IKBKG').
protein('OASL').
protein('ISG15').
protein('OAS2').
protein('ERN1').
protein('HSPA5').
protein('BRD9').
protein('BRD4').
protein('HAPLN1').
protein('ATR').
protein('ACAT1').
protein('CGAS').
protein('WTAP').
protein('NMB').
protein('NMBR').
protein('TRIM25').
protein('LTA').
protein('HBA2').
protein('TF').
protein('HBB').
protein('FCGRT').
protein('TFRC').
protein('IL19').
protein('IL20').
protein('IL24').
protein('IFNL2').
protein('TRK-CTT2-3').
protein('TSLP').
protein('IRAK4').
protein('CD276').
protein('CXCR1').
protein('XRN1').
protein('IFNA10').
protein('PLSCR1').
protein('IL3RA').
protein('CLEC4C').
protein('CD1A').
protein('CD52').
protein('MAP3K5').
protein('CAT').
protein('UL24').
protein('ENTPD1').
protein('LNPK').
protein('GC').
protein('AGER').
protein('CX3CL1').
protein('NLRP12').
protein('IFITM3').
protein('RSAD2').
protein('MIR326').
protein('KRT18').
protein('BST2').
protein('SLC17A5').
protein('NOX4').
protein('CASP9').
protein('LOC222344').
protein('REN').
protein('GATA6').
protein('SMARCA4').
protein('FOXM1').
protein('ESRRA').
protein('MAP4K3').
protein('UBR4').
protein('UCHL1').
protein('USP50').
protein('PIAS4').
protein('PRMT5').
protein('TFAP2A').
protein('TCRB').
protein('AGT').
protein('AGTR1A').
protein('IGHA').
protein('FCGR1').
protein('SDCBP').
protein('HLA-DRB5').
protein('HLA-DPB1').
protein('HLA-DQA2').
protein('HLA-DMA').
protein('CD7').
protein('XCR1').
protein('HLA-DOB').
protein('WARS1').
protein('ORF1AB').
protein('ORF10').
protein('ORF8').
protein('TLR1').
protein('AR').
protein('AGTR2').
protein('ANPEP').
protein('ENPEP').
protein('AP2B1').
protein('FLT1').
protein('ASGR1').
protein('DNASE1').
protein('ELANE').
protein('APLN').
protein('VN1R17P').
protein('APLNR').
protein('MBL2').
protein('FASN').
protein('PPIA').
protein('FURIN').
protein('APOL1').
protein('DNMT1').
protein('N').
protein('ANGPT1').
protein('AGTRAP').
protein('FOXO1').
protein('MIR1246').
protein('ALOX5').
protein('CD79A').
protein('GRN').
protein('PR').
protein('ERBB3').
protein('ERBB4').
protein('NRG1').
protein('PAX5').
protein('MAS1').
protein('PROM1').
protein('NRP2').
protein('SP2').
protein('ERVK-6').
protein('SELP').
protein('PGR').
protein('ADIPOQ').
protein('KDM1A').
protein('SETDB2').
protein('CENPW').
protein('HDAC4').
protein('SOD2').
protein('HDAC2').
protein('HDAC3').
protein('BCKDHB').
protein('DLAT').
protein('NSMF').
protein('TMEM106B').
protein('FANCB').
protein('D0FFM6').
protein('LY6E').
protein('CH25H').
protein('KLK4').
protein('APOBEC3G').
protein('CFTR').
protein('ANO1').
protein('ACTN4').
protein('TP63').
protein('SPTLC1').
protein('SPTLC3').
protein('MUC1').
protein('LSR').
protein('FLT3').
protein('KMT2A').
protein('CCND2').
protein('CCNL2').
protein('USF1').
protein('SERPINB2').
protein('HDAC8').
protein('THBD').
protein('CBL').
protein('RUNX1T1').
protein('EPHB2').
protein('PTPN22').
protein('KIR3DL1').
protein('IL4I1').
protein('TIRAP').
protein('IL34').
protein('IL20RA').
protein('POU1F1').
protein('CCL18').
protein('IL5RA').
protein('AIF1').
protein('VARS1').
protein('BTG3').
protein('CCL13').
protein('CCL26').
protein('PGF').
protein('VEGFC').
protein('VEGFD').
protein('HCP5').
protein('BRCA1').
protein('RGS1').
protein('C1QA').
protein('ABO').
protein('BW4').
protein('HP').
protein('TERT').
protein('DNMT3A').
protein('TRAF3').
protein('GPHA2').
protein('BCL2A1').
protein('IGKV2D-23').
protein('IGKV3D-25').
protein('CD24').
protein('IRF-3').
protein('TRIM5').
protein('TRIM22').
protein('IFNA17').
protein('PNP').
protein('BTK').
protein('EIF2A').
protein('ATF4').
protein('EIF2AK1').
protein('SSB').
protein('HTR2A').
protein('ACLY').
protein('IFNA13').
protein('IFNA14').
protein('IL4RA').
protein('IRS2').
protein('IRS1').
protein('ALOX15').
protein('IL1R2').
protein('IGKV1D-27').
protein('IFNA4').
protein('TNFRSF10A').
protein('FADD').
protein('TRADD').
protein('CFLAR').
protein('PPARGC1B').
protein('HAND2').
protein('TEK').
protein('MFT2').
protein('RNPS1').
protein('IFNL4').
protein('TNFSF13B').
protein('SIGLEC1').
protein('C3').
protein('PML').
protein('BBC3').
protein('IGKV2-23').
protein('LLGL2').
protein('TMEM37').
protein('PRTN3').
protein('SMAD3').
protein('COQ10A').
protein('CEACAM3').
protein('PMEL').
protein('MLANA').
protein('SLTM').
protein('PRKCZ').
protein('IL13RA1').
protein('IL13RA2').
protein('CDK2').
protein('SRSF1').
protein('GFI1').
protein('TCF7').
protein('IL33').
protein('IL1RL1').
protein('ACTA1').
protein('FCGR1A').
protein('VSX1').
protein('VPREB2').
protein('FOLH1').
protein('KLRA').
protein('TYR').
protein('MAGEA3').
protein('TAP2').
protein('TAPBP').
protein('EHMT2').
protein('AXL').
protein('CDKN2A').
protein('ELN').
protein('OAS1').
protein('ADAR').
protein('HNRNPC').
protein('TAC1').
protein('CCNA2').
protein('WNT5A').
protein('MMP7').
protein('LDLR').
protein('H2-AB1').
protein('PSMB8').
protein('IFNK').
protein('MARCO').
protein('ZEB2').
protein('OTULIN').
protein('RIPK1').
protein('CAMP').
protein('TLL1').
protein('NCOR1').
protein('TREM2').
protein('PF4').
protein('CSF1R').
protein('BAP1').
protein('TRIM33').
protein('IGHE').
protein('CD79B').
protein('KMT2D').
protein('HNF4A').
protein('NOD2').
protein('GIGYF1').
protein('AIRE').
protein('PIGR').
protein('ORAI1').
protein('MEF2C').
protein('ARID3B').
protein('AIM2').
protein('CTSB').
protein('TNFRSF14').
protein('DCPS').
protein('GBP5').
protein('GBP2').
protein('GSDMD').
protein('TRIM21').
protein('RO60').
protein('ACKR1').
protein('ZBP1').
protein('IPO4').
protein('BAK1').
protein('TNFSF8').
protein('SEPHS1').
protein('SH2D1A').
protein('CD1D1').
protein('CD24A').
protein('ADA').
protein('CXADRP1').
protein('ASF1A').
protein('H3C3').
protein('HAT1').
protein('ALB').
protein('LOC102724197').
protein('ALPP').
protein('TIGIT').
protein('MAPT').
protein('IL16').
protein('PTGDR2').
protein('CD101').
protein('HFM1').
protein('HAL').
protein('MAGEA4').
protein('MIF').
protein('EXOSC6').
protein('TNFRSF9').
protein('TMPRSS3').
protein('NAB2').
protein('CCNB1').
protein('AFP').
protein('HMMR').
protein('ACP3').
protein('TNIP1').
protein('TAX1BP1').
protein('TNFAIP3').
protein('TRIM11').
protein('TANK').
protein('PRKDC').
protein('GDNF').
protein('PKM').
protein('PIN1').
protein('IFI16').
protein('LRP1B').
protein('PSAT1').
protein('RNF180').
protein('IFNAB').
protein('IMPA1').
protein('ORF2').
protein('PTHLH').
protein('SCGB2A2').
protein('IFI30').
protein('EPHA2').
protein('PDLIM7').
protein('WT1').
protein('CYP2D6').
protein('GAD1').
protein('KRT88P').
protein('CDH3').
protein('MAGED4B').
protein('TNPO2').
protein('IPO5').
protein('NOS3').
protein('SOD1').
protein('PAK1').
protein('PDCD1LG2').
protein('TFF2').
protein('KIR2DS2').
protein('TJP1').
protein('OCLN').
protein('CLDN2').
protein('CLDN3').
protein('KIR2DL2').
protein('KIR3DL2').
protein('KIR2DS3').
protein('ELAVL2').
protein('CDC42').
protein('SIRT6').
protein('COL1A1').
protein('COL1A2').
protein('MAS1L').
protein('CCL8').
protein('CXCL6').
protein('LZTFL1').
protein('MUC4').
protein('SLC22A31').
protein('FDX2').
protein('PRKAA2').
protein('TYMP').
protein('LGALS3').
protein('MYH7').
protein('MYL2').
protein('CD5').
protein('REV').
protein('DDC').
protein('OGT').
protein('PLA2G4A').
protein('SPINT2').
protein('SERPINB3').
protein('CCNT1').
protein('CDK9').
protein('BIRC5').
protein('CCDC134').
protein('OAS3').
protein('CCRL2').
protein('SHARPIN').
protein('HDAC6').
protein('HLA-S').
protein('IFNA11').
protein('DUSP1').
protein('TNFSF4').
protein('CAMK2A').
protein('ITGA1').
protein('CD200R1').
protein('CCN2').
protein('LY6A').
protein('LYZ2').
protein('ABCB1').
protein('CD8B').
protein('CD160').
protein('WLS').
protein('CANX').
protein('ATF6').
protein('ATG5').
protein('ATG12').
protein('CALCA').
protein('DNAJB9').
protein('PIK3C3').
protein('PRL2C2').
protein('PPP1R15A').
protein('RYR1').
protein('PRF1').
protein('PTPN1').
protein('GSTK1').
protein('HCRT').
protein('PEPD').
protein('TPO').
protein('MIR208B').
protein('UCHL3').
protein('SART1').
protein('MIR1231').
protein('IFNE').
protein('TYROBP').
protein('UL42').
protein('EIF4G1').
protein('LGALS3BP').
protein('MIR33A').
protein('LINC00673').
protein('CD226').
protein('TCN2').
protein('ST2').
protein('BRCC3').
protein('CMPK2').
protein('MORC3').
protein('BCL6B').
protein('ORF7A').
protein('ORF3A').
protein('ERVW-1').
protein('ERVFRD-1').
protein('DR1').
protein('M').
protein('TPP2').
protein('A2M').
protein('LILRB3').
protein('PTPN4').
protein('MAGOHB').
protein('SH2D3A').
protein('LY96').
protein('ARSA').
protein('GAL').
protein('GP2').
protein('TECTA').
protein('THBS1').
protein('TRAV1-2').
protein('LOC102723407').
protein('CYP2C19').
protein('UGT1A1').
protein('SLC6A20').
protein('FYCO1').
protein('KIR2DL1').
protein('KIR2DS4').
protein('ANG').
protein('NDUFA5').
protein('MUC22').
protein('CFH').
protein('PVR').
protein('NECTIN2').
protein('TNFSF9').
protein('E').
protein('EHD2').
protein('GFM2').
protein('GSPT1').
protein('MAT2A').
protein('NQO2').
protein('SUPT6H').
protein('UMPS').
protein('NUSAP1').
protein('S100A1').
protein('ALK').
protein('NLRC5').
protein('NR4A2').
protein('SLAMF7').
protein('CD48').
protein('CD244').
protein('CD3G').
protein('AGO2').
protein('H3C10').
protein('MAPK4').
protein('PIK3C2A').
protein('HLA-F').
protein('XPO4').
protein('CD70').
protein('NCR1').
protein('HCK').
protein('POSTN').
protein('TRBV28').
protein('FCER1A').
protein('CLEC10A').
protein('TARP').
protein('ZNF683').
protein('DEFB4A').
protein('S100A8').
protein('MSR1').
protein('MRC1').
protein('CYCS').
protein('ICAM3').
protein('PTAFR').
protein('CEACAM6').
protein('GBP1').
protein('CEACAM8').
protein('MAP4K1').
protein('CMKLR1').
protein('CYBB').
protein('IL17C').
protein('LMP-1').
protein('NGFR').
protein('YRB1').
protein('RANBP2').
protein('DCTN6').
protein('SKP2').
protein('CSE1L').
protein('IL20RB').
protein('NPM1').
protein('POU5F1').
protein('PRKCQ').
protein('SETDB1').
protein('DICER1').
protein('IPO9').
protein('NR4A1').
protein('PAK4').
protein('NCOR2').
protein('FCN1').
protein('RPRM').
protein('MIR126').
protein('S100B').
protein('OLIG2').
protein('GRIN1').
protein('SHC1').
protein('CNTNAP1').
protein('CSF3R').
protein('EGR1').
protein('CRK').
protein('CRKL').
protein('TIMP3').
protein('TCF3').
protein('ETS1').
protein('GATA1').
protein('COL11A2').
protein('OBOX4').
protein('CXCL15').
protein('HGF').
protein('SNAI2').
protein('HAMP').
protein('XIAP').
protein('CSE').
protein('IL22RA1').
protein('FOXA3').
protein('MIR122').
protein('SOCS5').
protein('CUL5').
protein('BCL2L11').
protein('IGHJ1').
protein('STAR').
protein('OAS1A').
protein('DOK1').
protein('HSPH1').
protein('H3P6').
protein('SLC6A4').
protein('VIF').
protein('SLPI').
protein('NR0B2').
protein('INFA').
protein('IFNAA').
protein('LOC517016').
protein('TRIM14').
protein('MUL1').
protein('GGTLC5P').
protein('VIP').
protein('ADCYAP1').
protein('PTPRD').
protein('FAM3B').
protein('EPSTI1').
protein('IFI44L').
protein('EFHD2').
protein('FLT3L').
protein('PDP1').
protein('FBXW7').
protein('ESM1').
protein('SLC25A34').
protein('DTX4').
protein('APOBEC3B').
protein('MSL2').
protein('ACSL1').
protein('CD1D').
protein('NANOG').
protein('IL11').
protein('BMP4').
protein('BMP7').
protein('BMP1').
protein('KLF4').
protein('MIR1181').
protein('H2AX').
protein('SOX5').
protein('LIFR').
protein('MIR215').
protein('CEACAM5').
protein('SOX12').
protein('PVT1').
protein('NES').
protein('TUBB3').
protein('BGLAP2').
protein('MLH1').
protein('MSH6').
protein('CRYAB').
protein('BTRC').
protein('ITPR3').
protein('CDK6').
protein('HMGCR').
protein('GPM6A').
protein('IFN-TAU').
protein('WNT7A').
protein('HELZ2').
protein('IFI6').
protein('MGMT').
protein('STAM').
protein('HGS').
protein('TSC2').
protein('KLK1').
protein('RBFOX3').
protein('RARG').
protein('CHP1').
protein('ATF3').
protein('PCDH7').
protein('LPAR1').
protein('CDKL2').
protein('LPL').
protein('GFRA2').
protein('NR3C2').
protein('ADGRE1').
protein('CD200').
protein('MIR143').
protein('ULBP1').
protein('PGRMC1').
protein('SP110').
protein('ULBP3').
protein('IGKV1-27').
protein('MCM7').
protein('MIR20A').
protein('MIR9-3').
protein('CNR1').
protein('CNR2').
protein('TRAF3IP2').
protein('LINC00240').
protein('MIR124-3').
protein('PGP').
protein('TM4SF5').
protein('MSI2').
protein('PHB').
protein('PARP14').
protein('ITGB3').
protein('FPR2').
protein('OCSTAMP').
protein('LOC100361814').
protein('CXCL16').
protein('IL18BP').
protein('PSTPIP2').
protein('DNMT3B').
protein('PARP11').
protein('APOBEC3F').
protein('PBX1').
protein('FABP4').
protein('A3GALT2').
protein('PTGIS').
protein('DCSTAMP').
protein('MITF').
protein('FOXJ1').
protein('IL17RA').
protein('IRGM1').
protein('DUOXA2').
protein('KCNA3').
protein('FTO').
protein('YTHDF2').
protein('GBP9').
protein('MIR34A').
protein('TRPM7').
protein('CHIL3').
protein('RETNLA').
protein('EBI3').
protein('PRMT2').
protein('MARVELD2').
protein('IKZF2').
protein('VDR').
protein('RXRA').
protein('ANGPT2').
protein('BDNF').
protein('NTRK2').
protein('MUC2').
protein('DFNA34').
protein('TGM2').
protein('CEACAM1').
protein('NR1I3').
protein('UTRN').
protein('CREBZF').
protein('CR2').
protein('ECM1').
protein('TFDP2').
protein('PTGDS').
protein('PTGDR').
protein('ACSL4').
protein('AQP5').
protein('HMGB3').
protein('SPATA2').
protein('GPX4').
protein('SLC3A2').
protein('GDF15').
protein('ASXL2').
protein('LCN2').
protein('IGH-V7183').
protein('TRAF2').
protein('NFKBIZ').
protein('GSN').
protein('KMT2C').
protein('SSRP1').
protein('TOX').
protein('CDH5').
protein('TNFRSF17').
protein('CARTPT').
protein('TPST2').
protein('TGFBR2').
protein('TARM1').
protein('SQSTM1').
protein('GPR15').
protein('GCG').
protein('ARX').
protein('LY9').
protein('PTGIR').
protein('PPP2R1A').
protein('S100A12').
protein('MERTK').
protein('JUND').
protein('SELPLG').
protein('ROR1').
protein('MR1').
protein('FAP').
protein('RAVER1').
protein('STK11').
protein('SFTPA1').
protein('PTX3').
protein('CHI3L1').
protein('CLU').
protein('KLRD1').
protein('CFB').
protein('ITK').
protein('FYN').
protein('LRRK2').
protein('RAB10').
protein('IGFBP4').
protein('CBFB').
protein('FUT4').
protein('PRMT1').
protein('IL32').
protein('FGF21').
protein('SIGLEC7').
protein('IL6RA').
protein('FBN1').
protein('DIABLO').
protein('MLKL').
protein('ACOD1').
protein('STEAP1').
protein('PIBF1').
protein('ZBTB7B').
protein('APOB').
protein('LY6G').
protein('PGAM5').
protein('LILRB1').
protein('LILRB4').
protein('LGALS9').
protein('ITPA').
protein('ATHS').
protein('HTR1A').
protein('1300017J02RIK').
protein('ADA2').
protein('SNORD21').
protein('U21').
protein('MDK').
protein('SP3').
protein('ICAM2').
protein('UL16').
protein('TMED2').
protein('TRP53-PS').
protein('IMP3').
protein('RAE1').
protein('HDLBP').
protein('KL').
protein('NCR3').
protein('FAAH').
protein('FFAR3').
protein('FFAR2').
protein('RICTOR').
protein('IKZF3').
protein('CRBN').
protein('SLC40A1').
protein('ANXA1').
protein('KRT17').
protein('NR1H4').
protein('F11R').
protein('ATN1').
protein('CAVIN2').
protein('FLG').
protein('DKK1').
protein('MIR150').
protein('USP22').
protein('ACTN1').
protein('KDM6B').
protein('ZEB1').
protein('SIRPA').
protein('LAMP3').
protein('GRIA1').
protein('HDAC5').
protein('SIRT4').
protein('ORF63').
protein('MIR203').
protein('SIRT7').
protein('SMURF1').
protein('TGFB2').
protein('IL31').
protein('SELE').
protein('ALOX15B').
protein('FOXA1').
protein('MYOD1').
protein('CENPV').
protein('IGSF9').
protein('ST6GAL1').
protein('BICD2').
protein('GNLY').
protein('IGKV2-18').
protein('FLNB').
protein('CTAG1A').
protein('CAV1').
protein('KHSRP').
protein('CTSD').
protein('ABHD14B').
protein('ZG16B').
protein('TAM').
protein('EGLN3').
protein('PPARGC1A').
protein('BATF').
protein('TGFA').
protein('PDPN').
protein('TRIM10').
protein('ID2-AS1').
protein('PJA2').
protein('TRPV1').
protein('EIF4E').
protein('ACP5').
protein('CTSK').
protein('STRA6').
protein('BMF').
protein('SRA1').
protein('TLR5').
protein('SATB1').
protein('FDXR').
protein('CREB3L2').
protein('ASB2').
protein('STK35').
protein('CASP7').
protein('TRIB1').
protein('MAOA').
protein('RPS6KB1').
protein('MAPK9').
protein('FOXA2').
protein('MUC5B').
protein('SYNE2').
protein('EPHB1').
protein('MAPK7').
protein('AICDA').
protein('KRT14').
protein('STEAP3').
protein('RAC1').
protein('TNFAIP6').
protein('SOCS7').
protein('PPARA').
protein('MAP3K14').
protein('TMEM232').
protein('EPC2').
protein('KRT5').
protein('SFRP1').
protein('TFPI2').
protein('ITGAV').
protein('CTSS').
protein('CDCA7').
protein('ADM').
protein('GPR182').
protein('HLA-DRB3').
protein('GPC3').
protein('AQP4').
protein('MAD').
protein('IPO8').
protein('PPP2CB').
protein('HSPA1B').
protein('HSD17B8').
protein('ACRBP').
protein('EPCAM').
protein('KRT8').
protein('PCSK9').
protein('USP7').
protein('CTNNBL1').
protein('CD81').
protein('LRPPRC').
protein('AVP').
protein('RORA').
protein('ITLN1').
protein('APBA3').
protein('VPS35').
protein('KLHDC7B').
protein('SLC2A4').
protein('OAS1B').
protein('P2RY6').
protein('PANX1').
protein('MOV10L1').
protein('CD9').
protein('TRAIP').
protein('UNC93B1').
protein('VCAN').
protein('M6PR').
protein('KLF1').
protein('NLRC4').
protein('TREX1').
protein('PDC').
protein('ORF6').
protein('TACR2').
protein('CLDN5').
protein('DAAM1').
protein('SIGLEC14').
protein('C1QTNF6').
protein('MAP2K3').
protein('SH2B3').
protein('GRK2').
protein('PLIN2').
protein('ACVR1').
protein('PIEZO1').
protein('MIR203A').
protein('MYOG').
protein('LDHA').
protein('CMPK1').
protein('KRT6A').
protein('RNF41').
protein('HHIP').
protein('USP35').
protein('GOT2').
protein('CCND3').
protein('MIR17').
protein('HDVGP2').
protein('ACOX1').
protein('ZBTB20').
protein('MC1R').
protein('USP1').
protein('MEF2D').
protein('COL10A1').
protein('SSBP2').
protein('CPT1A').
protein('MIR4284').
protein('TYRO3').
protein('MMP12').
protein('FUT8').
protein('ALDH3A1').
protein('CYB5R3').
protein('TRPV2').
protein('APOC2').
protein('WBP1L').
protein('STIP1').
protein('TNK1').
protein('TIPARP').
protein('GYPA').
protein('UL49.5').
protein('OPN1SW').
protein('TNFSF15').
protein('CASP12').
protein('IGHA1').
protein('TG').
protein('HTR1B').
protein('NEU1').
protein('ENPP1').
protein('POLR2F').
protein('ANP32A').
protein('CHAF1A').
protein('DDB1').
protein('PTPN2').
protein('UL41').
protein('C\'').
protein('DCST1').
protein('NLRX1').
protein('SRF').
protein('MIR431').
protein('ELK1').
protein('PIAS2').
protein('PELI3').
protein('H3C7').
protein('H2AZ1').
protein('CTCF').
protein('NBR1').
protein('TYRP1').
protein('BMP6').
protein('PDGFA').
protein('SFPQ').
protein('MCPT1L1').
protein('OCA2').
protein('IFNA21').
protein('GLI1').
protein('PLCG1').
protein('BCL2L14').
protein('XAF1').
protein('NS1').
protein('MIR29A').
protein('MIR29B1').
protein('F2RL1').
protein('MIR145').
protein('UGT1A8').
protein('CASP10').
protein('PTPRR').
protein('APEX1').
protein('RANBP6').
protein('FTH1').
protein('FDPS').
protein('VP35').
protein('VP30').
protein('HLCS').
protein('RAB3GAP1').
protein('CNTF').
protein('TRAF5').
protein('TLR10').
protein('PLIN1').
protein('NCF1').
protein('NPPA').
protein('MIR551B').
protein('OSMR').
protein('IL31RA').
protein('RPTOR').
protein('CD58').
protein('CCL4L2').
protein('TCRD').
protein('S100A7').
protein('S100A9').
protein('APOA4').
protein('CLDN4').
protein('SLC11A1').
protein('HSPD1').
protein('HRH1').
protein('KIR2DS1').
protein('INSL3').
protein('FCGR3').
protein('CD55').
protein('HCST').
protein('MIR520B').
protein('LY75').
protein('PDGFRA').
protein('PLCE1').
protein('BF2').
protein('CXCL3').
protein('IL18RAP').
protein('GPR183').
protein('ALCAM').
protein('CKLF').
protein('TCF7L2').
protein('NLRP1').
protein('ADGRG1').
protein('ARRB1').
protein('MIR23A').
protein('NUP85').
protein('ATF1').
protein('GSDMB').
protein('ANGPTL8').
protein('TNNI3').
protein('RPP14').
protein('SUMO1').
protein('SIN3A').
protein('SUV39H1').
protein('HES1').
protein('CLIP1').
protein('BMP2').
protein('RASGRP1').
protein('CHGA').
protein('PAGR1').
protein('PEX19').
protein('PFN1').
protein('VASN').
protein('ABAT').
protein('MGRN1').
protein('RBFOX1').
protein('PDGFC').
protein('LOC100137897').
protein('MIR22').
protein('NOTCH3').
protein('PSMB10').
protein('KLF6').
protein('DLG2').
protein('LDLRAD3').
protein('SNHG15').
protein('PREP').
protein('TRPV6').
protein('CRH').
protein('BACH1').
protein('CD300E').
protein('USP2').
protein('CADM1').
protein('HOXB5').
protein('NPTX1').
protein('ULK1').
protein('CD63').
protein('PSMD12').
protein('GZMH').
protein('ICOSLG').
protein('RUVBL1').
protein('RUVBL2').
protein('SRCAP').
protein('LOC100136558').
protein('GALNS').
protein('CLEC5A').
protein('CLEC2D').
protein('FCGR2B').
protein('HSPB1').
protein('POU2F1').
protein('TDRD7').
protein('PNPT1').
protein('GLDC').
protein('SAMD9').
protein('SAMD9L').
protein('P/V/C').
protein('LOC103694545').
protein('SOX3').
protein('HIVEP2').
protein('PRAME').
protein('MAGED4').
protein('CD8B1').
protein('GAK').
protein('SRPRA').
protein('USO1').
protein('EBNA-1').
protein('ARHGAP45').
protein('KIR3DS1').
protein('MIR4319').
protein('SENP2').
protein('BTLA').
protein('CASR').
protein('MEX3B').
protein('PLAC1').
protein('PTP4A3').
protein('RGS2').
protein('RGS13').
protein('RGS16').
protein('NEAT1').
protein('TLR6').
protein('PLAAT2').
protein('PTN').
protein('BGN').
protein('NFATC3').
protein('ZFP148').
protein('CFP').
protein('BDKRB1').
protein('KNG1').
protein('IGKV2D-26').
protein('DMBT1').
protein('SMAD5').
protein('ACVRL1').
protein('KAT2A').
protein('PVALB').
protein('SYP').
protein('AKT3').
protein('RPS4X').
protein('RPS7').
protein('RPS27A').
protein('RPS13').
protein('RPS23').
protein('TULP3').
protein('GRB2').
protein('DOCK2').
protein('XRCC6').
protein('ETV4').
protein('IFITM10').
protein('ANGPTL3').
protein('SLC7A1').
protein('GHRH').
protein('CFL1').
protein('ASMT').
protein('LAIR2').
protein('JMJD1C').
protein('TFE3').
protein('TFEB').
protein('SPNS2').
protein('MAZ').
protein('APOC3').
protein('IRAK3').
protein('ACSM3').
protein('NOS1').
protein('INPP4B').
protein('ZNF480').
protein('RAP1A').
protein('OLFM4').
protein('MIAT').
protein('METTL3').
protein('RBPJ').
protein('GAG-POL').
protein('SPHK2').
protein('PXN').
protein('ARHGEF2').
protein('KCNN4').
protein('FOLR2').
protein('ELF5').
protein('IGHG2B').
protein('SNHG1').
protein('PRRX1').
protein('HPSE').
protein('ZFP189').
protein('CBLB').
protein('IGG').
protein('FAH').
protein('LOC641025').
protein('TAG').
protein('AP3D1').
protein('NONO').
protein('RORB').
protein('MAGEC3').
protein('FGFR1').
protein('KDM4D').
protein('RB1CC1').
protein('MGAT3').
protein('TMEM199').
protein('RAB11A').
protein('ARHGEF5').
protein('WDR82').
protein('UBA7').
protein('LSM14A').
protein('RNF149').
protein('ADORA2A').
protein('CSF2RB').
protein('ZMAT3').
protein('MIR132').
protein('MIR212').
protein('DEAF1').
protein('PELI1').
protein('NSD2').
protein('HIRA').
protein('H3-3B').
protein('MAGT1').
protein('MSTN').
protein('KAT2B').
protein('ARL5B').
protein('ELAVL1').
protein('PADI4').
protein('RNF11').
protein('IFI204').
protein('LOC107051710').
protein('DDX5').
protein('BEX1').
protein('MRE11').
protein('CELF1').
protein('NKX2-5').
protein('FABP2').
protein('SHH').
protein('COIL').
protein('ITGB7').
protein('SERPINA3G').
protein('MALT1').
protein('MAP3K1').
protein('GATA4').
protein('LCE3A').
protein('TNFRSF13C').
protein('TRERF1').
protein('SPAG9').
protein('ADAMTS12').
protein('IGF2BP2').
protein('LILRB2').
protein('IGHV1-62').
protein('LTC4S').
protein('HC').
protein('MIR146A').
protein('MIR146B').
protein('TSHR').
protein('CARS1').
protein('HOXA10').
protein('TRAV9-2').
protein('TRBV7-2').
protein('LOC100750601').
protein('LOC100769948').
protein('IGHJ2').
protein('RARB').
protein('IRX2').
protein('BCL10').
protein('NPY4R').
protein('HOXA9').
protein('MRTFA').
protein('MIR139').
protein('COX1').
protein('CDC25C').
protein('DAXX').
protein('FANCC').
protein('NCOA1').
protein('SLC27A2').
protein('DCTN1').
protein('EPS8').
protein('SPA17').
protein('FMR1NB').
protein('TMPRSS4').
protein('NACA2').
protein('CNMD').
protein('NPPC').
protein('NP').
protein('X').
protein('GULP1').
protein('LDHC').
protein('FCER2A').
protein('HLX').
protein('ACKR2').
protein('TWIST1').
protein('F5').
protein('DUSP26').
protein('SLC35B2').
protein('KHDRBS1').
protein('PLAT').
protein('PSEN2').
protein('ITGA6').
protein('MAP2K2').
protein('GNA12').
protein('PSME1').
protein('DDX60').
protein('BAG1').
protein('C1QTNF8').
protein('RXFP1').
protein('MPG').
protein('CAMK4').
protein('BRRF1').
protein('BTN2A1').
protein('BTN3A1').
protein('KLK8').
protein('PSAP').
protein('RACGAP1').
protein('GADD45GIP1').
protein('HOXA1').
protein('CYP21A1').
protein('BMPR2').
protein('PBSN').
protein('CAVIN1').
protein('CENPJ').
protein('IGFBP5').
protein('NDUFA13').
protein('DIRAS3').
protein('UBXN4').
protein('GAB2').
protein('PPP1R1B').
protein('TAZ').
protein('MIR211').
protein('MAP2').
protein('MIR31').
protein('STAP2').
protein('KLF5').
protein('EPAS1').
protein('HOP').
protein('NEDD4L').
protein('CDC25A').
protein('GSTM1').
protein('TNC').
protein('EEF1A2').
protein('MIXL1').
protein('WNT3A').
protein('ADRA1D').
protein('CASPA').
protein('BISPR').
protein('CA14').
protein('STATH').
protein('GAD2').
protein('NMNAT2').
protein('NLRP7').
protein('RBP3').
protein('GINS4').
protein('VCL').
protein('AGAP3').
protein('SEA').
protein('CAP1').
protein('ASZ1').
protein('RCAN1').
protein('APOF').
protein('KMT5AP1').
protein('CTHRC1').
protein('CD180').
protein('AREG').
protein('SLC22A1').
protein('BCLAF1').
protein('ZNF804A').
protein('LIAS').
protein('FPR1').
protein('ZNF350').
protein('MAPKAPK3').
protein('RRAGB').
protein('STS').
protein('IFNG-AS1').
protein('TSPO').
protein('LCP2').
protein('H4C6').
protein('IFNGAS1').
protein('PPP3R1').
protein('DRAM1').
protein('BHLHE40').
protein('UBD').
protein('LUM').
protein('DCN').
protein('RAMP3').
protein('NCAM2').
protein('FASL').
protein('CDSN').
protein('PRKG1').
protein('TRIM26').
protein('TAS1R1').
protein('CIB1').
protein('CIB2').
protein('LAP').
protein('MIR107').
protein('SGK1').
protein('CXORF21').
protein('NFE2').
protein('HBZ').
protein('MGAT5').
protein('AGMO').
protein('PF3D7_1133400').
protein('IGHD5-12').
protein('ATP7A').
protein('SLC31A1').
protein('CD6').
protein('MET').
protein('DEF6').
protein('KLRG1').
protein('IGFBP2').
protein('RBCK1').
protein('TRPA1').
protein('MIR18A').
protein('NVGP2').
protein('NFASC').
protein('TNFRSF21').
protein('MADCAM1').
protein('IGF2BP1').
protein('YTHDF1').
protein('METTL14').
protein('ALKBH5').
protein('MIR21A').
protein('LYNX1').
protein('BIRC2').
protein('HOTAIR').
protein('HOXC11').
protein('HOXC12').
protein('INSIG1').
protein('NEK7').
protein('PGGT1B').
protein('UBAP1').
protein('SLC22A12').
protein('VDAC1').
protein('ELF4').
protein('FHL1').
protein('GNA15').
protein('GNA14').
protein('HMGA1').
protein('VPU').
protein('SIM2').
protein('CYCSP25').
protein('ASPH').
protein('RNU11').
protein('RAB5A').
protein('HFE').
protein('UL9').
protein('CNTN2').
protein('VIRF-2').
protein('PTMAP9').
protein('SMR3A').
protein('VP24').
protein('ORF7B').
protein('PPP1CA').
protein('SPECC1').
protein('MBL3P').
protein('TRIM4').
protein('CTTNBP2').
protein('CWC15').
protein('RAE1/GLE2').
protein('GIGYF2').
protein('SNX9').
protein('ARID3A').
protein('MIR302A').
protein('MIR302C').
protein('PRPF19').
protein('CUL4B').
protein('HSP84-3').
protein('MAGOH').
protein('IPO13').
protein('NUAK1').
protein('KLF2').
protein('HBE1').
protein('MAPK11').
protein('SKI').
protein('KLRF2').
protein('JAK-1').
protein('PFKP').
protein('DSCAM').
protein('RRM2').
protein('PRDX5').
protein('ABL2').
protein('SARM1').
protein('KPNA5').
protein('CUX1').
protein('PLTP').
protein('RSPO4').
protein('SMARCC1').
protein('THRA').
protein('TRRAP').
protein('FAF1').
protein('FGF1').
protein('UBE2I').
protein('KPNA7').
protein('PSPC1').
protein('GAS6').
protein('PLSCR4').
protein('EIF1').
protein('STK24').
protein('MSI1').
protein('CDCA2').
protein('TFF3').
protein('NOSIP').
protein('RPS2').
protein('MIR4255').
protein('TRIP13').
protein('SUMO3').
protein('NUP50').
protein('DDX56').
protein('PHF6').
protein('STK4').
protein('NFAT5').
protein('FAT1').
protein('KLF13').
protein('ANG2').
protein('SOD3').
protein('DAPK3').
protein('PYY').
protein('RTN4').
protein('FSTL1').
protein('THRIL').
protein('MIR137').
protein('CAPN3').
protein('NBN').
protein('BAG6').
protein('AQP1').
protein('RNF19B').
protein('FER').
protein('ZFP335').
protein('FYB').
protein('CA9').
protein('ARNT').
protein('ID3').
protein('I-AG7').
protein('TRAV12-2').
protein('ST3GAL2').
protein('SIGLECF').
protein('C6L').
protein('CXCL14').
protein('HIC1').
protein('CDK8').
protein('TRIM59').
protein('MIR30A').
protein('GBP2B').
protein('ABCG1').
protein('SUMO2').
protein('IFRD1').
protein('MTMR2').
protein('TAC2').
protein('CLDN10').
protein('CYP3A4').
protein('MIR302B').
protein('GBP3').
protein('PTDSS1').
protein('CTF1').
protein('SH2B2').
protein('SHB').
protein('MCM3AP').
protein('CD109').
protein('WC1').
protein('VP40').
protein('TFAP2C').
protein('SOX17').
protein('CDH4').
protein('EFNB3').
protein('SEMA6B').
protein('SLC35A2').
protein('DLD').
protein('RNF130').
protein('GABPB1').
protein('FNDC4').
protein('EIF4G2').
protein('SOX21-AS1').
protein('SOX21').
protein('USP10').
protein('SOX11').
protein('HBEGF').
protein('OLFR1386').
protein('TCF12').
protein('MIR494').
protein('MIR663A').
protein('PSMA3').
protein('GNA13').
protein('NPR1').
protein('ID1').
protein('LIMK1').
protein('NFATC4').
protein('DDIT4').
protein('PCX').
protein('HEATR6').
protein('RAB7A').
protein('TPBG').
protein('CITED2').
protein('MMP15').
protein('CTTN').
protein('JAG1').
protein('GP').
protein('BCL2L12').
protein('REG4').
protein('RPL23A').
protein('VIRF-1').
protein('TGM1').
protein('C2').
protein('B18R').
protein('E3L').
protein('MAP2K6').
protein('GPD1').
protein('TRIM13').
protein('AIP').
protein('RNF5').
protein('TET3').
protein('PPP4C').
protein('PPP4R3B').
protein('GRASP').
protein('SMIM24').
protein('LCP1').
protein('SERPINB6').
protein('MIR148A').
protein('LRP2').
protein('GPER1').
protein('BA1').
protein('HCNV63GP2').
protein('CFHR1').
protein('PPP2CA').
protein('HSD3B1').
protein('ELMO1').
protein('SCNN1A').
protein('MIR340').
protein('MIR429').
protein('GDI2').
protein('SAT1').
protein('RPL17').
protein('GTPBP1').
protein('PDCD5').
protein('TBX1').
protein('GNAI1').
protein('MIR924HG').
protein('ABCB11').
protein('ANK3').
protein('RFX5').
protein('OGN').
protein('CHGB').
protein('ZDHHC21').
protein('RHEB').
protein('ZFYVE1').
protein('MYO18B').
protein('MIR520G').
protein('CPEB3').
protein('RRM1').
protein('POU3F1').
protein('ASH2L').
protein('ARRB2').
protein('DDX19A').
protein('LAT').
protein('RNF39').
protein('ZNRD1').
protein('TXN').
protein('PRAF2').
protein('SOX6').
protein('PAX3').
protein('SOX18').
protein('SOX8').
protein('BMI1').
protein('HIF3A').
protein('TOLLIP').
protein('UL38').
protein('TNXB').
protein('UL36').
protein('ABCF1').
protein('SLC12A5').
protein('ENO1').
protein('FLNA').
protein('KNTC1').
protein('AGTR1B').
protein('TCEAL1').
protein('RAB2A').
protein('RAPGEF1').
protein('CNTFR').
protein('IFNGR1L').
protein('SLC19A1').
protein('MDC1').
protein('ADAM22').
protein('TCIRG1').
protein('CGB5').
protein('PHYH').
protein('IDDM2').
protein('UGT1A6').
protein('RPL31').
protein('KIR2DL5B').
protein('BCL11B').
protein('SLAMF9').
protein('ERVK-16').
protein('PSME2').
protein('ABCC1').
protein('CPQ').
protein('RNF113A').
protein('MIR197').
protein('DUX4').
protein('MEG3').
protein('STAG3').
protein('MST1R').
protein('MMRN2').
protein('TCN1').
protein('DCLK3').
protein('MIR1269A').
protein('PCDHGA9').
protein('DHX36').
protein('SCFV').
protein('EIF4E2').
protein('USP26').
protein('JPH2').
protein('TRIM65').
protein('DDX20').
protein('TRIM56').
protein('DNAJA3').
protein('TM9SF2').
protein('DDX21').
protein('TRIM38').
protein('BSRF1').
protein('SNORA65').
protein('SLC9A9').
protein('DDX27').
protein('EFTUD2').
protein('EFNB1').
protein('DAB2IP').
protein('S100A6').
protein('GHRL').
protein('MIR7K').
protein('GM46612').
protein('MAPKAP1').
protein('PATJ').
protein('PRR5').
protein('PRR5L').
protein('SH3GLB1').
protein('UVRAG').
protein('PRKCG').
protein('FKBP1AP1').
protein('GOSR1').
protein('TSC22D3').
protein('MXI1').
protein('CDC37').
protein('MKNK2').
protein('EBNA3A').
protein('BZW1').
protein('BZW2').
protein('MRGPRF').
protein('P2RX5').
protein('MLLT3').
protein('CYP4F3').
protein('BKPYVGP4').
protein('BW64').
protein('IDD5').
protein('TWF1').
protein('H15').
protein('EGFL1').
protein('APOH').
protein('GHITM').
protein('LOC100034197').
protein('HHV8GK18_GP81').
protein('CCDC66').
protein('TSPAN8').
protein('TIMD4').
protein('HAUS3').
protein('UTP25').
protein('GCNT1').
protein('CD164').
protein('UL27').
protein('COL12A1').
protein('CDC20').
protein('GPR83').
protein('VACA').
protein('MIER1').
protein('FGF23').
protein('LY6').
protein('CST3').
protein('MIR26A-1').
protein('LRRC32').
protein('UHRF1').
protein('TNFAIP8L2').
protein('OPRK1').
protein('PDCD10').
protein('STK26').
protein('MOB4').
protein('PPP2R1B').
protein('STRN3').
protein('STRIP1').
protein('LOC101055843').
protein('PLIN3').
protein('CDCP1').
protein('MMP10').
protein('UL111A').
protein('US27').
protein('MIR495').
protein('PDLIM2').
protein('DBI').
protein('DRD5').
protein('GAP43').
protein('ARIH1').
protein('VCP').
protein('NTRK1').
protein('ZNF467').
protein('IGKV2D-24').
protein('AZF1').
protein('ZMYM2').
protein('PNRC1').
protein('NMI').
protein('ELF3').
protein('TFG').
protein('SLC4A2').
protein('PCLAF').
protein('RECQL').
protein('PDIA2').
protein('ENOSF1').
protein('THBS4').
protein('PER2').
protein('PDE8A').
protein('ORC2').
protein('ECI1').
protein('GUSBP14').
protein('SH3BGR').
protein('OSBPL8').
protein('PPP6R2').
protein('GATD3A').
protein('TRAPPC6A').
protein('CAMTA1').
protein('SLC38A2').
protein('MIR718').
protein('PLSCR2').
protein('KLF12').
protein('ARID4B').
protein('ARID3C').
protein('QKI').
protein('GLIS2').
protein('TAF11').
protein('NORAD').
protein('SULT1A1').
protein('PLA2G7').
protein('RLN2').
protein('SDC3').
protein('RORA-AS1').
protein('PAX6').
protein('DDR1').
protein('LOC100521667').
protein('ATG4C').
protein('ATG9B').
protein('BLOC1S6').
protein('BLOC1S1').
protein('DAB2').
protein('PRDX6-PS2').
protein('ZNF460').
protein('ZFAS1').
protein('CMTM2A').
protein('CD244A').
protein('ICL1').
protein('IL1F10').
protein('RASA1').
protein('TRIM58').
protein('ADAM9').
protein('UL148A').
protein('PGLYRP1').
protein('RFXANK').
protein('US9').
protein('UL147A').
protein('LINC01149').
protein('HOXB4').
protein('GP5').
protein('MRX50').
protein('SYN2').
protein('CYP21A2').
protein('L1CAM').
protein('LDHB').
protein('B125R').
protein('BCORL1').
protein('CALCRL').
protein('ASAH1').
protein('MIR1295A').
protein('MSX1').
protein('USP6').
protein('SLA-DQB1').
protein('CHRM3').
protein('PPM1K').
protein('BGLF2').
protein('CHD6').
protein('SMCHD1').
protein('USP5').
protein('PROC').
protein('ARID2').
protein('MIR10B').
protein('IAC').
protein('CPA1').
protein('S100P').
protein('ERVV-2').
protein('C1S1').
protein('NAT9').
protein('CTR9').
protein('MEOX1').
protein('PDK4').
protein('GDE1').
protein('HHEX').
protein('GCM1').
protein('OVOL1').
protein('PDZRN3').
protein('DNM3B').
protein('QSOX2').
protein('DMRT1').
protein('OLAH').
protein('SH2').
protein('NRG4').
protein('LPCAT2').
protein('DERL1').
protein('GTF2I').
protein('RBM25').
protein('DPPA3').
protein('EPB41').
protein('KLRA1P').
protein('DYRK1B').
protein('MIR106A').
protein('MIR20B').
protein('MIR93').
protein('MIR711').
protein('MIR193A').
protein('MIR548C').
protein('ADAM12').
protein('CD1').
protein('I7L').
protein('AGFG1').
protein('CDK14').
protein('KLF9').
protein('UCHL5').
protein('TOPORS').
protein('MIR183').
protein('P4HB').
protein('LINC-ROR').
protein('ERVK-13').
protein('CABP4').
protein('KCNJ10').
protein('NLRP2').
protein('MIR4325').
protein('IL1F8').
protein('FEN1').
protein('SPAG6').
protein('NAA60').
protein('H2BS1').
protein('MIR7705').
protein('UBE2E1').
protein('CCNG2').
protein('FBXO40').
protein('SIGLECH').
protein('PDE4D').
protein('FAM210B').
protein('FBN2').
protein('DPP').
protein('SAX').
protein('ACTBETA').
protein('BMPR1A').
protein('FGFR3').
protein('PRSS1').
protein('PCAT29').
protein('FREM1').
protein('SDK1').
protein('RPE65').
protein('LGALS4').
protein('PLOD2').
protein('CDH11').
protein('HAS2').
protein('SIT1').
protein('NRIR').
protein('F8').
protein('ADAM15').
protein('PROK2').
protein('RAB27A').
protein('BANP').
protein('NPS').
protein('UBXN6').
protein('UL23').
protein('FOXK1').
protein('MSRB2').
protein('A104R').
protein('SIGMA-A').
protein('NCOA3').
protein('LINC-PINT').
protein('CALCB').
protein('S100A14').
protein('LOC108348108').
protein('MAFA').
protein('RBM47').
protein('VGLL3').
protein('NUMB').
protein('LNX2').
protein('LNX1').
protein('TREML4').
protein('RAB43').
protein('HSD17B10').
protein('GUCY2C').
protein('RARRES2').
protein('SUCLA2').
protein('PICK1').
protein('RFPL3').
protein('MIR652').
protein('MIR4772').
protein('MIR192').
protein('TP53INP2').
protein('MIR1291').
protein('H4C8').
protein('H4C9').
protein('H4C12').
protein('MTHFD2').
protein('TUBA4A').
protein('TUBB1').
protein('RPS26').
protein('TFDP3').
protein('TRAV8-3').
protein('MC5R').
protein('TNP2').
protein('SYNPO2').
protein('POLE3').
protein('HMG20A').
protein('MIR590').
protein('ELAC1').
protein('JUP').
protein('LOC770612').
protein('MIR34C').
protein('ZDHHC3').
protein('ZDHHC7').
protein('TRAM1').
protein('ZNF382').
