base([
event('NR1H4',inhibit,'NR1H4'),
event('NR1H4',inhibit,'NR0B2'),
event('NR1H4',reveal,'RXR'),
event('NR1H4',reveal,'NR1H4'),
event('RXR',inhibit,'NR1H4'),
event('NR1H4',enhance,'RXR'),
event('NR1H4',enhance,'NR1H4'),
event('NR1H4',induce,'BAAT'),
event('NR1H4',induce,'bile acid'),
event('BAAT',reveal,'BAAT'),
event('BAAT',mediate,'RXR'),
event('BAAT',mediate,'NR1H4'),
event('BAAT',increase,'NR1H4'),
event('RXR',bind,'RXR'),
event('RXR',reveal,'RXR'),
event('RXR',translate,'RXR'),
event('BAAT',enhance,'BAAT'),
event('BAAT',involve,'NR1H2'),
event('CYP7A1',involve,'NR1H2'),
event('NR0B2',involve,'NR1H2'),
event('NR1H4',control,'BAAT'),
event('NR1H4',control,'CYP7A1'),
event('bile acid',regulate,'BAAT'),
event('bile acid',regulate,'CYP7A1'),
event('NR1H4',regulate,'BAAT'),
event('NR1H4',regulate,'CYP7A1'),
event('NR1H4',increase,'bile acid'),
event('BAAT',relate,'bile acid'),
event('NR1H4',relate,'bile acid'),
event('NR0B2',relate,'bile acid'),
event('BAAT',relate,'CYP7A1'),
event('NR1H4',relate,'CYP7A1'),
event('NR0B2',relate,'CYP7A1'),
event('NR1H4',detect,'BAAT'),
event('NR1H4',detect,'bile acid'),
event('NR1H4',detect,'CYP7A1'),
event('NR1H4',detect,'NR1H4'),
event('NR1H4',detect,'NR0B2'),
event('NR1H4',increase,'BAAT'),
event('NR1H4',increase,'CYP7A1'),
event('NR1H4',increase,'NR1H4'),
event('NR1H4',increase,'NR0B2'),
event('NR0B2',increase,'NR0B2'),
event('NR0B2',inhibit,'BAAT'),
event('NR5A2',increase,'CYP7A1'),
event('NR0B2',increase,'CYP7A1'),
event('NR5A2',decrease,'CYP7A1'),
event('NR5A2',decrease,'NR1H4'),
event('NR5A2',decrease,'NR0B2'),
event('BAAT',increase,'bile acid'),
event('BAAT',increase,'CYP7A1'),
event('bile acid',induce,'BAAT'),
event('CYP7A1',induce,'BAAT'),
event('MDFIC',express,'BAAT'),
event('BAAT',increase,'MDFIC'),
event('NR1H4',increase,'MDFIC'),
event('BAAT',involve,'NR1H4'),
event('NR1H2',involve,'NR1H4'),
event('MDFIC',involve,'NR1H4'),
event('NR1H2',control,'NR1H2'),
event('NR1H2',increase,'NR1H2'),
event('bile acid',enhance,'CYP7A1'),
event('NR1H2',target,'CYP7A1'),
event('NR1H3',target,'CYP7A1'),
event('NR1H4',target,'CYP7A1'),
event('NR1H2',control,'MDFIC'),
event('NR1H2',modulate,'NR1H2'),
event('NR1H2',target,'NR1H2'),
event('NR1H2',support,'NR1H2'),
event('NR1H2',fall,'RXR'),
event('NR1H2',bind,'NR1H2'),
event('NR1H2',bind,'CYP7A1'),
event('NR1H2',decrease,'NR1H2'),
event('NR1H2',decrease,'CYP7A1'),
event('NR1H2',inhibit,'NR1H2'),
event('NR1H2',involve,'NR1H2'),
event('NR1H2',enhance,'NR1H2'),
event('NR1H2',associate,'NR1H2'),
event('BAAT',affect,'NR1H2'),
event('oxysterols',induce,'NR1H3'),
event('MDFIC',bind,'NR1H3'),
event('NR1H3',suppress,'MDFIC'),
event('MDFIC',induce,'NR1H3'),
event('MDFIC',activate,'NR1H3'),
event('MDFIC',target,'NR1H2'),
event('NR1H2',enhance,'NR1H3'),
event('NR1H2',enhance,'MDFIC'),
event('NR1H2',reduce,'NR1H2'),
event('NR1H2',reduce,'NR1H3'),
event('NR1H2',target,'NR1H3'),
event('NR1H3',target,'NR1H2'),
event('NR1H3',target,'NR1H3'),
event('NR1H2',participate,'NR1H2'),
event('CHROMR',mediate,'NR1H2'),
event('CHROMR',mediate,'NR1H3'),
event('NR1H2',mediate,'NR1H2'),
event('NR1H2',mediate,'NR1H3'),
event('NR1H2',decrease,'NR1H3'),
event('NR1H3',change,'NR1H2'),
event('NR1H3',change,'NR1H3'),
event('NR1H2',induce,'NR1H2'),
event('NR1H2',regulate,'NR1H2'),
event('oxysterols',activate,'NR1H2'),
event('NR1H2',regulate,'RXR'),
event('NR1H3',regulate,'RXR'),
event('NR1H2',bind,'RXR'),
event('NR1H3',bind,'RXR'),
event('RXR',associate,'NR1H2'),
event('RXR',associate,'NR1H3'),
event('NR1H2',target,'RXR'),
event('NR1H3',target,'RXR'),
event('oxysterols',increase,'NR1H2'),
event('NR1H3',increase,'NR1H2'),
event('NR1H2',activate,'NR1H2'),
event('NR1H3',activate,'NR1H2'),
event('NR1H2',activate,'NR1H3'),
event('NR1H3',activate,'NR1H3'),
event('NR1H2',activate,'MDFIC'),
event('NR1H3',activate,'MDFIC'),
event('NR1H3',inhibit,'NR1H2'),
event('NR1H2',inhibit,'NR1H3'),
event('NR1H3',inhibit,'NR1H3'),
event('NR1H3',mediate,'NR1H2'),
event('NR1H3',mediate,'NR1H3'),
event('MDFIC',increase,'NR1H2'),
event('NR1H2',promote,'NR1H2'),
event('MDFIC',bind,'RXR'),
event('NR1H2',induce,'RXR'),
event('NR1H2',activate,'RXR'),
event('NR1H2',lead,'NR1H2'),
event('NR1H3',lead,'NR1H2'),
event('NR1H2',lead,'NR1H3'),
event('NR1H3',lead,'NR1H3'),
event('NR1H2',lead,'MDFIC'),
event('NR1H3',lead,'MDFIC'),
event('CYP7A1',bind,'NR1H2'),
event('CYP7A1',bind,'NR1H3'),
event('NR1H3',regulate,'NR1H2'),
event('MDFIC',regulate,'NR1H2'),
event('NR1H2',stimulate,'NR1H2'),
event('NR1H2',express,'NR1H2'),
event('NR1H2',express,'NR1H3'),
event('NR1H3',express,'NR1H2'),
event('NR1H3',express,'NR1H3'),
event('MDFIC',bind,'NR1H2'),
event('MDFIC',activate,'NR1H2'),
event('NR1H3',bind,'NR1H2'),
event('NR1H3',reduce,'NR1H2'),
event('NR1H3',reduce,'NR1H3'),
event('NR1H2',prevent,'NR1H2'),
event('NR1H2',prevent,'NR1H3'),
event('NR1H2',bind,'NR1H3'),
event('NR1H3',bind,'NR1H3'),
event('NR1H2',increase,'NR1H3'),
event('NR1H3',associate,'NR1H2'),
event('NR1H2',associate,'NR1H3'),
event('NR1H3',associate,'NR1H3'),
event('NR1H3',induce,'NR1H2'),
event('NR1H2',induce,'NR1H3'),
event('NR1H3',induce,'NR1H3'),
event('NR1H2',regulate,'NR1H3'),
event('NR1H3',regulate,'NR1H3'),
event('NR1H2',involve,'oxysterols'),
event('NR1H2',increase,'MDFIC'),
event('NR1H3',control,'NR1H2'),
event('oxysterols',bind,'NR1H2'),
event('oxysterols',bind,'RXR'),
event('NR1H2',stimulate,'NR1H3'),
event('NR1H2',stimulate,'RXR'),
event('RXR',activate,'NR1H2'),
event('MDFIC',develop,'NR1H2'),
event('MDFIC',affect,'NR1H2'),
event('oxysterols',regulate,'NR1H2'),
event('NR1H2',affect,'NR1H2'),
event('NR1H3',affect,'NR1H2'),
event('NR1H2',affect,'NR1H3'),
event('NR1H3',affect,'NR1H3'),
event('NR1H2',increase,'oxysterols'),
event('NR1H2',reveal,'NR1H2'),
event('NR1H2',relate,'NR1H2'),
event('NR1H2',require,'NR1H2'),
event('NR1H2',regulate,'MDFIC'),
event('NR1H2',modulate,'MDFIC'),
event('RXR',modulate,'MDFIC'),
event('oxysterols',limit,'NR1H2'),
event('RXR',reduce,'NR1H2'),
event('NR1H2',interact,'NR1H2'),
event('RXR',increase,'NR1H2'),
event('CYP7A1',suppress,'CYP7A1'),
event('CYP7A1',target,'CYP7A1'),
event('CYP7A1',induce,'CYP7A1'),
event('NR1H2',suppress,'CYP7A1'),
event('NR1H3',suppress,'CYP7A1'),
event('NR1H2',inhibit,'CYP7A1'),
event('NR1H3',inhibit,'CYP7A1'),
event('NR1H3',decrease,'NR1H2'),
event('NR1H3',decrease,'NR1H3'),
event('NR1H2',associate,'MDFIC'),
event('NR1H2',increase,'CYP7A1'),
event('MDFIC',decrease,'NR1H2'),
event('NR1H2',enhance,'bile acid'),
event('CYP7A1',enhance,'bile acid'),
event('NR1H2',suppress,'NR1H2'),
event('NR1H2',detect,'NR1H2'),
event('CYP7A1',activate,'NR1H2'),
event('CYP7A1',activate,'NR1H4'),
event('NR1H2',support,'MDFIC'),
event('MDFIC',reduce,'NR1H2'),
event('MDFIC',express,'NR1H2'),
event('NR1H2',bind,'NR0B2'),
event('NR1H4',bind,'NR0B2'),
event('NR1H2',associate,'NR1H4'),
event('NR1H2',increase,'NR1H4'),
event('RXR',interact,'RXR'),
event('oxysterols',inhibit,'NR1H2'),
event('oxysterols',involve,'NR1H2'),
event('MDFIC',involve,'NR1H2'),
event('NR1H2',mediate,'oxysterols'),
event('MDFIC',suppress,'CYP7A1'),
event('MDFIC',lead,'CYP7A1'),
event('RXR',involve,'MDFIC'),
event('NR1H2',change,'NR1H3'),
event('NR1H2',involve,'RXR'),
event('NR1H2',antagonize,'NR1H2'),
event('RXR',activate,'RXR'),
event('NR1H2',limit,'NR1H2'),
event('RXR',mediate,'MDFIC'),
event('NR1H3',reveal,'NR1H2'),
event('NR1H2',require,'NR1H3'),
event('NR1H2',lead,'RXR'),
event('NR1H3',lead,'RXR'),
event('RXR',lead,'NR1H2'),
event('RXR',lead,'RXR'),
event('RXR',bind,'NR1H2'),
event('NR1H2',support,'RXR'),
event('NR1H2',support,'NR1H3'),
event('MDFIC',promote,'NR1H2'),
event('NR1H2',heterodimerize,'RXR'),
event('NR1H3',involve,'NR1H2'),
event('NR1H2',change,'NR1H2'),
event('bile acid',activate,'NR1H2'),
event('RXR',regulate,'NR1H2'),
event('RXR',regulate,'RXR'),
event('RXR',support,'NR1H2'),
event('CYP7A1',increase,'NR1H2'),
event('NR1H3',enhance,'NR1H2'),
event('NR1H3',enhance,'NR1H3'),
event('MDFIC',enhance,'NR1H2'),
event('MDFIC',enhance,'NR1H3'),
event('NR1H3',increase,'NR1H3'),
event('NR5A2',express,'NR5A2'),
event('CYP7A1',activate,'NR5A2'),
event('NR0B2',activate,'NR5A2'),
event('NR1H2',activate,'NR5A2'),
event('NR5A2',activate,'NR5A2'),
event('RXR',activate,'NR5A2'),
event('NR1H2',suppress,'NR1H3'),
event('NR1H3',suppress,'NR1H2'),
event('NR1H3',suppress,'NR1H3'),
event('oxysterols',modulate,'NR1H2'),
event('CYP7A1',regulate,'MDFIC'),
event('NR1H2',regulate,'CYP7A1'),
event('CYP7A1',regulate,'CYP7A1'),
event('NR1H3',regulate,'CYP7A1'),
event('MDFIC',regulate,'CYP7A1'),
event('NR1H2',target,'NR1H4'),
event('NR0B2',target,'NR1H2'),
event('NR0B2',target,'NR1H3'),
event('NR0B2',target,'NR1H4'),
event('NR1H4',target,'NR1H2'),
event('NR1H4',target,'NR1H3'),
event('NR1H3',increase,'oxysterols'),
event('oxysterols',activate,'NR1H3'),
event('NR0B2',increase,'bile acid'),
event('NR1H4',activate,'NR1H2'),
event('CYP7A1',activate,'NR1H3'),
event('NR1H4',activate,'NR1H3'),
event('NR1H4',induce,'NR1H2'),
event('NR1H4',induce,'CYP7A1'),
event('NR1H4',induce,'NR1H3'),
event('NR1H2',activate,'bile acid'),
event('CYP7A1',activate,'bile acid'),
event('NR1H3',activate,'bile acid'),
event('NR1H4',activate,'bile acid'),
event('CYP7A1',activate,'MDFIC'),
event('NR1H4',activate,'MDFIC'),
event('NR1H4',control,'bile acid'),
event('NR1H3',regulate,'MDFIC'),
event('NR1H3',increase,'MDFIC'),
event('NR1H2',stimulate,'BAAT'),
event('NR1H4',stimulate,'BAAT'),
event('NR1H2',bind,'NR1H4'),
event('NR1H2',recognize,'NR1H4'),
event('RXR',recognize,'NR1H4'),
event('NR1H2',mediate,'MDFIC'),
event('RXR',interact,'NR1H2'),
event('NR1H2',relate,'MDFIC'),
event('NR1H2',suppress,'RXR'),
event('NR1H4',bind,'NR1H2'),
event('NR1H2',prevent,'NR1H4'),
event('NR1H2',enhance,'NR1H4'),
event('MDFIC',bind,'NR1H4'),
event('NR1H2',develop,'NR1H2'),
event('NR1H2',raise,'NR1H2'),
event('MDFIC',require,'NR1H2'),
event('NR1H2',control,'RXR'),
event('NR1H2',control,'NR1H4'),
event('RXR',control,'RXR'),
event('RXR',control,'NR1H4'),
event('NR0B2',require,'NR1H2'),
event('NR0B2',require,'NR0B2'),
event('NR1H2',inhibit,'NR0B2'),
event('NR0B2',inhibit,'NR0B2'),
event('MDFIC',inhibit,'NR1H2'),
event('NR1H2',regulate,'NR0B2'),
event('NR1H4',regulate,'NR0B2'),
event('NR0B2',lead,'CYP7A1'),
event('CYP7A1',target,'NR1H2'),
event('oxysterols',induce,'NR1H2'),
event('MDFIC',stimulate,'NR1H2'),
event('NR1H3',support,'NR1H2'),
event('RXR',reveal,'NR1H2'),
event('NR1H2',reveal,'NR1H3'),
event('RXR',reveal,'NR1H3'),
event('NR1H4',regulate,'NR1H2'),
event('NR1H4',regulate,'NR1H3'),
event('MDFIC',regulate,'NR1H3'),
event('NR1H4',target,'NR1H4'),
event('NR1H4',affect,'NR1H4'),
event('NR1H3',induce,'RXR'),
event('NR1H3',stimulate,'NR1H2'),
event('NR1H3',stimulate,'RXR'),
event('bile acid',inhibit,'CYP7A1'),
event('NR1H4',inhibit,'CYP7A1'),
event('CYP7A1',stimulate,'NR1H2'),
event('CYP7A1',stimulate,'NR1H3'),
event('CYP7A1',stimulate,'RXR'),
event('bile acid',bind,'NR1H2'),
event('bile acid',bind,'NR1H3'),
event('oxysterols',regulate,'NR1H3'),
event('NR1H2',reduce,'oxysterols'),
event('NR1H3',reduce,'oxysterols'),
event('oxysterols',target,'NR1H2'),
event('oxysterols',express,'NR1H2'),
event('bile acid',bind,'NR5A2'),
event('NR1H2',regulate,'bile acid'),
event('NR1H3',regulate,'bile acid'),
event('bile acid',activate,'NR1H4'),
event('NR1H4',inhibit,'NR1H2'),
event('NR1H2',regulate,'oxysterols'),
event('NR1H2',induce,'CYP7A1'),
event('NR1H3',require,'NR1H2'),
event('NR1H3',require,'NR1H3'),
event('BAAT',increase,'NR1H2'),
event('NR1H2',express,'oxysterols'),
event('NR1H2',express,'MDFIC'),
event('NR1H2',activate,'oxysterols'),
event('NR1H3',relate,'MDFIC'),
event('NR1H3',stimulate,'NR1H3'),
event('NR1H3',reveal,'NR1H3'),
event('NR1H2',reduce,'bile acid'),
event('CYP7A1',lead,'NR1H2'),
event('CYP7A1',lead,'NR1H3'),
event('MDFIC',lead,'NR1H2'),
event('MDFIC',lead,'NR1H3'),
event('NR1H3',increase,'CYP7A1'),
event('NR1H2',induce,'oxysterols'),
event('NR1H2',target,'oxysterols'),
event('NR0B2',increase,'MDFIC'),
event('NR1H4',decrease,'MDFIC'),
event('NR0B2',decrease,'MDFIC'),
event('NR1H2',decrease,'MDFIC'),
event('MDFIC',increase,'NR1H3'),
event('MDFIC',increase,'NR1H4'),
event('MDFIC',decrease,'NR1H3'),
event('MDFIC',decrease,'NR1H4'),
event('NR1H2',recognize,'NR1H2'),
event('NR1H3',recognize,'NR1H2'),
event('NR1H2',fall,'NR1H2'),
event('NR1H2',retain,'NR1H2'),
event('NR1H3',prevent,'NR1H2'),
event('NR1H2',involve,'NR1H3'),
event('MDFIC',involve,'RXR'),
event('NR1H2',target,'NR0B2'),
event('NR1H4',target,'NR0B2'),
event('NR1H4',regulate,'bile acid'),
event('NR1H4',induce,'NR1H4'),
event('NR1H4',bind,'NR1H4'),
event('NR1H2',mediate,'NR1H4'),
event('CYP7A1',mediate,'NR1H4'),
event('NR1H2',reduce,'CYP7A1'),
event('CYP7A1',reduce,'CYP7A1'),
event('NR1H3',reduce,'CYP7A1'),
event('CYP7A1',bind,'CYP7A1'),
event('NR1H3',bind,'CYP7A1'),
event('MDFIC',bind,'CYP7A1'),
event('NR1H3',involve,'NR1H3'),
event('CYP7A1',decrease,'bile acid'),
event('bile acid',induce,'NR1H2'),
event('bile acid',induce,'CYP7A1'),
event('bile acid',induce,'NR5A2'),
event('bile acid',induce,'RXR'),
event('bile acid',induce,'NR0B2'),
event('CYP7A1',induce,'NR1H2'),
event('CYP7A1',induce,'NR5A2'),
event('CYP7A1',induce,'RXR'),
event('CYP7A1',induce,'NR0B2'),
event('RXR',induce,'NR1H2'),
event('RXR',induce,'CYP7A1'),
event('RXR',induce,'NR5A2'),
event('RXR',induce,'RXR'),
event('RXR',induce,'NR0B2'),
event('NR1H4',induce,'NR5A2'),
event('NR1H4',induce,'RXR'),
event('NR1H4',induce,'NR0B2'),
event('bile acid',inhibit,'NR1H2'),
event('bile acid',inhibit,'NR5A2'),
event('bile acid',inhibit,'RXR'),
event('CYP7A1',inhibit,'NR1H2'),
event('CYP7A1',inhibit,'CYP7A1'),
event('CYP7A1',inhibit,'NR5A2'),
event('CYP7A1',inhibit,'RXR'),
event('RXR',inhibit,'NR1H2'),
event('RXR',inhibit,'CYP7A1'),
event('RXR',inhibit,'NR5A2'),
event('RXR',inhibit,'RXR'),
event('NR1H4',inhibit,'NR5A2'),
event('NR1H4',inhibit,'RXR'),
event('NR0B2',inhibit,'NR1H2'),
event('NR0B2',inhibit,'CYP7A1'),
event('NR0B2',inhibit,'NR5A2'),
event('NR0B2',inhibit,'RXR'),
event('MDFIC',inhibit,'CYP7A1'),
event('MDFIC',inhibit,'NR5A2'),
event('MDFIC',inhibit,'RXR'),
event('NR5A2',bind,'NR5A2'),
event('RXR',target,'NR1H2'),
event('RXR',target,'RXR'),
event('NR1H2',detect,'RXR'),
event('MDFIC',dimerize,'RXR'),
event('NR1H2',recognize,'CYP7A1'),
event('CYP7A1',recognize,'CYP7A1'),
event('CYP7A1',increase,'bile acid'),
event('CYP7A1',increase,'NR1H4'),
event('NR1H2',release,'MDFIC'),
event('NR1H2',induce,'MDFIC'),
event('NR1H2',inhibit,'NR1H4'),
event('NR1H2',interact,'NR1H4'),
event('MDFIC',control,'NR1H2'),
event('NR1H2',regulate,'NR1H4'),
event('NR1H4',suppress,'NR1H2'),
event('BAAT',decrease,'NR1H2'),
event('NR1H2',enhance,'RXR'),
event('RXR',enhance,'RXR'),
event('NR1H2',involve,'MDFIC'),
event('NR1H3',induce,'MDFIC'),
event('NR1H2',recruit,'NR1H2'),
event('NR1H2',emerge,'NR1H2'),
event('CYP7A1',enhance,'NR1H2'),
event('NR0B2',enhance,'NR1H2'),
event('NR0B2',decrease,'NR1H2'),
event('NR0B2',decrease,'CYP7A1'),
event('NR1H2',suppress,'MDFIC'),
event('NR1H2',suppress,'oxysterols'),
event('NR1H2',modulate,'NR1H3'),
event('NR1H2',reduce,'MDFIC'),
event('NR1H3',reduce,'MDFIC'),
event('CYP7A1',control,'CYP7A1'),
event('CYP7A1',increase,'CYP7A1'),
event('CYP7A1',decrease,'NR1H2'),
event('CYP7A1',decrease,'CYP7A1'),
event('CYP7A1',decrease,'NR1H3'),
event('CYP7A1',phosphorylate,'NR1H2'),
event('CYP7A1',phosphorylate,'CYP7A1'),
event('CYP7A1',phosphorylate,'NR1H3'),
event('CYP7A1',combine,'NR1H2'),
event('CYP7A1',combine,'CYP7A1'),
event('CYP7A1',combine,'NR1H3'),
event('NR1H2',suppress,'NR1H4'),
event('NR1H3',suppress,'NR1H4'),
event('NR1H4',suppress,'NR1H4'),
event('NR1H4',mediate,'NR1H2'),
event('NR1H4',mediate,'NR1H3'),
event('NR1H3',mediate,'NR1H4'),
event('NR1H4',mediate,'NR1H4'),
event('NR1H3',bind,'NR1H4'),
event('NR1H4',bind,'NR1H3'),
event('NR1H2',modulate,'CYP7A1'),
event('NR1H3',modulate,'CYP7A1'),
event('BAAT',increase,'NR1H3'),
event('NR0B2',affect,'NR0B2'),
event('NR1H2',stimulate,'CYP7A1'),
event('NR1H3',stimulate,'CYP7A1'),
event('NR1H2',inhibit,'bile acid'),
event('NR1H3',inhibit,'bile acid'),
event('NR0B2',inhibit,'bile acid'),
event('NR1H3',reduce,'bile acid'),
event('NR0B2',reduce,'bile acid'),
event('NR1H2',activate,'NR0B2'),
event('NR1H3',activate,'NR0B2'),
event('NR1H2',stimulate,'bile acid'),
event('NR1H3',stimulate,'bile acid'),
event('NR1H2',stimulate,'MDFIC'),
event('NR1H3',stimulate,'MDFIC'),
event('NR1H3',regulate,'NR0B2'),
event('NR1H2',antagonize,'CYP7A1'),
event('NR1H2',antagonize,'RXR'),
event('NR1H3',antagonize,'CYP7A1'),
event('NR1H3',antagonize,'RXR'),
event('NR1H4',express,'NR1H4'),
event('CYP7A1',regulate,'bile acid'),
event('oxysterols',induce,'CYP7A1'),
event('MDFIC',induce,'CYP7A1'),
event('CYP7A1',bind,'NR1H4'),
event('CYP7A1',bind,'NR0B2'),
event('bile acid',lead,'NR0B2'),
event('CYP7A1',lead,'NR0B2'),
event('NR1H4',lead,'NR0B2'),
event('MDFIC',lead,'NR0B2'),
event('NR0B2',inhibit,'CYP7A1'),
event('NR0B2',inactivate,'NR5A2'),
event('NR0B2',inhibit,'NR0B2'),
event('NR5A2',lead,'CYP7A1'),
event('NR5A2',lead,'NR0B2'),
event('NR0B2',lead,'NR0B2'),
event('CYP7A1',bind,'NR5A2'),
event('NR0B2',enhance,'NR5A2'),
event('NR0B2',enhance,'NR0B2'),
event('CYP7A1',increase,'NR1H3'),
event('CYP7A1',increase,'NR0B2'),
event('MDFIC',increase,'NR0B2'),
event('NR5A2',enhance,'CYP7A1'),
event('NR5A2',suppress,'CYP7A1'),
event('NR1H3',support,'NR1H3'),
event('RXR',support,'NR1H3'),
event('NR1H2',decrease,'RXR'),
event('CYP7A1',associate,'MDFIC'),
event('CYP7A1',enhance,'MDFIC'),
event('MDFIC',target,'CYP7A1'),
event('NR1H3',modulate,'NR1H2'),
event('BAAT',control,'NR1H2'),
event('NR1H2',suppress,'BAAT'),
event('NR1H2',translate,'NR1H2'),
event('NR1H2',translate,'NR1H3'),
event('NR1H3',translate,'NR1H2'),
event('NR1H3',translate,'NR1H3'),
event('CYP7A1',mediate,'NR1H2'),
event('CYP7A1',mediate,'NR1H3'),
event('NR1H4',enhance,'NR1H2'),
event('CYP7A1',enhance,'NR1H3'),
event('NR1H4',enhance,'NR1H3'),
event('CYP7A1',enhance,'NR1H4'),
event('NR1H3',enhance,'NR1H4'),
event('NR1H3',increase,'NR1H4'),
event('NR1H2',mediate,'CYP7A1'),
event('NR1H3',mediate,'CYP7A1'),
event('BAAT',express,'BAAT'),
event('NR1H2',induce,'BAAT'),
event('NR1H2',mediate,'BAAT'),
event('BAAT',reduce,'BAAT'),
event('BAAT',increase,'BAAT'),
event('NR1H2',promote,'BAAT'),
event('BAAT',control,'BAAT'),
event('BAAT',induce,'BAAT'),
event('BAAT',suppress,'BAAT'),
event('BAAT',change,'BAAT'),
event('BAAT',detect,'CHROMR'),
event('BAAT',decrease,'BAAT'),
event('NR1H2',activate,'BAAT'),
event('BAAT',activate,'NR1H2'),
event('NR1H2',increase,'BAAT'),
event('BAAT',associate,'BAAT'),
event('BAAT',activate,'BAAT'),
event('MDFIC',change,'BAAT'),
event('bile acid',enhance,'BAAT'),
event('MDFIC',enhance,'BAAT'),
event('NR1H2',change,'BAAT'),
event('MDFIC',activate,'BAAT'),
event('BAAT',stimulate,'BAAT'),
event('BAAT',prevent,'BAAT'),
event('BAAT',regulate,'BAAT'),
event('MDFIC',increase,'BAAT'),
event('bile acid',promote,'BAAT'),
event('MDFIC',promote,'BAAT'),
event('BAAT',relate,'BAAT'),
event('CH25H',activate,'NR1H2'),
event('NR1H2',interact,'RXR'),
event('NR1H4',interact,'RXR'),
event('NR1H2',express,'NR1H4'),
event('NR1H4',bind,'RXR'),
event('CYP7A1',stimulate,'CYP7A1'),
event('oxysterols',activate,'RXR'),
event('CYP7A1',activate,'RXR'),
event('oxysterols',bind,'CYP7A1'),
event('RXR',bind,'CYP7A1'),
event('RXR',stimulate,'CYP7A1'),
event('CYP7A1',interact,'NR1H2'),
event('CYP7A1',interact,'NR1H3'),
event('CYP7A1',interact,'RXR'),
event('NR1H2',associate,'RXR'),
event('bile acid',target,'NR1H4'),
event('bile acid',target,'NR0B2'),
event('NR1H2',activate,'NR1H4'),
event('NR1H3',activate,'NR1H4'),
event('NR1H4',activate,'NR1H4'),
event('CYP7A1',inhibit,'bile acid'),
event('CYP7A1',inhibit,'NR1H4'),
event('NR1H3',inhibit,'NR1H4'),
event('NR1H2',inhibit,'MDFIC'),
event('CYP7A1',inhibit,'MDFIC'),
event('NR1H3',inhibit,'MDFIC'),
event('NR1H4',suppress,'CYP7A1'),
event('CYP7A1',express,'oxysterols'),
event('bile acid',require,'CYP7A1'),
event('oxysterols',require,'CYP7A1'),
event('CYP7A1',limit,'oxysterols'),
event('oxysterols',bind,'NR1H3'),
event('NR1H2',antagonize,'NR1H3'),
event('oxysterols',antagonize,'NR1H2'),
event('oxysterols',antagonize,'NR1H3'),
event('NR1H3',relate,'NR1H2'),
event('NR1H2',relate,'NR1H3'),
event('NR1H3',relate,'NR1H3'),
event('oxysterols',decrease,'NR1H2'),
event('oxysterols',recruit,'NR1H2'),
event('MDFIC',recruit,'NR1H2'),
event('MDFIC',support,'NR1H2'),
event('CYP7A1',reduce,'NR1H2'),
event('oxysterols',reveal,'NR1H2'),
event('oxysterols',develop,'NR1H2'),
event('CH25H',control,'CH25H'),
event('CH25H',trigger,'CH25H'),
event('MDFIC',trigger,'CH25H'),
event('CH25H',induce,'CH25H'),
event('FOXA2',bind,'FOXA2'),
event('NR1H2',inhibit,'FOXA2'),
event('FOXA2',reveal,'FOXA2'),
event('CH25H',enhance,'CH25H'),
event('NR1H2',lead,'oxysterols'),
event('oxysterols',modulate,'oxysterols'),
event('oxysterols',activate,'oxysterols'),
event('oxysterols',regulate,'CH25H'),
event('oxysterols',regulate,'CYP7A1'),
event('oxysterols',raise,'NR1H2'),
event('BAAT',increase,'RXR'),
event('bile acid',increase,'RXR'),
event('BAAT',enhance,'RXR'),
event('RXR',require,'MDFIC'),
event('RXR',retain,'RXR'),
event('NR1H4',heterodimerize,'RXR'),
event('NR1H4',interact,'NR0B2'),
event('MDFIC',induce,'NR0B2'),
event('RXR',express,'RXR'),
event('NR1H4',associate,'bile acid'),
event('NR1H4',associate,'NR1H4'),
event('NR1H4',recruit,'RXR'),
event('NR1H4',recruit,'NR1H4'),
event('RXR',enhance,'NR1H4'),
event('NR1H4',modulate,'NR1H4'),
event('bile acid',mediate,'CYP7A1'),
event('RXR',mediate,'CYP7A1'),
event('NR1H4',mediate,'CYP7A1'),
event('RXR',regulate,'CYP7A1'),
event('RXR',decrease,'RXR'),
event('MDFIC',induce,'NR1H4'),
event('NR1H4',mediate,'MDFIC'),
event('CYP7A1',reduce,'NR5A2'),
event('NR0B2',reduce,'NR5A2'),
event('CYP7A1',reduce,'MDFIC'),
event('NR0B2',reduce,'MDFIC'),
event('NR1H2',associate,'CYP7A1'),
event('NR1H4',associate,'CYP7A1'),
event('RXR',increase,'CYP7A1'),
event('CYP7A1',increase,'RXR'),
event('NR1H4',increase,'RXR'),
event('CYP7A1',mediate,'CYP7A1'),
event('RXR',bind,'NR1H4'),
event('RXR',induce,'NR1H4'),
event('RXR',change,'NR1H4'),
event('NR1H4',change,'NR1H4'),
event('RXR',affect,'NR1H4'),
event('RXR',target,'NR1H4'),
event('MDFIC',target,'NR1H4'),
event('BAAT',increase,'SRY'),
event('SRY',increase,'BAAT'),
event('NR1H4',lead,'CYP7A1'),
event('CYP7A1',reduce,'NR1H4'),
event('NR0B2',reduce,'NR1H4'),
event('NR0B2',regulate,'NR0B2'),
event('NR0B2',associate,'NR0B2'),
event('NR1H4',combine,'NR1H4'),
event('NR0B2',combine,'NR1H4'),
event('NR1H4',combine,'NR0B2'),
event('NR0B2',combine,'NR0B2'),
event('NR1H4',combine,'MDFIC'),
event('NR0B2',combine,'MDFIC'),
event('NR0B2',control,'NR0B2'),
event('NR0B2',develop,'NR0B2'),
event('MDFIC',regulate,'NR0B2'),
event('NR1H2',stimulate,'NR1H4'),
event('MDFIC',inhibit,'NR0B2'),
event('NR0B2',induce,'NR0B2'),
event('NR0B2',regulate,'NR5A2'),
event('NR5A2',bind,'NR0B2'),
event('NR5A2',interact,'NR5A2'),
event('NR5A2',mediate,'NR0B2'),
event('CYP7A1',raise,'CYP7A1'),
event('CYP7A1',raise,'NR0B2'),
event('CYP7A1',inhibit,'NR0B2'),
event('NR0B2',interact,'NR0B2'),
event('NR0B2',recruit,'NR5A2'),
event('NR5A2',target,'NR5A2'),
event('NR0B2',target,'NR5A2'),
event('NR5A2',inhibit,'NR5A2'),
event('NR0B2',enhance,'NR1H4'),
event('CYP7A1',interact,'NR1H4'),
event('NR0B2',interact,'NR1H4'),
event('CYP7A1',interact,'NR0B2'),
event('CYP7A1',enhance,'NR0B2'),
event('CYP7A1',recruit,'NR1H4'),
event('NR0B2',recruit,'NR1H4'),
event('CYP7A1',recruit,'NR0B2'),
event('NR0B2',recruit,'NR0B2'),
event('CYP7A1',target,'NR1H4'),
event('CYP7A1',target,'NR0B2'),
event('NR0B2',target,'NR0B2'),
event('NR1H4',lead,'bile acid'),
event('NR1H4',lead,'NR1H4'),
event('bile acid',increase,'NR0B2'),
event('NR0B2',phosphorylate,'bile acid'),
event('NR0B2',phosphorylate,'NR0B2'),
event('CYP7A1',induce,'NR1H4'),
event('NR0B2',affect,'CYP7A1'),
event('NR1H4',express,'NR0B2'),
event('NR0B2',induce,'CYP7A1'),
event('NR0B2',target,'CYP7A1'),
event('bile acid',regulate,'NR0B2'),
event('NR0B2',associate,'CYP7A1'),
event('NR1H4',decrease,'NR0B2'),
event('NR5A2',mediate,'CYP7A1'),
event('CYP7A1',decrease,'NR0B2'),
event('NR5A2',target,'CYP7A1'),
event('NR5A2',inhibit,'CYP7A1'),
event('bile acid',target,'CYP7A1'),
event('bile acid',increase,'CYP7A1'),
event('NR5A2',regulate,'NR5A2'),
event('bile acid',suppress,'NR5A2'),
event('bile acid',suppress,'NR0B2'),
event('NR1H2',inhibit,'NR5A2'),
event('NR5A2',mediate,'bile acid'),
event('NR1H4',mediate,'bile acid'),
event('NR0B2',mediate,'bile acid'),
event('NR1H4',suppress,'NR5A2'),
event('NR0B2',suppress,'CYP7A1'),
event('NR0B2',suppress,'NR5A2'),
event('MDFIC',suppress,'NR5A2'),
event('NR5A2',bind,'NR1H2'),
event('NR5A2',bind,'NR1H3'),
event('NR1H2',enhance,'NR5A2'),
event('NR1H2',combine,'NR0B2'),
event('CYP7A1',combine,'NR0B2'),
event('NR5A2',combine,'NR0B2'),
event('NR1H3',combine,'NR0B2'),
event('NR5A2',bind,'CYP7A1'),
event('NR0B2',bind,'CYP7A1'),
event('NR0B2',bind,'NR1H2'),
event('NR0B2',bind,'NR1H3'),
event('NR5A2',recruit,'NR1H2'),
event('NR1H3',recruit,'NR1H2'),
event('NR0B2',recruit,'NR1H2'),
event('NR5A2',increase,'NR1H2'),
event('NR0B2',increase,'NR1H2'),
event('NR5A2',increase,'NR1H3'),
event('NR0B2',increase,'NR1H3'),
event('NR5A2',increase,'NR1H4'),
event('NR0B2',increase,'NR1H4'),
event('NR1H2',increase,'NR0B2'),
event('NR5A2',increase,'NR0B2'),
event('NR1H3',increase,'NR0B2'),
event('CYP7A1',increase,'MDFIC'),
event('NR5A2',increase,'MDFIC'),
event('NR1H2',combine,'NR1H2'),
event('NR5A2',combine,'NR1H2'),
event('NR1H3',combine,'NR1H2'),
event('NR1H2',combine,'CYP7A1'),
event('NR5A2',combine,'CYP7A1'),
event('NR1H3',combine,'CYP7A1'),
event('NR1H2',combine,'NR1H3'),
event('NR5A2',combine,'NR1H3'),
event('NR1H3',combine,'NR1H3'),
event('NR1H2',combine,'NR1H4'),
event('CYP7A1',combine,'NR1H4'),
event('NR5A2',combine,'NR1H4'),
event('NR1H3',combine,'NR1H4'),
event('NR1H2',combine,'MDFIC'),
event('CYP7A1',combine,'MDFIC'),
event('NR5A2',combine,'MDFIC'),
event('NR1H3',combine,'MDFIC'),
event('MDFIC',promote,'CYP7A1'),
event('CYP7A1',associate,'NR1H2'),
event('CYP7A1',associate,'NR0B2'),
event('CYP7A1',prevent,'CYP7A1'),
event('NR0B2',prevent,'CYP7A1'),
event('NR1H4',involve,'NR0B2'),
event('MDFIC',involve,'NR0B2'),
event('CYP7A1',affect,'NR1H4'),
event('NR0B2',affect,'NR1H4'),
event('NR1H4',control,'NR0B2'),
event('NR1H4',reduce,'NR1H4'),
event('bile acid',involve,'NR0B2'),
event('CYP7A1',involve,'NR0B2'),
event('CYP7A1',associate,'bile acid'),
event('CYP7A1',reduce,'bile acid'),
event('NR1H2',bind,'NR5A2'),
event('NR0B2',bind,'NR5A2'),
event('NR5A2',change,'NR0B2'),
event('NR0B2',change,'NR0B2'),
event('NR5A2',reveal,'NR0B2'),
event('NR0B2',reveal,'NR0B2'),
event('NR5A2',require,'NR0B2'),
event('NR0B2',interact,'NR5A2'),
event('NR0B2',express,'NR0B2'),
event('bile acid',control,'CYP7A1'),
event('bile acid',control,'NR0B2'),
event('NR0B2',control,'CYP7A1'),
event('NR0B2',mediate,'CYP7A1'),
event('NR0B2',mediate,'MDFIC'),
event('NR0B2',involve,'NR0B2'),
event('CYP7A1',interact,'MDFIC'),
event('CYP7A1',induce,'MDFIC'),
event('NR0B2',enhance,'CYP7A1'),
event('NR0B2',mediate,'NR0B2'),
event('NR1H4',decrease,'NR1H2'),
event('NR1H4',decrease,'NR1H4'),
event('NR1H4',decrease,'bile acid'),
event('CYP7A1',decrease,'MDFIC'),
event('bile acid',inactivate,'CYP7A1'),
event('bile acid',inactivate,'NR1H4'),
event('NR1H4',inactivate,'CYP7A1'),
event('NR1H4',inactivate,'NR1H4'),
event('MDFIC',inactivate,'CYP7A1'),
event('MDFIC',inactivate,'NR1H4'),
event('NR5A2',suppress,'NR1H2'),
event('NR5A2',suppress,'NR0B2'),
event('NR1H2',suppress,'NR5A2'),
event('NR5A2',suppress,'NR5A2'),
event('bile acid',heterodimerize,'NR5A2'),
event('NR1H2',heterodimerize,'NR5A2'),
event('NR5A2',heterodimerize,'NR5A2'),
event('NR0B2',heterodimerize,'NR5A2'),
event('NR5A2',involve,'NR0B2'),
event('bile acid',activate,'NR5A2'),
event('bile acid',activate,'NR0B2'),
event('NR5A2',activate,'NR0B2'),
event('MDFIC',heterodimerize,'NR5A2'),
event('NR0B2',suppress,'MDFIC'),
event('NR1H4',activate,'NR0B2'),
event('MDFIC',activate,'NR0B2'),
event('NR0B2',induce,'NR1H2'),
event('NR0B2',bind,'NR0B2'),
event('NR1H4',associate,'MDFIC'),
event('bile acid',regulate,'NR1H4'),
event('NR1H4',regulate,'NR1H4'),
event('NR0B2',activate,'bile acid'),
event('NR0B2',activate,'NR1H4'),
event('CYP7A1',decrease,'NR1H4'),
event('bile acid',activate,'CYP7A1'),
event('NR1H4',activate,'CYP7A1'),
event('CYP7A1',change,'NR1H4'),
event('NR0B2',change,'NR1H4'),
event('NR1H2',interact,'CYP7A1'),
event('NR1H2',interact,'NR5A2'),
event('NR1H4',interact,'CYP7A1'),
event('NR1H4',interact,'NR5A2'),
event('NR0B2',interact,'CYP7A1'),
event('MDFIC',induce,'NR5A2'),
event('NR0B2',associate,'NR5A2'),
event('CYP7A1',require,'NR5A2'),
event('CYP7A1',require,'NR0B2'),
event('NR0B2',involve,'NR5A2'),
event('CYP7A1',require,'NR1H4'),
event('NR1H4',require,'NR1H4'),
event('bile acid',bind,'CYP7A1'),
event('NR1H4',bind,'CYP7A1'),
event('NR5A2',stimulate,'CYP7A1'),
event('NR0B2',stimulate,'CYP7A1'),
event('NR5A2',stimulate,'NR1H4'),
event('NR0B2',stimulate,'NR1H4'),
event('NR5A2',induce,'CYP7A1'),
event('NR0B2',inhibit,'NR1H4'),
event('NR0B2',induce,'NR5A2'),
event('NR5A2',inhibit,'NR0B2'),
event('NR5A2',regulate,'CYP7A1'),
event('NR0B2',regulate,'CYP7A1'),
event('CYP7A1',activate,'NR0B2'),
event('CYP7A1',limit,'CYP7A1'),
event('NR0B2',relate,'NR0B2'),
event('NR0B2',modulate,'NR5A2'),
event('NR0B2',increase,'NR5A2'),
event('CYP7A1',reveal,'CYP7A1'),
event('CYP7A1',regulate,'NR1H2'),
event('CYP7A1',regulate,'NR0B2'),
event('NR1H4',decrease,'CYP7A1'),
event('NR1H4',limit,'CYP7A1'),
event('MDFIC',reveal,'NR0B2'),
event('CYP7A1',increase,'BAAT'),
event('NR0B2',increase,'BAAT'),
event('NR0B2',reduce,'BAAT'),
event('NR0B2',reduce,'CYP7A1'),
event('NR0B2',reveal,'NR1H2'),
event('NR0B2',express,'MDFIC'),
event('NR0B2',change,'CYP7A1'),
event('CYP7A1',relate,'NR0B2'),
event('CYP7A1',involve,'MDFIC'),
event('NR1H4',reduce,'bile acid'),
event('NR1H4',reduce,'CYP7A1'),
event('NR5A2',promote,'CYP7A1'),
event('NR5A2',promote,'NR0B2'),
event('CYP7A1',antagonize,'NR1H4'),
event('bile acid',bind,'NR1H4'),
event('NR1H2',lead,'CYP7A1'),
event('MDFIC',target,'NR0B2'),
event('NR1H2',promote,'NR5A2'),
event('NR5A2',promote,'NR5A2'),
event('NR0B2',decrease,'NR0B2'),
event('CYP7A1',detect,'CYP7A1'),
event('NR0B2',detect,'CYP7A1'),
event('CYP7A1',detect,'NR0B2'),
event('NR0B2',detect,'NR0B2'),
event('CYP7A1',relate,'MDFIC'),
event('NR5A2',relate,'MDFIC'),
event('NR0B2',relate,'MDFIC'),
event('MDFIC',decrease,'CYP7A1'),
event('MDFIC',decrease,'NR5A2'),
event('MDFIC',decrease,'NR0B2'),
event('MDFIC',activate,'NR5A2'),
event('NR0B2',reduce,'NR0B2'),
event('CYP7A1',relate,'bile acid'),
event('NR1H4',relate,'MDFIC'),
event('NR1H4',enhance,'bile acid'),
event('NR1H4',enhance,'MDFIC'),
event('bile acid',reduce,'CYP7A1'),
event('NR0B2',induce,'NR1H4'),
event('NR0B2',decrease,'NR1H4'),
event('NR1H2',promote,'NR1H4'),
event('CYP7A1',promote,'NR1H4'),
event('NR1H4',promote,'NR1H4'),
event('NR0B2',promote,'NR1H4'),
event('bile acid',inhibit,'NR0B2'),
event('NR1H4',involve,'NR1H4'),
event('NR1H4',induce,'FOXA2'),
event('NR1H4',interact,'NR1H4'),
event('MDFIC',interact,'NR1H4'),
event('FOXA2',interact,'NR1H4'),
event('FOXA2',enhance,'NR1H4'),
event('NR1H4',enhance,'FOXA2'),
event('FOXA2',enhance,'FOXA2'),
event('FOXA2',regulate,'NR1H4'),
event('bile acid',increase,'NR1H4'),
event('bile acid',promote,'NR1H4'),
event('NR5A2',associate,'CYP7A1'),
event('CYP7A1',increase,'NR5A2'),
event('NR1H4',control,'NR1H4'),
event('bile acid',bind,'NR0B2'),
event('CYP7A1',activate,'CYP7A1'),
event('NR5A2',activate,'CYP7A1'),
event('NR5A2',involve,'SRY'),
event('MDFIC',control,'NR5A2'),
event('SRY',relate,'CHROMR'),
event('SRY',modulate,'BAAT'),
event('NR1H4',express,'bile acid'),
event('CYP7A1',regulate,'NR1H4'),
event('bile acid',inhibit,'NR1H4'),
event('NR1H4',support,'NR1H4'),
event('CYP7A1',lead,'CYP7A1'),
event('CYP7A1',change,'bile acid'),
event('CYP7A1',induce,'bile acid'),
event('CYP7A1',affect,'bile acid'),
event('bile acid',change,'CYP7A1'),
event('NR1H4',change,'CYP7A1'),
event('NR1H4',emerge,'bile acid'),
event('NR1H4',relate,'NR1H4'),
event('NR1H4',develop,'NR1H4'),
event('bile acid',suppress,'CYP7A1'),
event('CHROMR',suppress,'NR1H4'),
event('NR1H4',bind,'bile acid'),
event('CYP7A1',involve,'NR5A2'),
event('NR1H4',involve,'NR5A2'),
event('NR1H4',bind,'NR5A2'),
event('MDFIC',bind,'NR5A2'),
event('NR1H4',require,'NR5A2'),
event('NR5A2',support,'CYP7A1'),
event('NR5A2',support,'NR1H4'),
event('MDFIC',regulate,'NR1H4'),
event('bile acid',trigger,'NR1H4'),
event('NR1H4',involve,'bile acid'),
event('MDFIC',mediate,'CYP7A1'),
event('bile acid',mediate,'NR1H4'),
event('CYP7A1',develop,'bile acid'),
event('CYP7A1',develop,'CYP7A1'),
event('NR1H4',stimulate,'NR1H4'),
event('NR1H4',modulate,'bile acid'),
event('MDFIC',reduce,'NR1H4'),
event('bile acid',control,'NR1H4'),
event('CYP7A1',require,'CYP7A1'),
event('bile acid',require,'NR1H4'),
event('NR1H4',require,'CYP7A1'),
event('bile acid',reveal,'CYP7A1'),
event('NR1H4',reveal,'CYP7A1'),
event('NR1H4',reduce,'NR1H2'),
event('NR1H4',reduce,'NR0B2'),
event('NR1H4',regulate,'MDFIC'),
event('NR1H4',infect,'NR1H4'),
event('NR1H4',antagonize,'NR1H4'),
event('MDFIC',express,'NR1H4'),
event('MDFIC',prevent,'NR1H4'),
event('NR1H4',require,'MDFIC'),
event('CYP7A1',control,'bile acid'),
event('MDFIC',activate,'NR1H4'),
event('MDFIC',inhibit,'NR1H4'),
event('MDFIC',reduce,'CYP7A1'),
event('NR1H4',trigger,'CYP7A1'),
event('CHROMR',change,'NR1H4'),
event('NR1H4',reduce,'CHROMR'),
event('MDFIC',increase,'CYP7A1'),
event('CYP7A1',inactivate,'NR1H4'),
event('MDFIC',control,'NR1H4'),
event('NR1H4',involve,'MDFIC'),
event('CYP7A1',express,'bile acid'),
event('NR1H4',increase,'NR1H2'),
event('NR1H4',lead,'MDFIC'),
event('bile acid',decrease,'CYP7A1'),
event('bile acid',release,'NR1H4'),
event('NR1H4',modulate,'CYP7A1'),
event('bile acid',lead,'CYP7A1'),
event('NR1H4',suppress,'NR0B2'),
event('NR1H4',prevent,'NR1H4'),
event('MDFIC',antagonize,'NR1H4'),
event('CYP7A1',control,'NR1H2'),
event('CYP7A1',change,'NR1H2'),
event('CYP7A1',change,'CYP7A1'),
event('MDFIC',induce,'NR1H2'),
event('NR1H4',inhibit,'MDFIC'),
event('NR1H2',modulate,'NR1H4'),
event('CYP7A1',phosphorylate,'NR1H4'),
event('CYP7A1',phosphorylate,'MDFIC'),
event('NR1H4',stimulate,'CYP7A1'),
event('SRY',relate,'MDFIC'),
event('SRY',lead,'SRY'),
event('SRY',decrease,'SRY'),
event('SRY',associate,'SRY'),
event('SRY',change,'SRY'),
event('SRY',affect,'SRY'),
event('SRY',support,'SRY'),
event('SRY',decrease,'NR1H2'),
event('SRY',collect,'MDFIC'),
event('SRY',express,'MDFIC'),
event('SRY',detect,'MDFIC'),
event('CYP7A1',relate,'NR1H2'),
event('NR1H2',change,'CYP7A1'),
event('CYP7A1',reduce,'RXR'),
event('MDFIC',stimulate,'CYP7A1'),
event('NR1H2',activate,'CYP7A1'),
event('MDFIC',activate,'CYP7A1'),
event('NR1H2',express,'CYP7A1'),
event('CYP7A1',detect,'bile acid'),
event('CYP7A1',target,'bile acid'),
event('CHROMR',require,'CHROMR'),
event('CHROMR',require,'MDFIC'),
event('NR5A2',reduce,'CYP7A1'),
event('NR5A2',control,'CYP7A1'),
event('MDFIC',change,'CYP7A1'),
event('bile acid',destabilize,'CYP7A1'),
event('CYP7A1',destabilize,'CYP7A1'),
event('MDFIC',convert,'CYP7A1'),
event('RXR',enhance,'NR1H2'),
event('RXR',increase,'bile acid'),
event('RXR',increase,'RXR'),
event('CYP7A1',require,'bile acid'),
event('CYP7A1',require,'NR1H2'),
event('CYP7A1',involve,'CYP7A1'),
event('CYP7A1',interact,'CYP7A1'),
event('CYP7A1',involve,'bile acid'),
event('NR5A2',mediate,'NR5A2'),
event('NR5A2',involve,'NR5A2'),
event('MDFIC',express,'CYP7A1'),
event('CYP7A1',suppress,'bile acid'),
event('CYP7A1',associate,'BAAT'),
event('bile acid',promote,'CYP7A1'),
event('bile acid',promote,'NR1H2'),
event('CYP7A1',phosphorylate,'bile acid'),
event('CYP7A1',mediate,'bile acid'),
event('CYP7A1',affect,'CYP7A1'),
event('bile acid',stimulate,'CYP7A1'),
event('CYP7A1',combine,'NR5A2'),
event('NR5A2',combine,'NR5A2'),
event('NR5A2',affect,'NR5A2'),
event('MDFIC',control,'CYP7A1'),
event('MDFIC',modulate,'CYP7A1'),
event('MDFIC',regulate,'NR5A2'),
event('RUNX1',induce,'RXR'),
event('RUNX1',associate,'RUNX1'),
event('RUNX1',express,'NR0B2'),
event('NR5A2',develop,'NR5A2'),
event('NR5A2',involve,'MDFIC'),
event('NR5A2',stimulate,'NR5A2'),
event('NR5A2',lead,'NR5A2'),
event('BAAT',express,'NR5A2'),
event('BAAT',target,'NR5A2'),
event('NR5A2',associate,'MDFIC'),
event('NR5A2',relate,'NR5A2'),
event('NR5A2',increase,'bile acid'),
event('NR5A2',support,'NR5A2'),
event('NR5A2',induce,'NR5A2'),
event('NR5A2',control,'NR5A2'),
event('NR5A2',increase,'NR5A2'),
event('NR5A2',change,'NR5A2'),
event('NR5A2',detect,'NR5A2'),
event('NR5A2',raise,'NR5A2'),
event('NR5A2',enhance,'NR1H2'),
event('NR5A2',enhance,'MDFIC'),
event('NR5A2',reduce,'NR5A2'),
event('NR5A2',interact,'MDFIC'),
event('NR5A2',enhance,'NR5A2'),
event('NRBF2',target,'RXR'),
event('NR0B2',interact,'NR1H2'),
event('NR0B2',interact,'NR1H3'),
event('NR0B2',lead,'NR1H2'),
event('FOXA2',target,'FOXA2'),
event('FOXA2',lead,'FOXA2'),
event('NR1H2',express,'FOXA2'),
event('NR0B2',mediate,'NR1H4'),
event('NR1H4',reduce,'RXR'),
event('NR0B2',bind,'RXR'),
event('RXR',bind,'NR0B2'),
event('NR0B2',increase,'RXR'),
event('RXR',increase,'NR0B2'),
event('NR0B2',interact,'RXR'),
event('RXR',modulate,'NR1H4'),
event('NR0B2',support,'NR0B2'),
event('RXR',target,'NR0B2'),
event('NR0B2',bind,'NR1H4'),
event('NR1H4',mediate,'NR0B2'),
event('RXR',regulate,'NR0B2'),
event('RXR',modulate,'NR0B2'),
event('NR1H4',modulate,'NR0B2'),
event('RXR',activate,'NR1H4'),
event('NR0B2',mediate,'NR1H2'),
event('NR0B2',activate,'NR0B2'),
event('NR5A2',regulate,'NR0B2'),
event('MDFIC',enhance,'NR0B2'),
event('NR1H2',modulate,'NR0B2'),
event('NR0B2',modulate,'NR0B2'),
event('NR0B2',affect,'NR5A2'),
event('NR1H2',involve,'NR0B2'),
event('NR0B2',release,'NR0B2'),
event('NR0B2',regulate,'NR1H2'),
event('NR0B2',suppress,'NR1H2'),
event('NR0B2',stimulate,'NR0B2'),
event('MDFIC',stimulate,'NR0B2'),
event('NR0B2',lead,'MDFIC'),
event('NR0B2',stabilize,'NR0B2'),
event('NR1H2',promote,'NR0B2'),
event('bile acid',emerge,'NR1H4'),
event('RXR',mediate,'NR1H2'),
event('RXR',mediate,'RXR'),
event('RXR',mediate,'NR1H4'),
event('RXR',participate,'NR1H4'),
event('NR1H4',participate,'NR1H4'),
event('NR1H4',develop,'bile acid'),
event('NR1H4',activate,'RXR'),
event('BAAT',decrease,'RXR'),
event('RXR',involve,'RXR'),
event('NR1H4',involve,'RXR'),
event('bile acid',bind,'RXR'),
event('NR1H4',require,'RXR'),
event('RXR',antagonize,'NR1H4'),
event('NR1H4',mediate,'RXR'),
event('NR1H2',decrease,'NR1H4'),
event('RXR',decrease,'NR1H4'),
event('NR1H2',recruit,'RXR'),
event('NR1H2',recruit,'NR1H4'),
event('RXR',recruit,'RXR'),
event('RXR',recruit,'NR1H4'),
event('NR1H4',target,'RXR'),
event('NR1H4',regulate,'RXR'),
event('RXR',regulate,'NR1H4'),
event('MDFIC',heterodimerize,'RXR'),
event('RXR',reveal,'NR1H4'),
event('NR1H4',promote,'RXR'),
event('RXR',develop,'NR1H4'),
event('NR1H4',reveal,'bile acid'),
event('NR0B2',express,'NR1H4'),
event('bile acid',decrease,'NR1H4'),
event('NR1H4',lead,'NR1H2'),
event('NR0B2',associate,'bile acid'),
event('NR1H4',express,'NR1H2'),
event('NR0B2',decrease,'bile acid'),
event('NR5A2',inhibit,'bile acid'),
event('NR5A2',inhibit,'NR1H4'),
event('NR0B2',suppress,'NR1H4'),
event('NR1H4',require,'NR1H2'),
event('NR0B2',require,'NR1H4'),
event('bile acid',antagonize,'NR1H4'),
event('NR0B2',decrease,'NR5A2'),
event('NR1H4',reduce,'NR5A2'),
event('RUNX1',induce,'NR1H4'),
event('NR1H2',suppress,'NR0B2'),
event('NR1H4',emerge,'NR1H4'),
event('NR0B2',reduce,'NR1H2'),
event('bile acid',enhance,'NR0B2'),
event('NR1H4',enhance,'NR0B2'),
event('NR0B2',express,'RXR'),
event('NR5A2',mediate,'NR1H4'),
event('NR5A2',modulate,'NR5A2'),
event('NR5A2',modulate,'NR1H4'),
event('NR5A2',modulate,'NR0B2'),
event('NR5A2',modulate,'MDFIC'),
event('NR1H4',prevent,'NR0B2'),
event('NR0B2',associate,'NR1H4'),
event('NR0B2',associate,'MDFIC'),
event('NR1H4',relate,'NR1H2'),
event('CDX1',relate,'bile acid'),
event('bile acid',change,'NR1H4'),
event('NR1H4',prevent,'bile acid'),
event('NR1H4',prevent,'CYP7A1'),
event('NR0B2',relate,'NR1H4'),
event('NR1H4',reduce,'MDFIC'),
event('NR1H4',change,'bile acid'),
event('NR1H4',promote,'NR0B2'),
event('NR0B2',promote,'NR0B2'),
event('NR1H4',promote,'CYP7A1'),
event('NR1H4',involve,'CYP7A1'),
event('NR1H4',phosphorylate,'NR1H4'),
event('MDFIC',involve,'NR1H3'),
event('NR1H4',promote,'bile acid'),
event('bile acid',suppress,'NR1H4'),
event('MDFIC',affect,'NR1H4'),
event('NR1H4',reduce,'BAAT'),
event('NR1H4',express,'BAAT'),
event('NR1H4',induce,'MDFIC'),
event('NR1H4',suppress,'MDFIC'),
event('NR1H2',involve,'CYP7A1'),
event('CYP7A1',suppress,'NR1H2'),
event('CYP7A1',associate,'NR1H4'),
event('CYP7A1',relate,'NR1H4'),
event('CYP7A1',involve,'NR1H4'),
event('MDFIC',associate,'CYP7A1'),
event('MDFIC',associate,'NR1H4'),
event('CYP7A1',modulate,'NR1H4'),
event('NR1H4',combine,'bile acid'),
event('BAAT',change,'NR1H4'),
event('CDX1',enhance,'CDX1'),
event('CDX1',associate,'bile acid'),
event('CDX1',associate,'CDX1'),
event('NR0B2',mediate,'CDX1'),
event('bile acid',induce,'CDX1'),
event('bile acid',increase,'CDX1'),
event('RXR',suppress,'NR5A2'),
event('MDFIC',regulate,'RXR'),
event('MDFIC',activate,'RXR'),
event('NR5A2',interact,'RXR'),
event('NR1H2',require,'NR5A2'),
event('NR5A2',target,'NR0B2'),
event('NR5A2',mediate,'NR1H2'),
event('NR5A2',induce,'NR0B2'),
event('NR0B2',induce,'MDFIC'),
event('NR0B2',inhibit,'MDFIC'),
event('NR5A2',enhance,'NR0B2'),
event('MDFIC',interact,'NR5A2'),
event('NR1H2',target,'NR5A2'),
event('NR0B2',enhance,'MDFIC'),
event('NR5A2',affect,'NR0B2'),
event('NR5A2',limit,'NR1H4'),
event('NR1H4',limit,'NR1H4'),
event('NR1H4',support,'NR5A2'),
event('NR5A2',bind,'NR1H4'),
event('NR5A2',associate,'NR5A2'),
event('NR5A2',associate,'NR1H4'),
event('NR5A2',recruit,'NR1H4'),
event('NR5A2',target,'NR1H4'),
event('NR1H4',relate,'NR5A2'),
event('FOXA2',activate,'NR5A2'),
event('NR5A2',induce,'NR1H2'),
event('NR5A2',require,'NR5A2'),
event('NR5A2',recognize,'NR5A2'),
event('NR5A2',translate,'NR5A2'),
event('NR1H2',increase,'NR5A2'),
event('NR5A2',induce,'BAAT'),
event('BAAT',change,'NR5A2'),
event('NR1H2',change,'NR5A2'),
event('NR5A2',relate,'BAAT'),
event('NR5A2',relate,'NR1H2'),
event('NR5A2',reveal,'NR5A2'),
event('MDFIC',promote,'NR5A2'),
event('NR1H2',trigger,'NR1H2'),
event('NR5A2',decrease,'NR5A2'),
event('NR5A2',decrease,'MDFIC'),
event('NR5A2',prevent,'NR5A2'),
event('NR5A2',recruit,'NR5A2'),
event('MDFIC',express,'NR5A2'),
event('MDFIC',change,'NR5A2'),
event('MDFIC',require,'NR5A2'),
event('NR5A2',involve,'NR1H2'),
event('BAAT',target,'NR1H2'),
event('BAAT',target,'NR1H3'),
event('NR1H2',decrease,'BAAT'),
event('NR1H3',decrease,'BAAT'),
event('NR1H2',incubate,'NR1H2'),
event('NR1H2',incubate,'NR1H3'),
event('NR1H3',express,'MDFIC'),
event('NR1H3',activate,'BAAT'),
event('NR1H2',relate,'RXR'),
event('NR1H2',express,'RXR'),
event('NR1H2',bind,'MDFIC'),
event('NR1H2',require,'MDFIC'),
event('RXR',antagonize,'NR1H2'),
event('RXR',antagonize,'RXR'),
event('NR1H2',require,'RXR'),
event('NR1H2',prevent,'RXR'),
event('NR1H3',prevent,'NR1H3'),
event('NR1H3',prevent,'RXR'),
event('NR1H2',increase,'RXR'),
event('RXR',involve,'NR1H2'),
event('RXR',activate,'MDFIC'),
event('NR1H2',raise,'RXR'),
event('RXR',raise,'RXR'),
event('RXR',affect,'NR1H2'),
event('RXR',recruit,'NR1H2'),
event('NR1H2',bind,'BAAT'),
event('RXR',bind,'BAAT'),
event('NR1H3',associate,'RXR'),
event('RXR',associate,'RXR'),
event('NR1H3',decrease,'RXR'),
event('RXR',reduce,'NR1H3'),
event('NR1H2',reduce,'RXR'),
event('RXR',reduce,'RXR'),
event('NR1H2',mediate,'RXR'),
event('NR1H3',activate,'RXR'),
event('RXR',regulate,'NR1H3'),
event('RXR',decrease,'NR1H2'),
event('RXR',decrease,'NR1H3'),
event('RXR',control,'NR1H2'),
event('RXR',raise,'NR1H2'),
event('RXR',heterodimerize,'NR1H2'),
event('NR1H2',inhibit,'RXR'),
event('RXR',suppress,'RXR'),
event('NR1H2',heterodimerize,'NR1H2'),
event('NR1H2',reveal,'RXR'),
event('NR0B2',decrease,'NR1H3'),
event('NR0B2',decrease,'RXR'),
event('NR0B2',inhibit,'NR1H3'),
event('NR1H3',interact,'RXR'),
event('NR1H2',control,'NR0B2'),
event('NR1H3',control,'NR0B2'),
event('NR1H3',involve,'NR0B2'),
event('RXR',bind,'MDFIC'),
event('BAAT',associate,'MDFIC'),
event('RXR',associate,'MDFIC'),
event('FOXA2',associate,'MDFIC'),
event('NR1H3',regulate,'NR1H4'),
event('NR1H4',modulate,'NR1H2'),
event('NR0B2',target,'FOXA2'),
event('FOXA2',reduce,'FOXA2'),
event('NR1H2',promote,'CYP7A1'),
event('CYP7A1',promote,'CYP7A1'),
event('CYP7A1',support,'NR1H2'),
event('NR5A2',control,'FOXA2'),
event('FOXA2',change,'NR5A2'),
event('NR5A2',activate,'FOXA2'),
event('FOXA2',increase,'FOXA2'),
event('NR1H2',enhance,'FOXA2'),
event('NR1H2',decrease,'FOXA2'),
event('FOXA2',enhance,'NR1H2'),
event('NR0B2',inactivate,'CYP7A1'),
event('NR0B2',inactivate,'NR0B2')
]).